In [1]:
import json
import glob
import os
from pathlib import Path
import pandas as pd

# ==========================================
# 1. 基础路径配置
# ==========================================
BASE_DIR = Path('/Volumes/KIOXIA/Project/lob')
# 专门建一个干净的文件夹存纯交易数据
OUTPUT_DIR = BASE_DIR / 'raw_transactions_only'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

WEEKS_TO_PROCESS = ['week1', 'week2']

# ==========================================
# 2. 核心提取函数：只抓取真正的成交记录
# ==========================================
def extract_raw_transactions(jsonl_path):
    transactions = []
    
    with open(jsonl_path, 'r', encoding='utf-8') as f:
        for line in f:
            if not line.strip(): continue
            
            data = json.loads(line)
            records = data if isinstance(data, list) else [data]
            
            for rec in records:
                # 【核心过滤逻辑】：根据你的真实文件结构，真正的交易包含 transaction_hash
                if rec.get('event_type') == 'last_trade_price' or 'transaction_hash' in rec:
                    
                    # 提取你要的所有交易相关字段
                    transactions.append({
                        'timestamp': pd.to_datetime(int(rec.get('timestamp')), unit='ms', utc=True),
                        'market': rec.get('market', ''),
                        'asset_id': rec.get('asset_id', ''),
                        'side': rec.get('side', ''),
                        'price': float(rec.get('price')) if rec.get('price') else None,
                        'size': float(rec.get('size')) if rec.get('size') else None,
                        'fee_rate_bps': rec.get('fee_rate_bps', ''),
                        'transaction_hash': rec.get('transaction_hash', '')
                    })
                    
    df_tx = pd.DataFrame(transactions)
    
    # 按照时间排个序
    if not df_tx.empty:
        df_tx.sort_values('timestamp', inplace=True)
        df_tx.reset_index(drop=True, inplace=True)
        
    return df_tx

# ==========================================
# 3. 遍历你指定的全部路径
# ==========================================
for week in WEEKS_TO_PROCESS:
    print(f"\n🚀 开始提取 {week} 的交易数据...")
    
    # 构建输入和输出的完整路径
    CONTRACTS_DIR = BASE_DIR / week / 'contracts' / 'btc'
    WEEK_OUTPUT_DIR = OUTPUT_DIR / week
    WEEK_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # 获取该路径下所有的 jsonl 文件
    jsonl_files = glob.glob(str(CONTRACTS_DIR / '*.jsonl'))
    print(f"   找到 {len(jsonl_files)} 个合约文件，正在处理...")
    
    for file_path in jsonl_files:
        slug = os.path.basename(file_path).replace('.jsonl', '')
        
        # 调用提取函数
        df_contract_txs = extract_raw_transactions(file_path)
        
        # 如果这个文件里有交易数据，就保存下来
        if df_contract_txs is not None and not df_contract_txs.empty:
            out_file = WEEK_OUTPUT_DIR / f"{slug}_raw_txs.parquet"
            df_contract_txs.to_parquet(out_file)
            print(f"     [√] 保存成功 -> {out_file.name} (共 {len(df_contract_txs)} 条交易记录)")
        else:
            print(f"     [!] 跳过 {slug}：未发现任何交易数据")

print("\n🎉 所有路径的数据提取完毕！")

🚀 开始提取 week1 的交易数据...
   找到 627 个合约文件，正在处理...
     [√] 保存成功 -> btc-updown-15m-1765153800_raw_txs.parquet (共 1781 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764838800_raw_txs.parquet (共 1608 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764656100_raw_txs.parquet (共 1917 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765081800_raw_txs.parquet (共 1707 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764792900_raw_txs.parquet (共 3153 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764834300_raw_txs.parquet (共 1946 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765107900_raw_txs.parquet (共 1788 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764567900_raw_txs.parquet (共 773 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764745200_raw_txs.parquet (共 1657 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764603000_raw_txs.parquet (共 3247 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765127700_raw_txs.parquet (共 1655 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765084500_raw_txs.parquet (共 2165 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764810000_raw_txs.parquet (共 1141 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764843300_raw_txs.parquet (共 2014 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764642600_raw_txs.parquet (共 1508 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764981900_raw_txs.parquet (共 715 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765103400_raw_txs.parquet (共 1839 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764918000_raw_txs.parquet (共 2539 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764627300_raw_txs.parquet (共 1827 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764869400_raw_txs.parquet (共 2449 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764675000_raw_txs.parquet (共 2454 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764882000_raw_txs.parquet (共 3046 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765010700_raw_txs.parquet (共 2169 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764673200_raw_txs.parquet (共 2430 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765156500_raw_txs.parquet (共 2020 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764751500_raw_txs.parquet (共 2999 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764620100_raw_txs.parquet (共 1785 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764644400_raw_txs.parquet (共 1855 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765118700_raw_txs.parquet (共 4072 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764845100_raw_txs.parquet (共 2446 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764966600_raw_txs.parquet (共 1090 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764578700_raw_txs.parquet (共 1704 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765082700_raw_txs.parquet (共 2015 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764817200_raw_txs.parquet (共 2120 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764946800_raw_txs.parquet (共 1475 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765068300_raw_txs.parquet (共 2359 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764815400_raw_txs.parquet (共 2258 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765018800_raw_txs.parquet (共 2479 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764779400_raw_txs.parquet (共 1211 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764792000_raw_txs.parquet (共 3284 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765038600_raw_txs.parquet (共 2776 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764973800_raw_txs.parquet (共 2732 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764784800_raw_txs.parquet (共 1492 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765107000_raw_txs.parquet (共 1136 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764623700_raw_txs.parquet (共 903 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764567000_raw_txs.parquet (共 799 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764646200_raw_txs.parquet (共 1839 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764671400_raw_txs.parquet (共 1418 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764603900_raw_txs.parquet (共 1915 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764753300_raw_txs.parquet (共 2737 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765076400_raw_txs.parquet (共 2332 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764755100_raw_txs.parquet (共 1875 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765014300_raw_txs.parquet (共 2105 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764949500_raw_txs.parquet (共 2492 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764789300_raw_txs.parquet (共 2700 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764625500_raw_txs.parquet (共 2025 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764596700_raw_txs.parquet (共 2468 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764841500_raw_txs.parquet (共 3640 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764927900_raw_txs.parquet (共 1309 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764681300_raw_txs.parquet (共 1312 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765086300_raw_txs.parquet (共 1808 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764813600_raw_txs.parquet (共 1268 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765027800_raw_txs.parquet (共 2854 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764652500_raw_txs.parquet (共 1741 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765049400_raw_txs.parquet (共 1415 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764923400_raw_txs.parquet (共 1745 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764810900_raw_txs.parquet (共 1357 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764976500_raw_txs.parquet (共 2582 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764830700_raw_txs.parquet (共 2598 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764595800_raw_txs.parquet (共 2632 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764918900_raw_txs.parquet (共 2020 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764741600_raw_txs.parquet (共 2288 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764688500_raw_txs.parquet (共 3625 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764938700_raw_txs.parquet (共 2525 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764882900_raw_txs.parquet (共 2206 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765146600_raw_txs.parquet (共 1996 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764675900_raw_txs.parquet (共 2176 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764566100_raw_txs.parquet (共 2105 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765106100_raw_txs.parquet (共 1883 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765041300_raw_txs.parquet (共 1900 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764670500_raw_txs.parquet (共 1732 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764814500_raw_txs.parquet (共 1847 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765149300_raw_txs.parquet (共 1554 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765080000_raw_txs.parquet (共 2350 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764972900_raw_txs.parquet (共 824 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764778500_raw_txs.parquet (共 2219 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764590400_raw_txs.parquet (共 2204 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764597600_raw_txs.parquet (共 2609 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764812700_raw_txs.parquet (共 1100 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765087200_raw_txs.parquet (共 1067 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765152000_raw_txs.parquet (共 1737 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765015200_raw_txs.parquet (共 2303 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764677700_raw_txs.parquet (共 2713 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765144800_raw_txs.parquet (共 1241 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765164600_raw_txs.parquet (共 1411 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764657900_raw_txs.parquet (共 2032 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765022400_raw_txs.parquet (共 2854 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764786600_raw_txs.parquet (共 2718 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765048500_raw_txs.parquet (共 3176 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764915300_raw_txs.parquet (共 2028 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765125000_raw_txs.parquet (共 437 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765026900_raw_txs.parquet (共 1975 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764714600_raw_txs.parquet (共 1259 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764653400_raw_txs.parquet (共 1977 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764621900_raw_txs.parquet (共 2759 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764771300_raw_txs.parquet (共 2378 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764987300_raw_txs.parquet (共 3017 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764919800_raw_txs.parquet (共 2609 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764883800_raw_txs.parquet (共 2775 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764689400_raw_txs.parquet (共 3101 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764740700_raw_txs.parquet (共 1728 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764607500_raw_txs.parquet (共 1462 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764939600_raw_txs.parquet (共 2745 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765072800_raw_txs.parquet (共 815 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764811800_raw_txs.parquet (共 1761 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765093500_raw_txs.parquet (共 1378 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765079100_raw_txs.parquet (共 2111 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764594900_raw_txs.parquet (共 3223 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764977400_raw_txs.parquet (共 2337 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764831600_raw_txs.parquet (共 1769 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764768600_raw_txs.parquet (共 2147 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764911700_raw_txs.parquet (共 1262 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764804600_raw_txs.parquet (共 1867 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764619200_raw_txs.parquet (共 62 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764926100_raw_txs.parquet (共 484 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764861300_raw_txs.parquet (共 4495 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764748800_raw_txs.parquet (共 1010 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764660600_raw_txs.parquet (共 1558 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765152900_raw_txs.parquet (共 3481 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764983700_raw_txs.parquet (共 2284 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764969300_raw_txs.parquet (共 2488 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764640800_raw_txs.parquet (共 2054 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764657000_raw_txs.parquet (共 1263 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764985500_raw_txs.parquet (共 2088 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764744300_raw_txs.parquet (共 2603 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764602100_raw_txs.parquet (共 3347 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765097100_raw_txs.parquet (共 1841 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765080900_raw_txs.parquet (共 1542 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764964800_raw_txs.parquet (共 2385 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764972000_raw_txs.parquet (共 1951 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764835200_raw_txs.parquet (共 1225 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764793800_raw_txs.parquet (共 1071 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765102500_raw_txs.parquet (共 1609 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764674100_raw_txs.parquet (共 1864 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764868500_raw_txs.parquet (共 2889 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765085400_raw_txs.parquet (共 1306 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764594000_raw_txs.parquet (共 1294 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764579600_raw_txs.parquet (共 2305 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765119600_raw_txs.parquet (共 1746 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764592200_raw_txs.parquet (共 2445 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765069200_raw_txs.parquet (共 1288 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764816300_raw_txs.parquet (共 2201 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764898200_raw_txs.parquet (共 2137 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765083600_raw_txs.parquet (共 1429 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765133100_raw_txs.parquet (共 3174 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765125900_raw_txs.parquet (共 2876 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764672300_raw_txs.parquet (共 1479 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765011600_raw_txs.parquet (共 1472 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765157400_raw_txs.parquet (共 1621 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765026000_raw_txs.parquet (共 2156 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764621000_raw_txs.parquet (共 2206 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765090800_raw_txs.parquet (共 955 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764783900_raw_txs.parquet (共 1334 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764825300_raw_txs.parquet (共 2503 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764962100_raw_txs.parquet (共 1664 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764840600_raw_txs.parquet (共 2828 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764711900_raw_txs.parquet (共 1476 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764624600_raw_txs.parquet (共 1552 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764995400_raw_txs.parquet (共 2647 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765116900_raw_txs.parquet (共 2443 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764612000_raw_txs.parquet (共 2312 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765136700_raw_txs.parquet (共 3216 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764604800_raw_txs.parquet (共 2063 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764754200_raw_txs.parquet (共 3000 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764948600_raw_txs.parquet (共 2588 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764731700_raw_txs.parquet (共 2094 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764993600_raw_txs.parquet (共 1839 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764647100_raw_txs.parquet (共 2378 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764829800_raw_txs.parquet (共 2897 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765039500_raw_txs.parquet (共 1223 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764871200_raw_txs.parquet (共 3044 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764936000_raw_txs.parquet (共 2970 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764609300_raw_txs.parquet (共 1710 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765135800_raw_txs.parquet (共 2862 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765147500_raw_txs.parquet (共 1984 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765001700_raw_txs.parquet (共 2136 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764569700_raw_txs.parquet (共 1072 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764854100_raw_txs.parquet (共 1623 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764582300_raw_txs.parquet (共 1700 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765109700_raw_txs.parquet (共 2702 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764695700_raw_txs.parquet (共 973 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764888300_raw_txs.parquet (共 509 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764801000_raw_txs.parquet (共 2055 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764852300_raw_txs.parquet (共 3026 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764584100_raw_txs.parquet (共 1794 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764990900_raw_txs.parquet (共 1626 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765112400_raw_txs.parquet (共 2259 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764909000_raw_txs.parquet (共 1371 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764636300_raw_txs.parquet (共 1250 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764572400_raw_txs.parquet (共 2196 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765161900_raw_txs.parquet (共 2259 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764878400_raw_txs.parquet (共 3326 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765062000_raw_txs.parquet (共 2369 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764958500_raw_txs.parquet (共 1667 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765005300_raw_txs.parquet (共 2191 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765142100_raw_txs.parquet (共 1249 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764634500_raw_txs.parquet (共 3017 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764798300_raw_txs.parquet (共 181 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764587700_raw_txs.parquet (共 3049 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764850500_raw_txs.parquet (共 2122 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764936900_raw_txs.parquet (共 2416 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764690300_raw_txs.parquet (共 2319 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765159200_raw_txs.parquet (共 3803 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765009800_raw_txs.parquet (共 2207 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764783000_raw_txs.parquet (共 1337 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765029600_raw_txs.parquet (共 2789 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764580500_raw_txs.parquet (共 2983 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764857700_raw_txs.parquet (共 3099 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764576000_raw_txs.parquet (共 1194 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764711000_raw_txs.parquet (共 2229 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765051200_raw_txs.parquet (共 3203 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765116000_raw_txs.parquet (共 2668 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764632700_raw_txs.parquet (共 1013 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765067400_raw_txs.parquet (共 1195 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764612900_raw_txs.parquet (共 2775 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764896400_raw_txs.parquet (共 1648 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764951300_raw_txs.parquet (共 3169 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764801900_raw_txs.parquet (共 2025 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764844200_raw_txs.parquet (共 3098 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764821700_raw_txs.parquet (共 2158 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764967500_raw_txs.parquet (共 3521 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764990000_raw_txs.parquet (共 1330 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764909900_raw_txs.parquet (共 1492 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765161000_raw_txs.parquet (共 2073 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764735300_raw_txs.parquet (共 2376 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765062900_raw_txs.parquet (共 1966 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764929700_raw_txs.parquet (共 2275 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764750600_raw_txs.parquet (共 34 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764643500_raw_txs.parquet (共 1031 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764704700_raw_txs.parquet (共 1417 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765036800_raw_txs.parquet (共 611 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764997200_raw_txs.parquet (共 1525 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764631800_raw_txs.parquet (共 1311 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765058400_raw_txs.parquet (共 1959 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764932400_raw_txs.parquet (共 1325 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764739800_raw_txs.parquet (共 1739 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764851400_raw_txs.parquet (共 1743 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764691200_raw_txs.parquet (共 3991 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764937800_raw_txs.parquet (共 2798 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764803700_raw_txs.parquet (共 2495 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765096200_raw_txs.parquet (共 1522 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764959400_raw_txs.parquet (共 1671 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765143000_raw_txs.parquet (共 1532 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764799200_raw_txs.parquet (共 2661 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764828000_raw_txs.parquet (共 2473 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764717300_raw_txs.parquet (共 1151 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764635400_raw_txs.parquet (共 2664 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764984600_raw_txs.parquet (共 994 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764633600_raw_txs.parquet (共 1923 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765050300_raw_txs.parquet (共 2478 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764710100_raw_txs.parquet (共 2180 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764661500_raw_txs.parquet (共 2479 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765066500_raw_txs.parquet (共 1487 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764613800_raw_txs.parquet (共 774 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1765158300_raw_txs.parquet (共 1780 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764805500_raw_txs.parquet (共 2052 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764769500_raw_txs.parquet (共 3366 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764581400_raw_txs.parquet (共 2134 条交易记录)
     [√] 保存成功 -> btc-updown-15m-1764963900_raw_txs.parquet (共 1923 条交易记录)

In [3]:
import pandas as pd
from pathlib import Path
import glob
import os

# ==========================================
# 1. 路径配置 (对接你刚才存好的数据)
# ==========================================
BASE_DIR = Path('/Volumes/KIOXIA/Project/lob')
INPUT_DIR = BASE_DIR / 'raw_transactions_only'  # 第一步输出的纯交易数据目录
OUTPUT_DIR = BASE_DIR / 'final_aggregated_trades' # 最终聚合好的特征存放目录

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
WEEKS_TO_PROCESS = ['week1', 'week2']

# ==========================================
# 2. 核心聚合函数 (完美平替你之前的 dict 逻辑)
# ==========================================
def aggregate_trades_to_second(df_raw, slug):
    if df_raw.empty:
        return pd.DataFrame()

    # 1. 把时间向下取整到秒 (例如 10:00:01.345 -> 10:00:01)
    df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
    
    # 2. 计算每笔交易的名义价值 (price * size)
    df_raw['notional'] = df_raw['price'] * df_raw['size']
    df_raw['slug'] = slug  # 补充 slug 列
    
    key_cols = ["slug", "market", "asset_id", "timestamp"]
    
    # 3. 分离 BUY 和 SELL
    buy_df = df_raw[df_raw['side'] == 'BUY']
    sell_df = df_raw[df_raw['side'] == 'SELL']
    
    # 4. 分别对 BUY 进行秒级聚合
    buy_agg = pd.DataFrame()
    if not buy_df.empty:
        buy_agg = buy_df.groupby(key_cols).agg(
            buy_trade_size=('size', 'sum'),
            buy_trade_count=('transaction_hash', 'count'),
            taker_buy_trade_nominal_value=('notional', 'sum')
        )
        buy_agg['buy_trade_vwap'] = buy_agg['taker_buy_trade_nominal_value'] / buy_agg['buy_trade_size']
    
    # 5. 分别对 SELL 进行秒级聚合
    sell_agg = pd.DataFrame()
    if not sell_df.empty:
        sell_agg = sell_df.groupby(key_cols).agg(
            sell_trade_size=('size', 'sum'),
            sell_trade_count=('transaction_hash', 'count'),
            taker_sell_trade_nominal_value=('notional', 'sum')
        )
        sell_agg['sell_trade_vwap'] = sell_agg['taker_sell_trade_nominal_value'] / sell_agg['sell_trade_size']
    
    # 6. 把 BUY 和 SELL 合并在一起 (how='outer' 保证单边有交易的秒数也不丢失)
    if buy_agg.empty and sell_agg.empty:
        return pd.DataFrame()
    elif buy_agg.empty:
        result = sell_agg.reset_index()
    elif sell_agg.empty:
        result = buy_agg.reset_index()
    else:
        result = buy_agg.join(sell_agg, how='outer').reset_index()
    
    # 7. 处理缺失值：交易量和次数空缺填 0，VWAP 保持 NaN
    fill_zero_cols = [c for c in ['buy_trade_size', 'buy_trade_count', 'taker_buy_trade_nominal_value', 
                                  'sell_trade_size', 'sell_trade_count', 'taker_sell_trade_nominal_value'] 
                      if c in result.columns]
    result[fill_zero_cols] = result[fill_zero_cols].fillna(0)
    
    # 按照时间排序
    return result.sort_values(key_cols).reset_index(drop=True)

# ==========================================
# 3. 批量处理所有提取好的 Parquet 文件
# ==========================================
for week in WEEKS_TO_PROCESS:
    print(f"\n{'='*50}")
    print(f"🚀 开始聚合 {week.upper()} 的交易特征")
    print(f"{'='*50}")
    
    WEEK_INPUT_DIR = INPUT_DIR / week
    WEEK_OUTPUT_DIR = OUTPUT_DIR / week
    WEEK_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # 获取该周所有的交易记录文件
    parquet_files = glob.glob(str(WEEK_INPUT_DIR / '*_raw_txs.parquet'))
    print(f"   [!] 找到 {len(parquet_files)} 个合约文件待聚合...")
    
    for file_path in parquet_files:
        slug = os.path.basename(file_path).replace('_raw_txs.parquet', '')
        
        # 读取第一步清洗好的纯交易数据
        df_raw = pd.read_parquet(file_path)
        
        # 执行聚合逻辑
        df_agg = aggregate_trades_to_second(df_raw, slug)
        
        # 保存最终的特征表
        if not df_agg.empty:
            out_file = WEEK_OUTPUT_DIR / f"{slug}_trade_features.parquet"
            df_agg.to_parquet(out_file)
            print(f"     [√] 聚合完成 -> {out_file.name} (输出行数: {len(df_agg)} 秒)")
        else:
            print(f"     [!] 跳过 {slug}：聚合后无有效数据")

print("\n🎉 恭喜！所有交易特征聚合完毕！")

==================================================
🚀 开始聚合 WEEK1 的交易特征
==================================================
   [!] 找到 627 个合约文件待聚合...
     [√] 聚合完成 -> btc-updown-15m-1765153800_trade_features.parquet (输出行数: 809 秒)
     [√] 聚合完成 -> btc-updown-15m-1764838800_trade_features.parquet (输出行数: 720 秒)
     [√] 聚合完成 -> btc-updown-15m-1764656100_trade_features.parquet (输出行数: 918 秒)
     [√] 聚合完成 -> btc-updown-15m-1765081800_trade_features.parquet (输出行数: 791 秒)
     [√] 聚合完成 -> btc-updown-15m-1764792900_trade_features.parquet (输出行数: 1174 秒)
     [√] 聚合完成 -> btc-updown-15m-1764834300_trade_features.parquet (输出行数: 877 秒)
     [√] 聚合完成 -> btc-updown-15m-1765107900_trade_features.parquet (输出行数: 911 秒)
     [√] 聚合完成 -> btc-updown-15m-1764567900_trade_features.parquet (输出行数: 467 秒)
     [√] 聚合完成 -> btc-updown-15m-1764745200_trade_features.parquet (输出行数: 844 秒)
     [√] 聚合完成 -> btc-updown-15m-1764603000_trade_features.parquet (输出行数: 1002 秒)
     [√] 聚合完成 -> btc-updown-15m-1765127700_trade_features.parquet (输出行数: 702 秒)
     [√] 聚合完成 -> btc-updown-15m-1765084500_trade_features.parquet (输出行数: 937 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764810000_trade_features.parquet (输出行数: 600 秒)
     [√] 聚合完成 -> btc-updown-15m-1764843300_trade_features.parquet (输出行数: 962 秒)
     [√] 聚合完成 -> btc-updown-15m-1764642600_trade_features.parquet (输出行数: 794 秒)
     [√] 聚合完成 -> btc-updown-15m-1764981900_trade_features.parquet (输出行数: 279 秒)
     [√] 聚合完成 -> btc-updown-15m-1765103400_trade_features.parquet (输出行数: 803 秒)
     [√] 聚合完成 -> btc-updown-15m-1764918000_trade_features.parquet (输出行数: 1096 秒)
     [√] 聚合完成 -> btc-updown-15m-1764627300_trade_features.parquet (输出行数: 886 秒)
     [√] 聚合完成 -> btc-updown-15m-1764869400_trade_features.parquet (输出行数: 1071 秒)
     [√] 聚合完成 -> btc-updown-15m-1764675000_trade_features.parquet (输出行数: 1083 秒)
     [√] 聚合完成 -> btc-updown-15m-1764882000_trade_features.parquet (输出行数: 1183 秒)
     [√] 聚合完成 -> btc-updown-15m-1765010700_trade_features.parquet (输出行数: 950 秒)
     [√] 聚合完成 -> btc-updown-15m-1764673200_trade_features.parquet (输出行数: 1024 秒)
     [√] 聚合完成 -> btc-updown-15m-1765156500_trade_features.parquet (输出行数: 841 秒)
     [√] 聚合完成 -> btc-updown-15m-1764751500_trade_features.parquet (输出行数: 1197 秒)
     [√] 聚合完成 -> btc-updown-15m-1764620100_trade_features.parquet (输出行数: 895 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764644400_trade_features.parquet (输出行数: 927 秒)
     [√] 聚合完成 -> btc-updown-15m-1765118700_trade_features.parquet (输出行数: 1466 秒)
     [√] 聚合完成 -> btc-updown-15m-1764845100_trade_features.parquet (输出行数: 1036 秒)
     [√] 聚合完成 -> btc-updown-15m-1764966600_trade_features.parquet (输出行数: 631 秒)
     [√] 聚合完成 -> btc-updown-15m-1764578700_trade_features.parquet (输出行数: 648 秒)
     [√] 聚合完成 -> btc-updown-15m-1765082700_trade_features.parquet (输出行数: 930 秒)
     [√] 聚合完成 -> btc-updown-15m-1764817200_trade_features.parquet (输出行数: 924 秒)
     [√] 聚合完成 -> btc-updown-15m-1764946800_trade_features.parquet (输出行数: 675 秒)
     [√] 聚合完成 -> btc-updown-15m-1765068300_trade_features.parquet (输出行数: 1068 秒)
     [√] 聚合完成 -> btc-updown-15m-1764815400_trade_features.parquet (输出行数: 960 秒)
     [√] 聚合完成 -> btc-updown-15m-1765018800_trade_features.parquet (输出行数: 1031 秒)
     [√] 聚合完成 -> btc-updown-15m-1764779400_trade_features.parquet (输出行数: 700 秒)
     [√] 聚合完成 -> btc-updown-15m-1764792000_trade_features.parquet (输出行数: 1230 秒)
     [√] 聚合完成 -> btc-updown-15m-1765038600_trade_features.parquet (输出行数: 1096 秒)
     [√] 聚合完成 -> btc-updown-15m-1764973800_trade_features.parquet (输出行数: 1160 秒)
     [√] 聚合完成 -> btc-updown-15m-1764784800_trade_features.parquet (输出行数: 764 秒)
     [√] 聚合完成 -> btc-updown-15m-1765107000_trade_features.parquet (输出行数: 630 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764623700_trade_features.parquet (输出行数: 451 秒)
     [√] 聚合完成 -> btc-updown-15m-1764567000_trade_features.parquet (输出行数: 468 秒)
     [√] 聚合完成 -> btc-updown-15m-1764646200_trade_features.parquet (输出行数: 869 秒)
     [√] 聚合完成 -> btc-updown-15m-1764671400_trade_features.parquet (输出行数: 758 秒)
     [√] 聚合完成 -> btc-updown-15m-1764603900_trade_features.parquet (输出行数: 671 秒)
     [√] 聚合完成 -> btc-updown-15m-1764753300_trade_features.parquet (输出行数: 1172 秒)
     [√] 聚合完成 -> btc-updown-15m-1765076400_trade_features.parquet (输出行数: 983 秒)
     [√] 聚合完成 -> btc-updown-15m-1764755100_trade_features.parquet (输出行数: 725 秒)
     [√] 聚合完成 -> btc-updown-15m-1765014300_trade_features.parquet (输出行数: 890 秒)
     [√] 聚合完成 -> btc-updown-15m-1764949500_trade_features.parquet (输出行数: 919 秒)
     [√] 聚合完成 -> btc-updown-15m-1764789300_trade_features.parquet (输出行数: 1075 秒)
     [√] 聚合完成 -> btc-updown-15m-1764625500_trade_features.parquet (输出行数: 959 秒)
     [√] 聚合完成 -> btc-updown-15m-1764596700_trade_features.parquet (输出行数: 1023 秒)
     [√] 聚合完成 -> btc-updown-15m-1764841500_trade_features.parquet (输出行数: 1296 秒)
     [√] 聚合完成 -> btc-updown-15m-1764927900_trade_features.parquet (输出行数: 441 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764681300_trade_features.parquet (输出行数: 625 秒)
     [√] 聚合完成 -> btc-updown-15m-1765086300_trade_features.parquet (输出行数: 851 秒)
     [√] 聚合完成 -> btc-updown-15m-1764813600_trade_features.parquet (输出行数: 600 秒)
     [√] 聚合完成 -> btc-updown-15m-1765027800_trade_features.parquet (输出行数: 1046 秒)
     [√] 聚合完成 -> btc-updown-15m-1764652500_trade_features.parquet (输出行数: 884 秒)
     [√] 聚合完成 -> btc-updown-15m-1765049400_trade_features.parquet (输出行数: 724 秒)
     [√] 聚合完成 -> btc-updown-15m-1764923400_trade_features.parquet (输出行数: 571 秒)
     [√] 聚合完成 -> btc-updown-15m-1764810900_trade_features.parquet (输出行数: 658 秒)
     [√] 聚合完成 -> btc-updown-15m-1764976500_trade_features.parquet (输出行数: 1089 秒)
     [√] 聚合完成 -> btc-updown-15m-1764830700_trade_features.parquet (输出行数: 1065 秒)
     [√] 聚合完成 -> btc-updown-15m-1764595800_trade_features.parquet (输出行数: 1124 秒)
     [√] 聚合完成 -> btc-updown-15m-1764918900_trade_features.parquet (输出行数: 900 秒)
     [√] 聚合完成 -> btc-updown-15m-1764741600_trade_features.parquet (输出行数: 1001 秒)
     [√] 聚合完成 -> btc-updown-15m-1764688500_trade_features.parquet (输出行数: 1257 秒)
     [√] 聚合完成 -> btc-updown-15m-1764938700_trade_features.parquet (输出行数: 1102 秒)
     [√] 聚合完成 -> btc-updown-15m-1764882900_trade_features.parquet (输出行数: 1048 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765146600_trade_features.parquet (输出行数: 892 秒)
     [√] 聚合完成 -> btc-updown-15m-1764675900_trade_features.parquet (输出行数: 980 秒)
     [√] 聚合完成 -> btc-updown-15m-1764566100_trade_features.parquet (输出行数: 934 秒)
     [√] 聚合完成 -> btc-updown-15m-1765106100_trade_features.parquet (输出行数: 889 秒)
     [√] 聚合完成 -> btc-updown-15m-1765041300_trade_features.parquet (输出行数: 830 秒)
     [√] 聚合完成 -> btc-updown-15m-1764670500_trade_features.parquet (输出行数: 879 秒)
     [√] 聚合完成 -> btc-updown-15m-1764814500_trade_features.parquet (输出行数: 878 秒)
     [√] 聚合完成 -> btc-updown-15m-1765149300_trade_features.parquet (输出行数: 759 秒)
     [√] 聚合完成 -> btc-updown-15m-1765080000_trade_features.parquet (输出行数: 972 秒)
     [√] 聚合完成 -> btc-updown-15m-1764972900_trade_features.parquet (输出行数: 531 秒)
     [√] 聚合完成 -> btc-updown-15m-1764778500_trade_features.parquet (输出行数: 995 秒)
     [√] 聚合完成 -> btc-updown-15m-1764590400_trade_features.parquet (输出行数: 943 秒)
     [√] 聚合完成 -> btc-updown-15m-1764597600_trade_features.parquet (输出行数: 1036 秒)
     [√] 聚合完成 -> btc-updown-15m-1764812700_trade_features.parquet (输出行数: 581 秒)
     [√] 聚合完成 -> btc-updown-15m-1765087200_trade_features.parquet (输出行数: 596 秒)
     [√] 聚合完成 -> btc-updown-15m-1765152000_trade_features.parquet (输出行数: 844 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765015200_trade_features.parquet (输出行数: 987 秒)
     [√] 聚合完成 -> btc-updown-15m-1764677700_trade_features.parquet (输出行数: 1110 秒)
     [√] 聚合完成 -> btc-updown-15m-1765144800_trade_features.parquet (输出行数: 591 秒)
     [√] 聚合完成 -> btc-updown-15m-1765164600_trade_features.parquet (输出行数: 637 秒)
     [√] 聚合完成 -> btc-updown-15m-1764657900_trade_features.parquet (输出行数: 939 秒)
     [√] 聚合完成 -> btc-updown-15m-1765022400_trade_features.parquet (输出行数: 1080 秒)
     [√] 聚合完成 -> btc-updown-15m-1764786600_trade_features.parquet (输出行数: 1117 秒)
     [√] 聚合完成 -> btc-updown-15m-1765048500_trade_features.parquet (输出行数: 1189 秒)
     [√] 聚合完成 -> btc-updown-15m-1764915300_trade_features.parquet (输出行数: 909 秒)
     [√] 聚合完成 -> btc-updown-15m-1765125000_trade_features.parquet (输出行数: 213 秒)
     [√] 聚合完成 -> btc-updown-15m-1765026900_trade_features.parquet (输出行数: 767 秒)
     [√] 聚合完成 -> btc-updown-15m-1764714600_trade_features.parquet (输出行数: 640 秒)
     [√] 聚合完成 -> btc-updown-15m-1764653400_trade_features.parquet (输出行数: 998 秒)
     [√] 聚合完成 -> btc-updown-15m-1764621900_trade_features.parquet (输出行数: 1106 秒)
     [√] 聚合完成 -> btc-updown-15m-1764771300_trade_features.parquet (输出行数: 928 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764987300_trade_features.parquet (输出行数: 1160 秒)
     [√] 聚合完成 -> btc-updown-15m-1764919800_trade_features.parquet (输出行数: 1028 秒)
     [√] 聚合完成 -> btc-updown-15m-1764883800_trade_features.parquet (输出行数: 1149 秒)
     [√] 聚合完成 -> btc-updown-15m-1764689400_trade_features.parquet (输出行数: 1157 秒)
     [√] 聚合完成 -> btc-updown-15m-1764740700_trade_features.parquet (输出行数: 832 秒)
     [√] 聚合完成 -> btc-updown-15m-1764607500_trade_features.parquet (输出行数: 703 秒)
     [√] 聚合完成 -> btc-updown-15m-1764939600_trade_features.parquet (输出行数: 1070 秒)
     [√] 聚合完成 -> btc-updown-15m-1765072800_trade_features.parquet (输出行数: 506 秒)
     [√] 聚合完成 -> btc-updown-15m-1764811800_trade_features.parquet (输出行数: 884 秒)
     [√] 聚合完成 -> btc-updown-15m-1765093500_trade_features.parquet (输出行数: 699 秒)
     [√] 聚合完成 -> btc-updown-15m-1765079100_trade_features.parquet (输出行数: 982 秒)
     [√] 聚合完成 -> btc-updown-15m-1764594900_trade_features.parquet (输出行数: 1280 秒)
     [√] 聚合完成 -> btc-updown-15m-1764977400_trade_features.parquet (输出行数: 1033 秒)
     [√] 聚合完成 -> btc-updown-15m-1764831600_trade_features.parquet (输出行数: 814 秒)
     [√] 聚合完成 -> btc-updown-15m-1764768600_trade_features.parquet (输出行数: 900 秒)
     [√] 聚合完成 -> btc-updown-15m-1764911700_trade_features.parquet (输出行数: 654 秒)
     [√] 聚合完成 -> btc-updown-15m-1764804600_trade_features.parquet (输出行数: 916 秒)
     [√] 聚合完成 -> btc-updown-15m-1764619200_trade_features.parquet (输出行数: 46 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764926100_trade_features.parquet (输出行数: 289 秒)
     [√] 聚合完成 -> btc-updown-15m-1764861300_trade_features.parquet (输出行数: 1504 秒)
     [√] 聚合完成 -> btc-updown-15m-1764748800_trade_features.parquet (输出行数: 489 秒)
     [√] 聚合完成 -> btc-updown-15m-1764660600_trade_features.parquet (输出行数: 768 秒)
     [√] 聚合完成 -> btc-updown-15m-1765152900_trade_features.parquet (输出行数: 1064 秒)
     [√] 聚合完成 -> btc-updown-15m-1764983700_trade_features.parquet (输出行数: 926 秒)
     [√] 聚合完成 -> btc-updown-15m-1764969300_trade_features.parquet (输出行数: 1090 秒)
     [√] 聚合完成 -> btc-updown-15m-1764640800_trade_features.parquet (输出行数: 990 秒)
     [√] 聚合完成 -> btc-updown-15m-1764657000_trade_features.parquet (输出行数: 628 秒)
     [√] 聚合完成 -> btc-updown-15m-1764985500_trade_features.parquet (输出行数: 869 秒)
     [√] 聚合完成 -> btc-updown-15m-1764744300_trade_features.parquet (输出行数: 1096 秒)
     [√] 聚合完成 -> btc-updown-15m-1764602100_trade_features.parquet (输出行数: 1062 秒)
     [√] 聚合完成 -> btc-updown-15m-1765097100_trade_features.parquet (输出行数: 793 秒)
     [√] 聚合完成 -> btc-updown-15m-1765080900_trade_features.parquet (输出行数: 763 秒)
     [√] 聚合完成 -> btc-updown-15m-1764964800_trade_features.parquet (输出行数: 1015 秒)
     [√] 聚合完成 -> btc-updown-15m-1764972000_trade_features.parquet (输出行数: 966 秒)
     [√] 聚合完成 -> btc-updown-15m-1764835200_trade_features.parquet (输出行数: 508 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764793800_trade_features.parquet (输出行数: 496 秒)
     [√] 聚合完成 -> btc-updown-15m-1765102500_trade_features.parquet (输出行数: 781 秒)
     [√] 聚合完成 -> btc-updown-15m-1764674100_trade_features.parquet (输出行数: 884 秒)
     [√] 聚合完成 -> btc-updown-15m-1764868500_trade_features.parquet (输出行数: 1173 秒)
     [√] 聚合完成 -> btc-updown-15m-1765085400_trade_features.parquet (输出行数: 657 秒)
     [√] 聚合完成 -> btc-updown-15m-1764594000_trade_features.parquet (输出行数: 611 秒)
     [√] 聚合完成 -> btc-updown-15m-1764579600_trade_features.parquet (输出行数: 877 秒)
     [√] 聚合完成 -> btc-updown-15m-1765119600_trade_features.parquet (输出行数: 731 秒)
     [√] 聚合完成 -> btc-updown-15m-1764592200_trade_features.parquet (输出行数: 998 秒)
     [√] 聚合完成 -> btc-updown-15m-1765069200_trade_features.parquet (输出行数: 703 秒)
     [√] 聚合完成 -> btc-updown-15m-1764816300_trade_features.parquet (输出行数: 986 秒)
     [√] 聚合完成 -> btc-updown-15m-1764898200_trade_features.parquet (输出行数: 945 秒)
     [√] 聚合完成 -> btc-updown-15m-1765083600_trade_features.parquet (输出行数: 722 秒)
     [√] 聚合完成 -> btc-updown-15m-1765133100_trade_features.parquet (输出行数: 1251 秒)
     [√] 聚合完成 -> btc-updown-15m-1765125900_trade_features.parquet (输出行数: 1108 秒)
     [√] 聚合完成 -> btc-updown-15m-1764672300_trade_features.parquet (输出行数: 742 秒)
     [√] 聚合完成 -> btc-updown-15m-1765011600_trade_features.parquet (输出行数: 725 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765157400_trade_features.parquet (输出行数: 716 秒)
     [√] 聚合完成 -> btc-updown-15m-1765026000_trade_features.parquet (输出行数: 929 秒)
     [√] 聚合完成 -> btc-updown-15m-1764621000_trade_features.parquet (输出行数: 1055 秒)
     [√] 聚合完成 -> btc-updown-15m-1765090800_trade_features.parquet (输出行数: 444 秒)
     [√] 聚合完成 -> btc-updown-15m-1764783900_trade_features.parquet (输出行数: 690 秒)
     [√] 聚合完成 -> btc-updown-15m-1764825300_trade_features.parquet (输出行数: 973 秒)
     [√] 聚合完成 -> btc-updown-15m-1764962100_trade_features.parquet (输出行数: 788 秒)
     [√] 聚合完成 -> btc-updown-15m-1764840600_trade_features.parquet (输出行数: 1084 秒)
     [√] 聚合完成 -> btc-updown-15m-1764711900_trade_features.parquet (输出行数: 745 秒)
     [√] 聚合完成 -> btc-updown-15m-1764624600_trade_features.parquet (输出行数: 738 秒)
     [√] 聚合完成 -> btc-updown-15m-1764995400_trade_features.parquet (输出行数: 1005 秒)
     [√] 聚合完成 -> btc-updown-15m-1765116900_trade_features.parquet (输出行数: 916 秒)
     [√] 聚合完成 -> btc-updown-15m-1764612000_trade_features.parquet (输出行数: 987 秒)
     [√] 聚合完成 -> btc-updown-15m-1765136700_trade_features.parquet (输出行数: 1248 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764604800_trade_features.parquet (输出行数: 891 秒)
     [√] 聚合完成 -> btc-updown-15m-1764754200_trade_features.parquet (输出行数: 1190 秒)
     [√] 聚合完成 -> btc-updown-15m-1764948600_trade_features.parquet (输出行数: 1053 秒)
     [√] 聚合完成 -> btc-updown-15m-1764731700_trade_features.parquet (输出行数: 980 秒)
     [√] 聚合完成 -> btc-updown-15m-1764993600_trade_features.parquet (输出行数: 812 秒)
     [√] 聚合完成 -> btc-updown-15m-1764647100_trade_features.parquet (输出行数: 1016 秒)
     [√] 聚合完成 -> btc-updown-15m-1764829800_trade_features.parquet (输出行数: 1034 秒)
     [√] 聚合完成 -> btc-updown-15m-1765039500_trade_features.parquet (输出行数: 676 秒)
     [√] 聚合完成 -> btc-updown-15m-1764871200_trade_features.parquet (输出行数: 1187 秒)
     [√] 聚合完成 -> btc-updown-15m-1764936000_trade_features.parquet (输出行数: 1221 秒)
     [√] 聚合完成 -> btc-updown-15m-1764609300_trade_features.parquet (输出行数: 762 秒)
     [√] 聚合完成 -> btc-updown-15m-1765135800_trade_features.parquet (输出行数: 1194 秒)
     [√] 聚合完成 -> btc-updown-15m-1765147500_trade_features.parquet (输出行数: 789 秒)
     [√] 聚合完成 -> btc-updown-15m-1765001700_trade_features.parquet (输出行数: 905 秒)
     [√] 聚合完成 -> btc-updown-15m-1764569700_trade_features.parquet (输出行数: 586 秒)
     [√] 聚合完成 -> btc-updown-15m-1764854100_trade_features.parquet (输出行数: 815 秒)
     [√] 聚合完成 -> btc-updown-15m-1764582300_trade_features.parquet (输出行数: 823 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765109700_trade_features.parquet (输出行数: 1139 秒)
     [√] 聚合完成 -> btc-updown-15m-1764695700_trade_features.parquet (输出行数: 519 秒)
     [√] 聚合完成 -> btc-updown-15m-1764888300_trade_features.parquet (输出行数: 222 秒)
     [√] 聚合完成 -> btc-updown-15m-1764801000_trade_features.parquet (输出行数: 898 秒)
     [√] 聚合完成 -> btc-updown-15m-1764852300_trade_features.parquet (输出行数: 1187 秒)
     [√] 聚合完成 -> btc-updown-15m-1764584100_trade_features.parquet (输出行数: 887 秒)
     [√] 聚合完成 -> btc-updown-15m-1764990900_trade_features.parquet (输出行数: 776 秒)
     [√] 聚合完成 -> btc-updown-15m-1765112400_trade_features.parquet (输出行数: 950 秒)
     [√] 聚合完成 -> btc-updown-15m-1764909000_trade_features.parquet (输出行数: 709 秒)
     [√] 聚合完成 -> btc-updown-15m-1764636300_trade_features.parquet (输出行数: 644 秒)
     [√] 聚合完成 -> btc-updown-15m-1764572400_trade_features.parquet (输出行数: 969 秒)
     [√] 聚合完成 -> btc-updown-15m-1765161900_trade_features.parquet (输出行数: 924 秒)
     [√] 聚合完成 -> btc-updown-15m-1764878400_trade_features.parquet (输出行数: 1289 秒)
     [√] 聚合完成 -> btc-updown-15m-1765062000_trade_features.parquet (输出行数: 961 秒)
     [√] 聚合完成 -> btc-updown-15m-1764958500_trade_features.parquet (输出行数: 801 秒)
     [√] 聚合完成 -> btc-updown-15m-1765005300_trade_features.parquet (输出行数: 938 秒)
     [√] 聚合完成 -> btc-updown-15m-1765142100_trade_features.parquet (输出行数: 600 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764634500_trade_features.parquet (输出行数: 1164 秒)
     [√] 聚合完成 -> btc-updown-15m-1764798300_trade_features.parquet (输出行数: 90 秒)
     [√] 聚合完成 -> btc-updown-15m-1764587700_trade_features.parquet (输出行数: 1164 秒)
     [√] 聚合完成 -> btc-updown-15m-1764850500_trade_features.parquet (输出行数: 975 秒)
     [√] 聚合完成 -> btc-updown-15m-1764936900_trade_features.parquet (输出行数: 1030 秒)
     [√] 聚合完成 -> btc-updown-15m-1764690300_trade_features.parquet (输出行数: 973 秒)
     [√] 聚合完成 -> btc-updown-15m-1765159200_trade_features.parquet (输出行数: 1343 秒)
     [√] 聚合完成 -> btc-updown-15m-1765009800_trade_features.parquet (输出行数: 830 秒)
     [√] 聚合完成 -> btc-updown-15m-1764783000_trade_features.parquet (输出行数: 686 秒)
     [√] 聚合完成 -> btc-updown-15m-1765029600_trade_features.parquet (输出行数: 1009 秒)
     [√] 聚合完成 -> btc-updown-15m-1764580500_trade_features.parquet (输出行数: 1182 秒)
     [√] 聚合完成 -> btc-updown-15m-1764857700_trade_features.parquet (输出行数: 1146 秒)
     [√] 聚合完成 -> btc-updown-15m-1764576000_trade_features.parquet (输出行数: 518 秒)
     [√] 聚合完成 -> btc-updown-15m-1764711000_trade_features.parquet (输出行数: 942 秒)
     [√] 聚合完成 -> btc-updown-15m-1765051200_trade_features.parquet (输出行数: 1211 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765116000_trade_features.parquet (输出行数: 1092 秒)
     [√] 聚合完成 -> btc-updown-15m-1764632700_trade_features.parquet (输出行数: 533 秒)
     [√] 聚合完成 -> btc-updown-15m-1765067400_trade_features.parquet (输出行数: 674 秒)
     [√] 聚合完成 -> btc-updown-15m-1764612900_trade_features.parquet (输出行数: 1154 秒)
     [√] 聚合完成 -> btc-updown-15m-1764896400_trade_features.parquet (输出行数: 820 秒)
     [√] 聚合完成 -> btc-updown-15m-1764951300_trade_features.parquet (输出行数: 1192 秒)
     [√] 聚合完成 -> btc-updown-15m-1764801900_trade_features.parquet (输出行数: 904 秒)
     [√] 聚合完成 -> btc-updown-15m-1764844200_trade_features.parquet (输出行数: 1179 秒)
     [√] 聚合完成 -> btc-updown-15m-1764821700_trade_features.parquet (输出行数: 988 秒)
     [√] 聚合完成 -> btc-updown-15m-1764967500_trade_features.parquet (输出行数: 1213 秒)
     [√] 聚合完成 -> btc-updown-15m-1764990000_trade_features.parquet (输出行数: 655 秒)
     [√] 聚合完成 -> btc-updown-15m-1764909900_trade_features.parquet (输出行数: 745 秒)
     [√] 聚合完成 -> btc-updown-15m-1765161000_trade_features.parquet (输出行数: 881 秒)
     [√] 聚合完成 -> btc-updown-15m-1764735300_trade_features.parquet (输出行数: 982 秒)
     [√] 聚合完成 -> btc-updown-15m-1765062900_trade_features.parquet (输出行数: 869 秒)
     [√] 聚合完成 -> btc-updown-15m-1764929700_trade_features.parquet (输出行数: 995 秒)
     [√] 聚合完成 -> btc-updown-15m-1764750600_trade_features.parquet (输出行数: 26 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764643500_trade_features.parquet (输出行数: 607 秒)
     [√] 聚合完成 -> btc-updown-15m-1764704700_trade_features.parquet (输出行数: 712 秒)
     [√] 聚合完成 -> btc-updown-15m-1765036800_trade_features.parquet (输出行数: 412 秒)
     [√] 聚合完成 -> btc-updown-15m-1764997200_trade_features.parquet (输出行数: 789 秒)
     [√] 聚合完成 -> btc-updown-15m-1764631800_trade_features.parquet (输出行数: 655 秒)
     [√] 聚合完成 -> btc-updown-15m-1765058400_trade_features.parquet (输出行数: 864 秒)
     [√] 聚合完成 -> btc-updown-15m-1764932400_trade_features.parquet (输出行数: 686 秒)
     [√] 聚合完成 -> btc-updown-15m-1764739800_trade_features.parquet (输出行数: 846 秒)
     [√] 聚合完成 -> btc-updown-15m-1764851400_trade_features.parquet (输出行数: 793 秒)
     [√] 聚合完成 -> btc-updown-15m-1764691200_trade_features.parquet (输出行数: 1391 秒)
     [√] 聚合完成 -> btc-updown-15m-1764937800_trade_features.parquet (输出行数: 1140 秒)
     [√] 聚合完成 -> btc-updown-15m-1764803700_trade_features.parquet (输出行数: 1064 秒)
     [√] 聚合完成 -> btc-updown-15m-1765096200_trade_features.parquet (输出行数: 738 秒)
     [√] 聚合完成 -> btc-updown-15m-1764959400_trade_features.parquet (输出行数: 806 秒)
     [√] 聚合完成 -> btc-updown-15m-1765143000_trade_features.parquet (输出行数: 759 秒)
     [√] 聚合完成 -> btc-updown-15m-1764799200_trade_features.parquet (输出行数: 1033 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764828000_trade_features.parquet (输出行数: 1066 秒)
     [√] 聚合完成 -> btc-updown-15m-1764717300_trade_features.parquet (输出行数: 658 秒)
     [√] 聚合完成 -> btc-updown-15m-1764635400_trade_features.parquet (输出行数: 1098 秒)
     [√] 聚合完成 -> btc-updown-15m-1764984600_trade_features.parquet (输出行数: 546 秒)
     [√] 聚合完成 -> btc-updown-15m-1764633600_trade_features.parquet (输出行数: 853 秒)
     [√] 聚合完成 -> btc-updown-15m-1765050300_trade_features.parquet (输出行数: 1147 秒)
     [√] 聚合完成 -> btc-updown-15m-1764710100_trade_features.parquet (输出行数: 1008 秒)
     [√] 聚合完成 -> btc-updown-15m-1764661500_trade_features.parquet (输出行数: 1086 秒)
     [√] 聚合完成 -> btc-updown-15m-1765066500_trade_features.parquet (输出行数: 773 秒)
     [√] 聚合完成 -> btc-updown-15m-1764613800_trade_features.parquet (输出行数: 333 秒)
     [√] 聚合完成 -> btc-updown-15m-1765158300_trade_features.parquet (输出行数: 815 秒)
     [√] 聚合完成 -> btc-updown-15m-1764805500_trade_features.parquet (输出行数: 923 秒)
     [√] 聚合完成 -> btc-updown-15m-1764769500_trade_features.parquet (输出行数: 1175 秒)
     [√] 聚合完成 -> btc-updown-15m-1764581400_trade_features.parquet (输出行数: 921 秒)
     [√] 聚合完成 -> btc-updown-15m-1764963900_trade_features.parquet (输出行数: 903 秒)
     [√] 聚合完成 -> btc-updown-15m-1765028700_trade_features.parquet (输出行数: 765 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764782100_trade_features.parquet (输出行数: 1072 秒)
     [√] 聚合完成 -> btc-updown-15m-1765160100_trade_features.parquet (输出行数: 918 秒)
     [√] 聚合完成 -> btc-updown-15m-1765063800_trade_features.parquet (输出行数: 909 秒)
     [√] 聚合完成 -> btc-updown-15m-1765132200_trade_features.parquet (输出行数: 996 秒)
     [√] 聚合完成 -> btc-updown-15m-1764892800_trade_features.parquet (输出行数: 733 秒)
     [√] 聚合完成 -> btc-updown-15m-1764899100_trade_features.parquet (输出行数: 851 秒)
     [√] 聚合完成 -> btc-updown-15m-1764659700_trade_features.parquet (输出行数: 1059 秒)
     [√] 聚合完成 -> btc-updown-15m-1764585900_trade_features.parquet (输出行数: 1125 秒)
     [√] 聚合完成 -> btc-updown-15m-1764593100_trade_features.parquet (输出行数: 1406 秒)
     [√] 聚合完成 -> btc-updown-15m-1764855900_trade_features.parquet (输出行数: 863 秒)
     [√] 聚合完成 -> btc-updown-15m-1764738900_trade_features.parquet (输出行数: 1057 秒)
     [√] 聚合完成 -> btc-updown-15m-1764875700_trade_features.parquet (输出行数: 1465 秒)
     [√] 聚合完成 -> btc-updown-15m-1765134000_trade_features.parquet (输出行数: 1004 秒)
     [√] 聚合完成 -> btc-updown-15m-1764630900_trade_features.parquet (输出行数: 485 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764996300_trade_features.parquet (输出行数: 783 秒)
     [√] 聚合完成 -> btc-updown-15m-1764705600_trade_features.parquet (输出行数: 768 秒)
     [√] 聚合完成 -> btc-updown-15m-1765167300_trade_features.parquet (输出行数: 932 秒)
     [√] 聚合完成 -> btc-updown-15m-1764994500_trade_features.parquet (输出行数: 1111 秒)
     [√] 聚合完成 -> btc-updown-15m-1765117800_trade_features.parquet (输出行数: 1064 秒)
     [√] 聚合完成 -> btc-updown-15m-1765165500_trade_features.parquet (输出行数: 1003 秒)
     [√] 聚合完成 -> btc-updown-15m-1765137600_trade_features.parquet (输出行数: 987 秒)
     [√] 聚合完成 -> btc-updown-15m-1765008000_trade_features.parquet (输出行数: 479 秒)
     [√] 聚合完成 -> btc-updown-15m-1764963000_trade_features.parquet (输出行数: 1169 秒)
     [√] 聚合完成 -> btc-updown-15m-1764870300_trade_features.parquet (输出行数: 797 秒)
     [√] 聚合完成 -> btc-updown-15m-1765130400_trade_features.parquet (输出行数: 658 秒)
     [√] 聚合完成 -> btc-updown-15m-1765143900_trade_features.parquet (输出行数: 600 秒)
     [√] 聚合完成 -> btc-updown-15m-1764828900_trade_features.parquet (输出行数: 956 秒)
     [√] 聚合完成 -> btc-updown-15m-1764978300_trade_features.parquet (输出行数: 684 秒)
     [√] 聚合完成 -> btc-updown-15m-1765163700_trade_features.parquet (输出行数: 679 秒)
     [√] 聚合完成 -> btc-updown-15m-1764992700_trade_features.parquet (输出行数: 1003 秒)
     [√] 聚合完成 -> btc-updown-15m-1764855000_trade_features.parquet (输出行数: 1376 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764583200_trade_features.parquet (输出行数: 1045 秒)
     [√] 聚合完成 -> btc-updown-15m-1764807300_trade_features.parquet (输出行数: 980 秒)
     [√] 聚合完成 -> btc-updown-15m-1764738000_trade_features.parquet (输出行数: 1057 秒)
     [√] 聚合完成 -> btc-updown-15m-1764889200_trade_features.parquet (输出行数: 1128 秒)
     [√] 聚合完成 -> btc-updown-15m-1765092600_trade_features.parquet (输出行数: 596 秒)
     [√] 聚合完成 -> btc-updown-15m-1765078200_trade_features.parquet (输出行数: 609 秒)
     [√] 聚合完成 -> btc-updown-15m-1765134900_trade_features.parquet (输出行数: 726 秒)
     [√] 聚合完成 -> btc-updown-15m-1764606600_trade_features.parquet (输出行数: 803 秒)
     [√] 聚合完成 -> btc-updown-15m-1764630000_trade_features.parquet (输出行数: 762 秒)
     [√] 聚合完成 -> btc-updown-15m-1764713700_trade_features.parquet (输出行数: 693 秒)
     [√] 聚合完成 -> btc-updown-15m-1764715500_trade_features.parquet (输出行数: 652 秒)
     [√] 聚合完成 -> btc-updown-15m-1764637200_trade_features.parquet (输出行数: 750 秒)
     [√] 聚合完成 -> btc-updown-15m-1764908100_trade_features.parquet (输出行数: 843 秒)
     [√] 聚合完成 -> btc-updown-15m-1764991800_trade_features.parquet (输出行数: 653 秒)
     [√] 聚合完成 -> btc-updown-15m-1764766800_trade_features.parquet (输出行数: 1277 秒)
     [√] 聚合完成 -> btc-updown-15m-1765055700_trade_features.parquet (输出行数: 1054 秒)
     [√] 聚合完成 -> btc-updown-15m-1764665100_trade_features.parquet (输出行数: 859 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764800100_trade_features.parquet (输出行数: 751 秒)
     [√] 聚合完成 -> btc-updown-15m-1765094400_trade_features.parquet (输出行数: 412 秒)
     [√] 聚合完成 -> btc-updown-15m-1764787500_trade_features.parquet (输出行数: 491 秒)
     [√] 聚合完成 -> btc-updown-15m-1764853200_trade_features.parquet (输出行数: 805 秒)
     [√] 聚合完成 -> btc-updown-15m-1764585000_trade_features.parquet (输出行数: 1113 秒)
     [√] 聚合完成 -> btc-updown-15m-1764941400_trade_features.parquet (输出行数: 1038 秒)
     [√] 聚合完成 -> btc-updown-15m-1764781200_trade_features.parquet (输出行数: 971 秒)
     [√] 聚合完成 -> btc-updown-15m-1765114200_trade_features.parquet (输出行数: 1217 秒)
     [√] 聚合完成 -> btc-updown-15m-1765053000_trade_features.parquet (输出行数: 899 秒)
     [√] 聚合完成 -> btc-updown-15m-1765045800_trade_features.parquet (输出行数: 748 秒)
     [√] 聚合完成 -> btc-updown-15m-1764776700_trade_features.parquet (输出行数: 1354 秒)
     [√] 聚合完成 -> btc-updown-15m-1764574200_trade_features.parquet (输出行数: 836 秒)
     [√] 聚合完成 -> btc-updown-15m-1764894600_trade_features.parquet (输出行数: 1039 秒)
     [√] 聚合完成 -> btc-updown-15m-1764725400_trade_features.parquet (输出行数: 963 秒)
     [√] 聚合完成 -> btc-updown-15m-1764756900_trade_features.parquet (输出行数: 826 秒)
     [√] 聚合完成 -> btc-updown-15m-1765065600_trade_features.parquet (输出行数: 1063 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765140300_trade_features.parquet (输出行数: 861 秒)
     [√] 聚合完成 -> btc-updown-15m-1764723600_trade_features.parquet (输出行数: 986 秒)
     [√] 聚合完成 -> btc-updown-15m-1765007100_trade_features.parquet (输出行数: 1054 秒)
     [√] 聚合完成 -> btc-updown-15m-1764703800_trade_features.parquet (输出行数: 693 秒)
     [√] 聚合完成 -> btc-updown-15m-1764599400_trade_features.parquet (输出行数: 1282 秒)
     [√] 聚合完成 -> btc-updown-15m-1764692100_trade_features.parquet (输出行数: 663 秒)
     [√] 聚合完成 -> btc-updown-15m-1764873900_trade_features.parquet (输出行数: 1369 秒)
     [√] 聚合完成 -> btc-updown-15m-1764684900_trade_features.parquet (输出行数: 987 秒)
     [√] 聚合完成 -> btc-updown-15m-1764679500_trade_features.parquet (输出行数: 1062 秒)
     [√] 聚合完成 -> btc-updown-15m-1764881100_trade_features.parquet (输出行数: 1051 秒)
     [√] 聚合完成 -> btc-updown-15m-1765070100_trade_features.parquet (输出行数: 831 秒)
     [√] 聚合完成 -> btc-updown-15m-1764982800_trade_features.parquet (输出行数: 957 秒)
     [√] 聚合完成 -> btc-updown-15m-1765046700_trade_features.parquet (输出行数: 1064 秒)
     [√] 聚合完成 -> btc-updown-15m-1764775800_trade_features.parquet (输出行数: 1358 秒)
     [√] 聚合完成 -> btc-updown-15m-1764706500_trade_features.parquet (输出行数: 695 秒)
     [√] 聚合完成 -> btc-updown-15m-1764788400_trade_features.parquet (输出行数: 998 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764641700_trade_features.parquet (输出行数: 515 秒)
     [√] 聚合完成 -> btc-updown-15m-1764910800_trade_features.parquet (输出行数: 730 秒)
     [√] 聚合完成 -> btc-updown-15m-1764989100_trade_features.parquet (输出行数: 828 秒)
     [√] 聚合完成 -> btc-updown-15m-1764680400_trade_features.parquet (输出行数: 1172 秒)
     [√] 聚合完成 -> btc-updown-15m-1764930600_trade_features.parquet (输出行数: 1082 秒)
     [√] 聚合完成 -> btc-updown-15m-1764687600_trade_features.parquet (输出行数: 714 秒)
     [√] 聚合完成 -> btc-updown-15m-1764945900_trade_features.parquet (输出行数: 1109 秒)
     [√] 聚合完成 -> btc-updown-15m-1764953100_trade_features.parquet (输出行数: 979 秒)
     [√] 聚合完成 -> btc-updown-15m-1764823500_trade_features.parquet (输出行数: 882 秒)
     [√] 聚合完成 -> btc-updown-15m-1764965700_trade_features.parquet (输出行数: 1109 秒)
     [√] 聚合完成 -> btc-updown-15m-1764846000_trade_features.parquet (输出行数: 1275 秒)
     [√] 聚合完成 -> btc-updown-15m-1765077300_trade_features.parquet (输出行数: 836 秒)
     [√] 聚合完成 -> btc-updown-15m-1764752400_trade_features.parquet (输出行数: 1255 秒)
     [√] 聚合完成 -> btc-updown-15m-1764737100_trade_features.parquet (输出行数: 823 秒)
     [√] 聚合完成 -> btc-updown-15m-1764808200_trade_features.parquet (输出行数: 792 秒)
     [√] 聚合完成 -> btc-updown-15m-1764720900_trade_features.parquet (输出行数: 864 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765075500_trade_features.parquet (输出行数: 507 秒)
     [√] 聚合完成 -> btc-updown-15m-1765089900_trade_features.parquet (输出行数: 120 秒)
     [√] 聚合完成 -> btc-updown-15m-1764645300_trade_features.parquet (输出行数: 512 秒)
     [√] 聚合完成 -> btc-updown-15m-1764791100_trade_features.parquet (输出行数: 710 秒)
     [√] 聚合完成 -> btc-updown-15m-1764865800_trade_features.parquet (输出行数: 1046 秒)
     [√] 聚合完成 -> btc-updown-15m-1764684000_trade_features.parquet (输出行数: 824 秒)
     [√] 聚合完成 -> btc-updown-15m-1764934200_trade_features.parquet (输出行数: 673 秒)
     [√] 聚合完成 -> btc-updown-15m-1764873000_trade_features.parquet (输出行数: 987 秒)
     [√] 聚合完成 -> btc-updown-15m-1764669600_trade_features.parquet (输出行数: 689 秒)
     [√] 聚合完成 -> btc-updown-15m-1764682200_trade_features.parquet (输出行数: 877 秒)
     [√] 聚合完成 -> btc-updown-15m-1764842400_trade_features.parquet (输出行数: 1221 秒)
     [√] 聚合完成 -> btc-updown-15m-1764960300_trade_features.parquet (输出行数: 1130 秒)
     [√] 聚合完成 -> btc-updown-15m-1764718200_trade_features.parquet (输出行数: 437 秒)
     [√] 聚合完成 -> btc-updown-15m-1764827100_trade_features.parquet (输出行数: 1055 秒)
     [√] 聚合完成 -> btc-updown-15m-1764649800_trade_features.parquet (输出行数: 876 秒)
     [√] 聚合完成 -> btc-updown-15m-1764626400_trade_features.parquet (输出行数: 813 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765053900_trade_features.parquet (输出行数: 1281 秒)
     [√] 聚合完成 -> btc-updown-15m-1764733500_trade_features.parquet (输出行数: 979 秒)
     [√] 聚合完成 -> btc-updown-15m-1765073700_trade_features.parquet (输出行数: 500 秒)
     [√] 聚合完成 -> btc-updown-15m-1764610200_trade_features.parquet (输出行数: 1074 秒)
     [√] 聚合完成 -> btc-updown-15m-1764756000_trade_features.parquet (输出行数: 1062 秒)
     [√] 聚合完成 -> btc-updown-15m-1764866700_trade_features.parquet (输出行数: 1344 秒)
     [√] 聚合完成 -> btc-updown-15m-1764945000_trade_features.parquet (输出行数: 1326 秒)
     [√] 聚合完成 -> btc-updown-15m-1765168200_trade_features.parquet (输出行数: 1262 秒)
     [√] 聚合完成 -> btc-updown-15m-1764846900_trade_features.parquet (输出行数: 821 秒)
     [√] 聚合完成 -> btc-updown-15m-1764570600_trade_features.parquet (输出行数: 910 秒)
     [√] 聚合完成 -> btc-updown-15m-1765110600_trade_features.parquet (输出行数: 944 秒)
     [√] 聚合完成 -> btc-updown-15m-1765060200_trade_features.parquet (输出行数: 998 秒)
     [√] 聚合完成 -> btc-updown-15m-1764720000_trade_features.parquet (输出行数: 998 秒)
     [√] 聚合完成 -> btc-updown-15m-1765145700_trade_features.parquet (输出行数: 1201 秒)
     [√] 聚合完成 -> btc-updown-15m-1764676800_trade_features.parquet (输出行数: 900 秒)
     [√] 聚合完成 -> btc-updown-15m-1764727200_trade_features.parquet (输出行数: 907 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764818100_trade_features.parquet (输出行数: 762 秒)
     [√] 聚合完成 -> btc-updown-15m-1765003500_trade_features.parquet (输出行数: 1017 秒)
     [√] 聚合完成 -> btc-updown-15m-1764943200_trade_features.parquet (输出行数: 1208 秒)
     [√] 聚合完成 -> btc-updown-15m-1764864900_trade_features.parquet (输出行数: 1100 秒)
     [√] 聚合完成 -> btc-updown-15m-1764872100_trade_features.parquet (输出行数: 1086 秒)
     [√] 聚合完成 -> btc-updown-15m-1764693900_trade_features.parquet (输出行数: 884 秒)
     [√] 聚合完成 -> btc-updown-15m-1765042200_trade_features.parquet (输出行数: 531 秒)
     [√] 聚合完成 -> btc-updown-15m-1764858600_trade_features.parquet (输出行数: 1233 秒)
     [√] 聚合完成 -> btc-updown-15m-1764702000_trade_features.parquet (输出行数: 511 秒)
     [√] 聚合完成 -> btc-updown-15m-1765021500_trade_features.parquet (输出行数: 866 秒)
     [√] 聚合完成 -> btc-updown-15m-1764588600_trade_features.parquet (输出行数: 791 秒)
     [√] 聚合完成 -> btc-updown-15m-1765044000_trade_features.parquet (输出行数: 945 秒)
     [√] 聚合完成 -> btc-updown-15m-1765151100_trade_features.parquet (输出行数: 465 秒)
     [√] 聚合完成 -> btc-updown-15m-1765129500_trade_features.parquet (输出行数: 1288 秒)
     [√] 聚合完成 -> btc-updown-15m-1764668700_trade_features.parquet (输出行数: 1014 秒)
     [√] 聚合完成 -> btc-updown-15m-1764961200_trade_features.parquet (输出行数: 1094 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764648900_trade_features.parquet (输出行数: 950 秒)
     [√] 聚合完成 -> btc-updown-15m-1764772200_trade_features.parquet (输出行数: 1225 秒)
     [√] 聚合完成 -> btc-updown-15m-1764622800_trade_features.parquet (输出行数: 612 秒)
     [√] 聚合完成 -> btc-updown-15m-1765057500_trade_features.parquet (输出行数: 1078 秒)
     [√] 聚合完成 -> btc-updown-15m-1765019700_trade_features.parquet (输出行数: 627 秒)
     [√] 聚合完成 -> btc-updown-15m-1764944100_trade_features.parquet (输出行数: 1163 秒)
     [√] 聚合完成 -> btc-updown-15m-1764867600_trade_features.parquet (输出行数: 990 秒)
     [√] 聚合完成 -> btc-updown-15m-1764629100_trade_features.parquet (输出行数: 799 秒)
     [√] 聚合完成 -> btc-updown-15m-1764916200_trade_features.parquet (输出行数: 1079 秒)
     [√] 聚合完成 -> btc-updown-15m-1764847800_trade_features.parquet (输出行数: 870 秒)
     [√] 聚合完成 -> btc-updown-15m-1764785700_trade_features.parquet (输出行数: 490 秒)
     [√] 聚合完成 -> btc-updown-15m-1764860400_trade_features.parquet (输出行数: 641 秒)
     [√] 聚合完成 -> btc-updown-15m-1764942300_trade_features.parquet (输出行数: 1257 秒)
     [√] 聚合完成 -> btc-updown-15m-1765071900_trade_features.parquet (输出行数: 752 秒)
     [√] 聚合完成 -> btc-updown-15m-1764819000_trade_features.parquet (输出行数: 787 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764726300_trade_features.parquet (输出行数: 623 秒)
     [√] 聚合完成 -> btc-updown-15m-1764968400_trade_features.parquet (输出行数: 959 秒)
     [√] 聚合完成 -> btc-updown-15m-1764774000_trade_features.parquet (输出行数: 1129 秒)
     [√] 聚合完成 -> btc-updown-15m-1765052100_trade_features.parquet (输出行数: 989 秒)
     [√] 聚合完成 -> btc-updown-15m-1764777600_trade_features.parquet (输出行数: 751 秒)
     [√] 聚合完成 -> btc-updown-15m-1765044900_trade_features.parquet (输出行数: 1056 秒)
     [√] 聚合完成 -> btc-updown-15m-1765064700_trade_features.parquet (输出行数: 608 秒)
     [√] 聚合完成 -> btc-updown-15m-1764757800_trade_features.parquet (输出行数: 680 秒)
     [√] 聚合完成 -> btc-updown-15m-1764724500_trade_features.parquet (输出行数: 658 秒)
     [√] 聚合完成 -> btc-updown-15m-1764862200_trade_features.parquet (输出行数: 1087 秒)
     [√] 聚合完成 -> btc-updown-15m-1764940500_trade_features.parquet (输出行数: 922 秒)
     [√] 聚合完成 -> btc-updown-15m-1764648000_trade_features.parquet (输出行数: 851 秒)
     [√] 聚合完成 -> btc-updown-15m-1764780300_trade_features.parquet (输出行数: 716 秒)
     [√] 聚合完成 -> btc-updown-15m-1764912600_trade_features.parquet (输出行数: 934 秒)
     [√] 聚合完成 -> btc-updown-15m-1764914400_trade_features.parquet (输出行数: 706 秒)
     [√] 聚合完成 -> btc-updown-15m-1764971100_trade_features.parquet (输出行数: 909 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764947700_trade_features.parquet (输出行数: 1378 秒)
     [√] 聚合完成 -> btc-updown-15m-1764693000_trade_features.parquet (输出行数: 670 秒)
     [√] 聚合完成 -> btc-updown-15m-1764685800_trade_features.parquet (输出行数: 1439 秒)
     [√] 聚合完成 -> btc-updown-15m-1764864000_trade_features.parquet (输出行数: 1031 秒)
     [√] 聚合完成 -> btc-updown-15m-1764722700_trade_features.parquet (输出行数: 752 秒)
     [√] 聚合完成 -> btc-updown-15m-1765088100_trade_features.parquet (输出行数: 656 秒)
     [√] 聚合完成 -> btc-updown-15m-1765141200_trade_features.parquet (输出行数: 612 秒)
     [√] 聚合完成 -> btc-updown-15m-1764986400_trade_features.parquet (输出行数: 998 秒)
     [√] 聚合完成 -> btc-updown-15m-1764770400_trade_features.parquet (输出行数: 489 秒)
     [√] 聚合完成 -> btc-updown-15m-1764598500_trade_features.parquet (输出行数: 1186 秒)
     [√] 聚合完成 -> btc-updown-15m-1764702900_trade_features.parquet (输出行数: 1033 秒)
     [√] 聚合完成 -> btc-updown-15m-1764877500_trade_features.parquet (输出行数: 1440 秒)
     [√] 聚合完成 -> btc-updown-15m-1765071000_trade_features.parquet (输出行数: 736 秒)
     [√] 聚合完成 -> btc-updown-15m-1764819900_trade_features.parquet (输出行数: 988 秒)
     [√] 聚合完成 -> btc-updown-15m-1764707400_trade_features.parquet (输出行数: 1049 秒)
     [√] 聚合完成 -> btc-updown-15m-1765023300_trade_features.parquet (输出行数: 1001 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764839700_trade_features.parquet (输出行数: 1319 秒)
     [√] 聚合完成 -> btc-updown-15m-1764774900_trade_features.parquet (输出行数: 1385 秒)
     [√] 聚合完成 -> btc-updown-15m-1765047600_trade_features.parquet (输出行数: 860 秒)
     [√] 聚合完成 -> btc-updown-15m-1765040400_trade_features.parquet (输出行数: 1192 秒)
     [√] 聚合完成 -> btc-updown-15m-1765025100_trade_features.parquet (输出行数: 1055 秒)
     [√] 聚合完成 -> btc-updown-15m-1764721800_trade_features.parquet (输出行数: 893 秒)
     [√] 聚合完成 -> btc-updown-15m-1765126800_trade_features.parquet (输出行数: 1153 秒)
     [√] 聚合完成 -> btc-updown-15m-1765148400_trade_features.parquet (输出行数: 1206 秒)
     [√] 聚合完成 -> btc-updown-15m-1764686700_trade_features.parquet (输出行数: 1234 秒)
     [√] 聚合完成 -> btc-updown-15m-1764591300_trade_features.parquet (输出行数: 1226 秒)
     [√] 聚合完成 -> btc-updown-15m-1765098000_trade_features.parquet (输出行数: 913 秒)
     [√] 聚合完成 -> btc-updown-15m-1764732600_trade_features.parquet (输出行数: 758 秒)
     [√] 聚合完成 -> btc-updown-15m-1765016100_trade_features.parquet (输出行数: 839 秒)
     [√] 聚合完成 -> btc-updown-15m-1764611100_trade_features.parquet (输出行数: 1093 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764760500_trade_features.parquet (输出行数: 758 秒)
     [√] 聚合完成 -> btc-updown-15m-1764712800_trade_features.parquet (输出行数: 654 秒)
     [√] 聚合完成 -> btc-updown-15m-1765059300_trade_features.parquet (输出行数: 912 秒)
     [√] 聚合完成 -> btc-updown-15m-1764904500_trade_features.parquet (输出行数: 647 秒)
     [√] 聚合完成 -> btc-updown-15m-1764719100_trade_features.parquet (输出行数: 685 秒)
     [√] 聚合完成 -> btc-updown-15m-1764826200_trade_features.parquet (输出行数: 504 秒)
     [√] 聚合完成 -> btc-updown-15m-1764957600_trade_features.parquet (输出行数: 866 秒)
     [√] 聚合完成 -> btc-updown-15m-1764933300_trade_features.parquet (输出行数: 891 秒)
     [√] 聚合完成 -> btc-updown-15m-1764683100_trade_features.parquet (输出行数: 831 秒)
     [√] 聚合完成 -> btc-updown-15m-1764935100_trade_features.parquet (输出行数: 568 秒)
     [√] 聚合完成 -> btc-updown-15m-1764950400_trade_features.parquet (输出行数: 616 秒)
     [√] 聚合完成 -> btc-updown-15m-1764790200_trade_features.parquet (输出行数: 1182 秒)
     [√] 聚合完成 -> btc-updown-15m-1764902700_trade_features.parquet (输出行数: 51 秒)
     [√] 聚合完成 -> btc-updown-15m-1764565200_trade_features.parquet (输出行数: 1237 秒)
     [√] 聚合完成 -> btc-updown-15m-1765054800_trade_features.parquet (输出行数: 1188 秒)
     [√] 聚合完成 -> btc-updown-15m-1764767700_trade_features.parquet (输出行数: 979 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765105200_trade_features.parquet (输出行数: 1016 秒)
     [√] 聚合完成 -> btc-updown-15m-1764747900_trade_features.parquet (输出行数: 924 秒)
     [√] 聚合完成 -> btc-updown-15m-1765074600_trade_features.parquet (输出行数: 973 秒)
     [√] 聚合完成 -> btc-updown-15m-1764734400_trade_features.parquet (输出行数: 660 秒)
     [√] 聚合完成 -> btc-updown-15m-1764954900_trade_features.parquet (输出行数: 1187 秒)
     [√] 聚合完成 -> btc-updown-15m-1764696600_trade_features.parquet (输出行数: 46 秒)
     [√] 聚合完成 -> btc-updown-15m-1764639900_trade_features.parquet (输出行数: 842 秒)
     [√] 聚合完成 -> btc-updown-15m-1764974700_trade_features.parquet (输出行数: 980 秒)
     [√] 聚合完成 -> btc-updown-15m-1764832500_trade_features.parquet (输出行数: 1039 秒)
     [√] 聚合完成 -> btc-updown-15m-1765035000_trade_features.parquet (输出行数: 1016 秒)
     [√] 聚合完成 -> btc-updown-15m-1765002600_trade_features.parquet (输出行数: 780 秒)
     [√] 聚合完成 -> btc-updown-15m-1764897300_trade_features.parquet (输出行数: 701 秒)
     [√] 聚合完成 -> btc-updown-15m-1764743400_trade_features.parquet (输出行数: 722 秒)
     [√] 聚合完成 -> btc-updown-15m-1765061100_trade_features.parquet (输出行数: 1172 秒)
     [√] 聚合完成 -> btc-updown-15m-1765004400_trade_features.parquet (输出行数: 1214 秒)
     [√] 聚合完成 -> btc-updown-15m-1764890100_trade_features.parquet (输出行数: 876 秒)
     [√] 聚合完成 -> btc-updown-15m-1765162800_trade_features.parquet (输出行数: 927 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764571500_trade_features.parquet (输出行数: 1141 秒)
     [√] 聚合完成 -> btc-updown-15m-1765033200_trade_features.parquet (输出行数: 639 秒)
     [√] 聚合完成 -> btc-updown-15m-1764650700_trade_features.parquet (输出行数: 1005 秒)
     [√] 聚合完成 -> btc-updown-15m-1765111500_trade_features.parquet (输出行数: 513 秒)
     [√] 聚合完成 -> btc-updown-15m-1765169100_trade_features.parquet (输出行数: 1081 秒)
     [√] 聚合完成 -> btc-updown-15m-1764998100_trade_features.parquet (输出行数: 744 秒)
     [√] 聚合完成 -> btc-updown-15m-1764921600_trade_features.parquet (输出行数: 476 秒)
     [√] 聚合完成 -> btc-updown-15m-1764758700_trade_features.parquet (输出行数: 1177 秒)
     [√] 聚合完成 -> btc-updown-15m-1765139400_trade_features.parquet (输出行数: 976 秒)
     [√] 聚合完成 -> btc-updown-15m-1764678600_trade_features.parquet (输出行数: 1045 秒)
     [√] 聚合完成 -> btc-updown-15m-1764658800_trade_features.parquet (输出行数: 691 秒)
     [√] 聚合完成 -> btc-updown-15m-1764709200_trade_features.parquet (输出行数: 676 秒)
     [√] 聚合完成 -> btc-updown-15m-1765031400_trade_features.parquet (输出行数: 929 秒)
     [√] 聚合完成 -> btc-updown-15m-1764573300_trade_features.parquet (输出行数: 1033 秒)
     [√] 聚合完成 -> btc-updown-15m-1765113300_trade_features.parquet (输出行数: 844 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764747000_trade_features.parquet (输出行数: 1146 秒)
     [√] 聚合完成 -> btc-updown-15m-1764879300_trade_features.parquet (输出行数: 1314 秒)
     [√] 聚合完成 -> btc-updown-15m-1764601200_trade_features.parquet (输出行数: 1190 秒)
     [√] 聚合完成 -> btc-updown-15m-1765006200_trade_features.parquet (输出行数: 980 秒)
     [√] 聚合完成 -> btc-updown-15m-1764893700_trade_features.parquet (输出行数: 542 秒)
     [√] 聚合完成 -> btc-updown-15m-1764895500_trade_features.parquet (输出行数: 850 秒)
     [√] 聚合完成 -> btc-updown-15m-1765098900_trade_features.parquet (输出行数: 470 秒)
     [√] 聚合完成 -> btc-updown-15m-1764848700_trade_features.parquet (输出行数: 1193 秒)
     [√] 聚合完成 -> btc-updown-15m-1765115100_trade_features.parquet (输出行数: 979 秒)
     [√] 聚合完成 -> btc-updown-15m-1764575100_trade_features.parquet (输出行数: 1100 秒)
     [√] 聚合完成 -> btc-updown-15m-1764654300_trade_features.parquet (输出行数: 879 秒)
     [√] 聚合完成 -> btc-updown-15m-1764874800_trade_features.parquet (输出行数: 857 秒)
     [√] 聚合完成 -> btc-updown-15m-1764736200_trade_features.parquet (输出行数: 747 秒)
     [√] 聚合完成 -> btc-updown-15m-1764809100_trade_features.parquet (输出行数: 1154 秒)
     [√] 聚合完成 -> btc-updown-15m-1765012500_trade_features.parquet (输出行数: 901 秒)
     [√] 聚合完成 -> btc-updown-15m-1765154700_trade_features.parquet (输出行数: 1020 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764667800_trade_features.parquet (输出行数: 647 秒)
     [√] 聚合完成 -> btc-updown-15m-1764764100_trade_features.parquet (输出行数: 1099 秒)
     [√] 聚合完成 -> btc-updown-15m-1764822600_trade_features.parquet (输出行数: 1051 秒)
     [√] 聚合完成 -> btc-updown-15m-1764608400_trade_features.parquet (输出行数: 1086 秒)
     [√] 聚合完成 -> btc-updown-15m-1764802800_trade_features.parquet (输出行数: 1061 秒)
     [√] 聚合完成 -> btc-updown-15m-1764952200_trade_features.parquet (输出行数: 826 秒)
     [√] 聚合完成 -> btc-updown-15m-1764954000_trade_features.parquet (输出行数: 1245 秒)
     [√] 聚合完成 -> btc-updown-15m-1764931500_trade_features.parquet (输出行数: 717 秒)
     [√] 聚合完成 -> btc-updown-15m-1764988200_trade_features.parquet (输出行数: 1068 秒)
     [√] 聚合完成 -> btc-updown-15m-1764906300_trade_features.parquet (输出行数: 851 秒)
     [√] 聚合完成 -> btc-updown-15m-1764639000_trade_features.parquet (输出行数: 902 秒)
     [√] 聚合完成 -> btc-updown-15m-1764824400_trade_features.parquet (输出行数: 592 秒)
     [√] 聚合完成 -> btc-updown-15m-1765101600_trade_features.parquet (输出行数: 720 秒)
     [√] 聚合完成 -> btc-updown-15m-1764762300_trade_features.parquet (输出行数: 838 秒)
     [√] 聚合完成 -> btc-updown-15m-1765035900_trade_features.parquet (输出行数: 1017 秒)
     [√] 聚合完成 -> btc-updown-15m-1764880200_trade_features.parquet (输出行数: 974 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765030500_trade_features.parquet (输出行数: 810 秒)
     [√] 聚合完成 -> btc-updown-15m-1764746100_trade_features.parquet (输出行数: 890 秒)
     [√] 聚合完成 -> btc-updown-15m-1764600300_trade_features.parquet (输出行数: 1444 秒)
     [√] 聚合完成 -> btc-updown-15m-1764928800_trade_features.parquet (输出行数: 882 秒)
     [√] 聚合完成 -> btc-updown-15m-1765138500_trade_features.parquet (输出行数: 928 秒)
     [√] 聚合完成 -> btc-updown-15m-1764837000_trade_features.parquet (输出行数: 15 秒)
     [√] 聚合完成 -> btc-updown-15m-1764708300_trade_features.parquet (输出行数: 1156 秒)
     [√] 聚合完成 -> btc-updown-15m-1764820800_trade_features.parquet (输出行数: 859 秒)
     [√] 聚合完成 -> btc-updown-15m-1764970200_trade_features.parquet (输出行数: 721 秒)
     [√] 聚合完成 -> btc-updown-15m-1764913500_trade_features.parquet (输出行数: 582 秒)
     [√] 聚合完成 -> btc-updown-15m-1764863100_trade_features.parquet (输出行数: 1341 秒)
     [√] 聚合完成 -> btc-updown-15m-1764924300_trade_features.parquet (输出行数: 249 秒)
     [√] 聚合完成 -> btc-updown-15m-1764806400_trade_features.parquet (输出行数: 809 秒)
     [√] 聚合完成 -> btc-updown-15m-1764662400_trade_features.parquet (输出行数: 412 秒)
     [√] 聚合完成 -> btc-updown-15m-1765017900_trade_features.parquet (输出行数: 831 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765099800_trade_features.parquet (输出行数: 1025 秒)
     [√] 聚合完成 -> btc-updown-15m-1765037700_trade_features.parquet (输出行数: 1084 秒)
     [√] 聚合完成 -> btc-updown-15m-1764655200_trade_features.parquet (输出行数: 877 秒)
     [√] 聚合完成 -> btc-updown-15m-1764849600_trade_features.parquet (输出行数: 1296 秒)
     [√] 聚合完成 -> btc-updown-15m-1764999900_trade_features.parquet (输出行数: 833 秒)
     [√] 聚合完成 -> btc-updown-15m-1764586800_trade_features.parquet (输出行数: 552 秒)
     [√] 聚合完成 -> btc-updown-15m-1764891900_trade_features.parquet (输出行数: 1127 秒)
     [√] 聚合完成 -> btc-updown-15m-1765013400_trade_features.parquet (输出行数: 1122 秒)
     [√] 聚合完成 -> btc-updown-15m-1764666900_trade_features.parquet (输出行数: 851 秒)
     [√] 聚合完成 -> btc-updown-15m-1765155600_trade_features.parquet (输出行数: 703 秒)
     [√] 聚合完成 -> btc-updown-15m-1765131300_trade_features.parquet (输出行数: 979 秒)
     [√] 聚合完成 -> btc-updown-15m-1764765000_trade_features.parquet (输出行数: 1113 秒)
     [√] 聚合完成 -> btc-updown-15m-1765024200_trade_features.parquet (输出行数: 998 秒)
     [√] 聚合完成 -> btc-updown-15m-1764763200_trade_features.parquet (输出行数: 1007 秒)
     [√] 聚合完成 -> btc-updown-15m-1765100700_trade_features.parquet (输出行数: 775 秒)
     [√] 聚合完成 -> btc-updown-15m-1764876600_trade_features.parquet (输出行数: 609 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764856800_trade_features.parquet (输出行数: 1177 秒)
     [√] 聚合完成 -> btc-updown-15m-1764638100_trade_features.parquet (输出行数: 1125 秒)
     [√] 聚合完成 -> btc-updown-15m-1764907200_trade_features.parquet (输出行数: 680 秒)
     [√] 聚合完成 -> btc-updown-15m-1764568800_trade_features.parquet (输出行数: 807 秒)
     [√] 聚合完成 -> btc-updown-15m-1765108800_trade_features.parquet (输出行数: 870 秒)
     [√] 聚合完成 -> btc-updown-15m-1764905400_trade_features.parquet (输出行数: 1028 秒)
     [√] 聚合完成 -> btc-updown-15m-1764694800_trade_features.parquet (输出行数: 1033 秒)
     [√] 聚合完成 -> btc-updown-15m-1765128600_trade_features.parquet (输出行数: 1347 秒)
     [√] 聚合完成 -> btc-updown-15m-1764956700_trade_features.parquet (输出行数: 885 秒)
     [√] 聚合完成 -> btc-updown-15m-1765017000_trade_features.parquet (输出行数: 1005 秒)
     [√] 聚合完成 -> btc-updown-15m-1765000800_trade_features.parquet (输出行数: 928 秒)
     [√] 聚合完成 -> btc-updown-15m-1765150200_trade_features.parquet (输出行数: 937 秒)
     [√] 聚合完成 -> btc-updown-15m-1765166400_trade_features.parquet (输出行数: 1069 秒)
     [√] 聚合完成 -> btc-updown-15m-1765020600_trade_features.parquet (输出行数: 849 秒)
     [√] 聚合完成 -> btc-updown-15m-1764761400_trade_features.parquet (输出行数: 951 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764589500_trade_features.parquet (输出行数: 1033 秒)
     [√] 聚合完成 -> btc-updown-15m-1764859500_trade_features.parquet (输出行数: 832 秒)
     [√] 聚合完成 -> btc-updown-15m-1765043100_trade_features.parquet (输出行数: 998 秒)
     [√] 聚合完成 -> btc-updown-15m-1765104300_trade_features.parquet (输出行数: 1033 秒)
     [√] 聚合完成 -> btc-updown-15m-1764903600_trade_features.parquet (输出行数: 953 秒)
     [√] 聚合完成 -> btc-updown-15m-1764837900_trade_features.parquet (输出行数: 834 秒)
     [√] 聚合完成 -> btc-updown-15m-1765034100_trade_features.parquet (输出行数: 540 秒)
     [√] 聚合完成 -> btc-updown-15m-1764605700_trade_features.parquet (输出行数: 1055 秒)
     [√] 聚合完成 -> btc-updown-15m-1764742500_trade_features.parquet (输出行数: 740 秒)
     [√] 聚合完成 -> btc-updown-15m-1765091700_trade_features.parquet (输出行数: 833 秒)
     [√] 聚合完成 -> btc-updown-15m-1764955800_trade_features.parquet (输出行数: 1021 秒)
     [√] 聚合完成 -> btc-updown-15m-1764975600_trade_features.parquet (输出行数: 746 秒)
     [√] 聚合完成 -> btc-updown-15m-1764833400_trade_features.parquet (输出行数: 641 秒)
     [√] 聚合完成 -> btc-updown-15m-1764999000_trade_features.parquet (输出行数: 773 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1764628200_trade_features.parquet (输出行数: 755 秒)
     [√] 聚合完成 -> btc-updown-15m-1764917100_trade_features.parquet (输出行数: 785 秒)
     [√] 聚合完成 -> btc-updown-15m-1764920700_trade_features.parquet (输出行数: 922 秒)
     [√] 聚合完成 -> btc-updown-15m-1764759600_trade_features.parquet (输出行数: 891 秒)
     [√] 聚合完成 -> btc-updown-15m-1764666000_trade_features.parquet (输出行数: 604 秒)
     [√] 聚合完成 -> btc-updown-15m-1764891000_trade_features.parquet (输出行数: 961 秒)
     [√] 聚合完成 -> btc-updown-15m-1764765900_trade_features.parquet (输出行数: 1110 秒)
     [√] 聚合完成 -> btc-updown-15m-1765056600_trade_features.parquet (输出行数: 1071 秒)
     [√] 聚合完成 -> btc-updown-15m-1764773100_trade_features.parquet (输出行数: 716 秒)
     [√] 聚合完成 -> btc-updown-15m-1764651600_trade_features.parquet (输出行数: 879 秒)
     [√] 聚合完成 -> btc-updown-15m-1764716400_trade_features.parquet (输出行数: 755 秒)
     [√] 聚合完成 -> btc-updown-15m-1765032300_trade_features.parquet (输出行数: 1138 秒)

==================================================
🚀 开始聚合 WEEK2 的交易特征
==================================================
   [!] 找到 628 个合约文件待聚合...
     [√] 聚合完成 -> btc-updown-15m-1765512900_trade_features.parquet (输出行数: 356 秒)
     [√] 聚合完成 -> btc-updown-15m-1765763100_trade_features.parquet (输出行数: 1066 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765323000_trade_features.parquet (输出行数: 1179 秒)
     [√] 聚合完成 -> btc-updown-15m-1765641600_trade_features.parquet (输出行数: 731 秒)
     [√] 聚合完成 -> btc-updown-15m-1765706400_trade_features.parquet (输出行数: 984 秒)
     [√] 聚合完成 -> btc-updown-15m-1765173600_trade_features.parquet (输出行数: 1069 秒)
     [√] 聚合完成 -> btc-updown-15m-1765532700_trade_features.parquet (输出行数: 570 秒)
     [√] 聚合完成 -> btc-updown-15m-1765495800_trade_features.parquet (输出行数: 609 秒)
     [√] 聚合完成 -> btc-updown-15m-1765749600_trade_features.parquet (输出行数: 1022 秒)
     [√] 聚合完成 -> btc-updown-15m-1765185300_trade_features.parquet (输出行数: 1215 秒)
     [√] 聚合完成 -> btc-updown-15m-1765269900_trade_features.parquet (输出行数: 1160 秒)
     [√] 聚合完成 -> btc-updown-15m-1765338300_trade_features.parquet (输出行数: 1026 秒)
     [√] 聚合完成 -> btc-updown-15m-1765458000_trade_features.parquet (输出行数: 1372 秒)
     [√] 聚合完成 -> btc-updown-15m-1765590300_trade_features.parquet (输出行数: 583 秒)
     [√] 聚合完成 -> btc-updown-15m-1765189800_trade_features.parquet (输出行数: 1044 秒)
     [√] 聚合完成 -> btc-updown-15m-1765376100_trade_features.parquet (输出行数: 1373 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765534500_trade_features.parquet (输出行数: 706 秒)
     [√] 聚合完成 -> btc-updown-15m-1765230300_trade_features.parquet (输出行数: 958 秒)
     [√] 聚合完成 -> btc-updown-15m-1765175400_trade_features.parquet (输出行数: 775 秒)
     [√] 聚合完成 -> btc-updown-15m-1765254600_trade_features.parquet (输出行数: 539 秒)
     [√] 聚合完成 -> btc-updown-15m-1765720800_trade_features.parquet (输出行数: 1046 秒)
     [√] 聚合完成 -> btc-updown-15m-1765737000_trade_features.parquet (输出行数: 1034 秒)
     [√] 聚合完成 -> btc-updown-15m-1765170900_trade_features.parquet (输出行数: 507 秒)
     [√] 聚合完成 -> btc-updown-15m-1765543500_trade_features.parquet (输出行数: 542 秒)
     [√] 聚合完成 -> btc-updown-15m-1765364400_trade_features.parquet (输出行数: 1101 秒)
     [√] 聚合完成 -> btc-updown-15m-1765756800_trade_features.parquet (输出行数: 1402 秒)
     [√] 聚合完成 -> btc-updown-15m-1765689300_trade_features.parquet (输出行数: 806 秒)
     [√] 聚合完成 -> btc-updown-15m-1765531800_trade_features.parquet (输出行数: 892 秒)
     [√] 聚合完成 -> btc-updown-15m-1765215000_trade_features.parquet (输出行数: 1376 秒)
     [√] 聚合完成 -> btc-updown-15m-1765655100_trade_features.parquet (输出行数: 929 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765653300_trade_features.parquet (输出行数: 885 秒)
     [√] 聚合完成 -> btc-updown-15m-1765517400_trade_features.parquet (输出行数: 575 秒)
     [√] 聚合完成 -> btc-updown-15m-1765213200_trade_features.parquet (输出行数: 1311 秒)
     [√] 聚合完成 -> btc-updown-15m-1765342800_trade_features.parquet (输出行数: 1035 秒)
     [√] 聚合完成 -> btc-updown-15m-1765362600_trade_features.parquet (输出行数: 1089 秒)
     [√] 聚合完成 -> btc-updown-15m-1765467000_trade_features.parquet (输出行数: 835 秒)
     [√] 聚合完成 -> btc-updown-15m-1765241100_trade_features.parquet (输出行数: 1141 秒)
     [√] 聚合完成 -> btc-updown-15m-1765692000_trade_features.parquet (输出行数: 1140 秒)
     [√] 聚合完成 -> btc-updown-15m-1765684800_trade_features.parquet (输出行数: 1139 秒)
     [√] 聚合完成 -> btc-updown-15m-1765679400_trade_features.parquet (输出行数: 835 秒)
     [√] 聚合完成 -> btc-updown-15m-1765429200_trade_features.parquet (输出行数: 650 秒)
     [√] 聚合完成 -> btc-updown-15m-1765349100_trade_features.parquet (输出行数: 1273 秒)
     [√] 聚合完成 -> btc-updown-15m-1765269000_trade_features.parquet (输出行数: 1149 秒)
     [√] 聚合完成 -> btc-updown-15m-1765628100_trade_features.parquet (输出行数: 804 秒)
     [√] 聚合完成 -> btc-updown-15m-1765509300_trade_features.parquet (输出行数: 729 秒)
     [√] 聚合完成 -> btc-updown-15m-1765458900_trade_features.parquet (输出行数: 1277 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765759500_trade_features.parquet (输出行数: 1082 秒)
     [√] 聚合完成 -> btc-updown-15m-1765319400_trade_features.parquet (输出行数: 834 秒)
     [√] 聚合完成 -> btc-updown-15m-1765401300_trade_features.parquet (输出行数: 1010 秒)
     [√] 聚合完成 -> btc-updown-15m-1765737900_trade_features.parquet (输出行数: 921 秒)
     [√] 聚合完成 -> btc-updown-15m-1765547100_trade_features.parquet (输出行数: 1123 秒)
     [√] 聚合完成 -> btc-updown-15m-1765651500_trade_features.parquet (输出行数: 935 秒)
     [√] 聚合完成 -> btc-updown-15m-1765211400_trade_features.parquet (输出行数: 1457 秒)
     [√] 聚合完成 -> btc-updown-15m-1765504800_trade_features.parquet (输出行数: 889 秒)
     [√] 聚合完成 -> btc-updown-15m-1765298700_trade_features.parquet (输出行数: 60 秒)
     [√] 聚合完成 -> btc-updown-15m-1765323900_trade_features.parquet (输出行数: 818 秒)
     [√] 聚合完成 -> btc-updown-15m-1765366200_trade_features.parquet (输出行数: 842 秒)
     [√] 聚合完成 -> btc-updown-15m-1765524600_trade_features.parquet (输出行数: 407 秒)
     [√] 聚合完成 -> btc-updown-15m-1765463400_trade_features.parquet (输出行数: 1239 秒)
     [√] 聚合完成 -> btc-updown-15m-1765697400_trade_features.parquet (输出行数: 1154 秒)
     [√] 聚合完成 -> btc-updown-15m-1765645200_trade_features.parquet (输出行数: 792 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765467900_trade_features.parquet (输出行数: 445 秒)
     [√] 聚合完成 -> btc-updown-15m-1765536300_trade_features.parquet (输出行数: 591 秒)
     [√] 聚合完成 -> btc-updown-15m-1765177200_trade_features.parquet (输出行数: 1022 秒)
     [√] 聚合完成 -> btc-updown-15m-1765181700_trade_features.parquet (输出行数: 403 秒)
     [√] 聚合完成 -> btc-updown-15m-1765692900_trade_features.parquet (输出行数: 834 秒)
     [√] 聚合完成 -> btc-updown-15m-1765408500_trade_features.parquet (输出行数: 1022 秒)
     [√] 聚合完成 -> btc-updown-15m-1765595700_trade_features.parquet (输出行数: 485 秒)
     [√] 聚合完成 -> btc-updown-15m-1765439100_trade_features.parquet (输出行数: 1034 秒)
     [√] 聚合完成 -> btc-updown-15m-1765170000_trade_features.parquet (输出行数: 486 秒)
     [√] 聚合完成 -> btc-updown-15m-1765733400_trade_features.parquet (输出行数: 1411 秒)
     [√] 聚合完成 -> btc-updown-15m-1765372500_trade_features.parquet (输出行数: 1017 秒)
     [√] 聚合完成 -> btc-updown-15m-1765235700_trade_features.parquet (输出行数: 918 秒)
     [√] 聚合完成 -> btc-updown-15m-1765215900_trade_features.parquet (输出行数: 998 秒)
     [√] 聚合完成 -> btc-updown-15m-1765432800_trade_features.parquet (输出行数: 965 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765377900_trade_features.parquet (输出行数: 1298 秒)
     [√] 聚合完成 -> btc-updown-15m-1765188000_trade_features.parquet (输出行数: 1267 秒)
     [√] 聚合完成 -> btc-updown-15m-1765210500_trade_features.parquet (输出行数: 960 秒)
     [√] 聚合完成 -> btc-updown-15m-1765436400_trade_features.parquet (输出行数: 1098 秒)
     [√] 聚合完成 -> btc-updown-15m-1765629000_trade_features.parquet (输出行数: 907 秒)
     [√] 聚合完成 -> btc-updown-15m-1765282500_trade_features.parquet (输出行数: 602 秒)
     [√] 聚合完成 -> btc-updown-15m-1765459800_trade_features.parquet (输出行数: 1403 秒)
     [√] 聚合完成 -> btc-updown-15m-1765268100_trade_features.parquet (输出行数: 294 秒)
     [√] 聚合完成 -> btc-updown-15m-1765492200_trade_features.parquet (输出行数: 1005 秒)
     [√] 聚合完成 -> btc-updown-15m-1765318500_trade_features.parquet (输出行数: 1283 秒)
     [√] 聚合完成 -> btc-updown-15m-1765696500_trade_features.parquet (输出行数: 979 秒)
     [√] 聚合完成 -> btc-updown-15m-1765455300_trade_features.parquet (输出行数: 938 秒)
     [√] 聚合完成 -> btc-updown-15m-1765217700_trade_features.parquet (输出行数: 1121 秒)
     [√] 聚合完成 -> btc-updown-15m-1765462500_trade_features.parquet (输出行数: 1237 秒)
     [√] 聚合完成 -> btc-updown-15m-1765726200_trade_features.parquet (输出行数: 1287 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765409400_trade_features.parquet (输出行数: 1090 秒)
     [√] 聚合完成 -> btc-updown-15m-1765383300_trade_features.parquet (输出行数: 1125 秒)
     [√] 聚合完成 -> btc-updown-15m-1765693800_trade_features.parquet (输出行数: 943 秒)
     [√] 聚合完成 -> btc-updown-15m-1765204200_trade_features.parquet (输出行数: 1410 秒)
     [√] 聚合完成 -> btc-updown-15m-1765644300_trade_features.parquet (输出行数: 778 秒)
     [√] 聚合完成 -> btc-updown-15m-1765327500_trade_features.parquet (输出行数: 759 秒)
     [√] 聚合完成 -> btc-updown-15m-1765176300_trade_features.parquet (输出行数: 1207 秒)
     [√] 聚合完成 -> btc-updown-15m-1765311300_trade_features.parquet (输出行数: 870 秒)
     [√] 聚合完成 -> btc-updown-15m-1765537200_trade_features.parquet (输出行数: 654 秒)
     [√] 聚合完成 -> btc-updown-15m-1765530000_trade_features.parquet (输出行数: 810 秒)
     [√] 聚合完成 -> btc-updown-15m-1765373400_trade_features.parquet (输出行数: 1128 秒)
     [√] 聚合完成 -> btc-updown-15m-1765732500_trade_features.parquet (输出行数: 1197 秒)
     [√] 聚合完成 -> btc-updown-15m-1765506600_trade_features.parquet (输出行数: 1135 秒)
     [√] 聚合完成 -> btc-updown-15m-1765648800_trade_features.parquet (输出行数: 770 秒)
     [√] 聚合完成 -> btc-updown-15m-1765668600_trade_features.parquet (输出行数: 1093 秒)
     [√] 聚合完成 -> btc-updown-15m-1765385100_trade_features.parquet (输出行数: 1251 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765748700_trade_features.parquet (输出行数: 1096 秒)
     [√] 聚合完成 -> btc-updown-15m-1765308600_trade_features.parquet (输出行数: 1391 秒)
     [√] 聚合完成 -> btc-updown-15m-1765561500_trade_features.parquet (输出行数: 696 秒)
     [√] 聚合完成 -> btc-updown-15m-1765640700_trade_features.parquet (输出行数: 1056 秒)
     [√] 聚合完成 -> btc-updown-15m-1765322100_trade_features.parquet (输出行数: 820 秒)
     [√] 聚合完成 -> btc-updown-15m-1765200600_trade_features.parquet (输出行数: 1358 秒)
     [√] 聚合完成 -> btc-updown-15m-1765513800_trade_features.parquet (输出行数: 1102 秒)
     [√] 聚合完成 -> btc-updown-15m-1765346400_trade_features.parquet (输出行数: 1099 秒)
     [√] 聚合完成 -> btc-updown-15m-1765533600_trade_features.parquet (输出行数: 1007 秒)
     [√] 聚合完成 -> btc-updown-15m-1765172700_trade_features.parquet (输出行数: 1254 秒)
     [√] 聚合完成 -> btc-updown-15m-1765174500_trade_features.parquet (输出行数: 1048 秒)
     [√] 聚合完成 -> btc-updown-15m-1765736100_trade_features.parquet (输出行数: 1198 秒)
     [√] 聚合完成 -> btc-updown-15m-1765671300_trade_features.parquet (输出行数: 313 秒)
     [√] 聚合完成 -> btc-updown-15m-1765360800_trade_features.parquet (输出行数: 1385 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765377000_trade_features.parquet (输出行数: 1546 秒)
     [√] 聚合完成 -> btc-updown-15m-1765188900_trade_features.parquet (输出行数: 1307 秒)
     [√] 聚合完成 -> btc-updown-15m-1765231200_trade_features.parquet (输出行数: 754 秒)
     [√] 聚合完成 -> btc-updown-15m-1765535400_trade_features.parquet (输出行数: 873 秒)
     [√] 聚合完成 -> btc-updown-15m-1765591200_trade_features.parquet (输出行数: 532 秒)
     [√] 聚合完成 -> btc-updown-15m-1765629900_trade_features.parquet (输出行数: 941 秒)
     [√] 聚合完成 -> btc-updown-15m-1765339200_trade_features.parquet (输出行数: 1018 秒)
     [√] 聚合完成 -> btc-updown-15m-1765381500_trade_features.parquet (输出行数: 1159 秒)
     [√] 聚合完成 -> btc-updown-15m-1765686600_trade_features.parquet (输出行数: 905 秒)
     [√] 聚合完成 -> btc-updown-15m-1765530900_trade_features.parquet (输出行数: 742 秒)
     [√] 聚合完成 -> btc-updown-15m-1765171800_trade_features.parquet (输出行数: 1094 秒)
     [√] 聚合完成 -> btc-updown-15m-1765724400_trade_features.parquet (输出行数: 1119 秒)
     [√] 聚合完成 -> btc-updown-15m-1765214100_trade_features.parquet (输出行数: 1130 秒)
     [√] 聚合完成 -> btc-updown-15m-1765490400_trade_features.parquet (输出行数: 863 秒)
     [√] 聚合完成 -> btc-updown-15m-1765678500_trade_features.parquet (输出行数: 1113 秒)
     [√] 聚合完成 -> btc-updown-15m-1765238400_trade_features.parquet (输出行数: 921 秒)
     [√] 聚合完成 -> btc-updown-15m-1765709100_trade_features.parquet (输出行数: 1093 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765428300_trade_features.parquet (输出行数: 744 秒)
     [√] 聚合完成 -> btc-updown-15m-1765598400_trade_features.parquet (输出行数: 714 秒)
     [√] 聚合完成 -> btc-updown-15m-1765451700_trade_features.parquet (输出行数: 1108 秒)
     [√] 聚合完成 -> btc-updown-15m-1765212300_trade_features.parquet (输出行数: 666 秒)
     [√] 聚合完成 -> btc-updown-15m-1765516500_trade_features.parquet (输出行数: 1046 秒)
     [√] 聚合完成 -> btc-updown-15m-1765722600_trade_features.parquet (输出行数: 762 秒)
     [√] 聚合完成 -> btc-updown-15m-1765601100_trade_features.parquet (输出行数: 790 秒)
     [√] 聚合完成 -> btc-updown-15m-1765466100_trade_features.parquet (输出行数: 1054 秒)
     [√] 聚合完成 -> btc-updown-15m-1765639800_trade_features.parquet (输出行数: 1065 秒)
     [√] 聚合完成 -> btc-updown-15m-1765581300_trade_features.parquet (输出行数: 823 秒)
     [√] 聚合完成 -> btc-updown-15m-1765449000_trade_features.parquet (输出行数: 928 秒)
     [√] 聚合完成 -> btc-updown-15m-1765329300_trade_features.parquet (输出行数: 1154 秒)
     [√] 聚合完成 -> btc-updown-15m-1765278900_trade_features.parquet (输出行数: 1232 秒)
     [√] 聚合完成 -> btc-updown-15m-1765391400_trade_features.parquet (输出行数: 499 秒)
     [√] 聚合完成 -> btc-updown-15m-1765245600_trade_features.parquet (输出行数: 1080 秒)
     [√] 聚合完成 -> btc-updown-15m-1765604700_trade_features.parquet (输出行数: 686 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765525500_trade_features.parquet (输出行数: 444 秒)
     [√] 聚合完成 -> btc-updown-15m-1765221300_trade_features.parquet (输出行数: 1497 秒)
     [√] 聚合完成 -> btc-updown-15m-1765198800_trade_features.parquet (输出行数: 1108 秒)
     [√] 聚合完成 -> btc-updown-15m-1765367100_trade_features.parquet (输出行数: 1197 秒)
     [√] 聚合完成 -> btc-updown-15m-1765324800_trade_features.parquet (输出行数: 1167 秒)
     [√] 聚合完成 -> btc-updown-15m-1765332000_trade_features.parquet (输出行数: 570 秒)
     [√] 聚合完成 -> btc-updown-15m-1765650600_trade_features.parquet (输出行数: 964 秒)
     [√] 聚合完成 -> btc-updown-15m-1765571400_trade_features.parquet (输出行数: 1049 秒)
     [√] 聚合完成 -> btc-updown-15m-1765764900_trade_features.parquet (输出行数: 1017 秒)
     [√] 聚合完成 -> btc-updown-15m-1765635300_trade_features.parquet (输出行数: 666 秒)
     [√] 聚合完成 -> btc-updown-15m-1765503900_trade_features.parquet (输出行数: 343 秒)
     [√] 聚合完成 -> btc-updown-15m-1765772100_trade_features.parquet (输出行数: 926 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765523700_trade_features.parquet (输出行数: 300 秒)
     [√] 聚合完成 -> btc-updown-15m-1765546200_trade_features.parquet (输出行数: 1263 秒)
     [√] 聚合完成 -> btc-updown-15m-1765194300_trade_features.parquet (输出行数: 1231 秒)
     [√] 聚合完成 -> btc-updown-15m-1765758600_trade_features.parquet (输出行数: 803 秒)
     [√] 聚合完成 -> btc-updown-15m-1765760400_trade_features.parquet (输出行数: 1184 秒)
     [√] 聚合完成 -> btc-updown-15m-1765588500_trade_features.parquet (输出行数: 638 秒)
     [√] 聚合完成 -> btc-updown-15m-1765575900_trade_features.parquet (输出行数: 938 秒)
     [√] 聚合完成 -> btc-updown-15m-1765250100_trade_features.parquet (输出行数: 1401 秒)
     [√] 聚合完成 -> btc-updown-15m-1765476000_trade_features.parquet (输出行数: 690 秒)
     [√] 聚合完成 -> btc-updown-15m-1765611000_trade_features.parquet (输出行数: 774 秒)
     [√] 聚合完成 -> btc-updown-15m-1765480500_trade_features.parquet (输出行数: 394 秒)
     [√] 聚合完成 -> btc-updown-15m-1765683000_trade_features.parquet (输出行数: 1155 秒)
     [√] 聚合完成 -> btc-updown-15m-1765228500_trade_features.parquet (输出行数: 999 秒)
     [√] 聚合完成 -> btc-updown-15m-1765358100_trade_features.parquet (输出行数: 968 秒)
     [√] 聚合完成 -> btc-updown-15m-1765438200_trade_features.parquet (输出行数: 1148 秒)
     [√] 聚合完成 -> btc-updown-15m-1765719000_trade_features.parquet (输出行数: 1329 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765296000_trade_features.parquet (输出行数: 844 秒)
     [√] 聚合完成 -> btc-updown-15m-1765487700_trade_features.parquet (输出行数: 1022 秒)
     [√] 聚合完成 -> btc-updown-15m-1765395900_trade_features.parquet (输出行数: 1119 秒)
     [√] 聚合完成 -> btc-updown-15m-1765698300_trade_features.parquet (输出行数: 601 秒)
     [√] 聚合完成 -> btc-updown-15m-1765747800_trade_features.parquet (输出行数: 1226 秒)
     [√] 聚合完成 -> btc-updown-15m-1765552500_trade_features.parquet (输出行数: 1049 秒)
     [√] 聚合完成 -> btc-updown-15m-1765415700_trade_features.parquet (输出行数: 1445 秒)
     [√] 聚合完成 -> btc-updown-15m-1765257300_trade_features.parquet (输出行数: 1266 秒)
     [√] 聚合完成 -> btc-updown-15m-1765767600_trade_features.parquet (输出行数: 1308 秒)
     [√] 聚合完成 -> btc-updown-15m-1765332900_trade_features.parquet (输出行数: 611 秒)
     [√] 聚合完成 -> btc-updown-15m-1765289700_trade_features.parquet (输出行数: 854 秒)
     [√] 聚合完成 -> btc-updown-15m-1765764000_trade_features.parquet (输出行数: 608 秒)
     [√] 聚合完成 -> btc-updown-15m-1765472400_trade_features.parquet (输出行数: 356 秒)
     [√] 聚合完成 -> btc-updown-15m-1765255500_trade_features.parquet (输出行数: 1274 秒)
     [√] 聚合完成 -> btc-updown-15m-1765484100_trade_features.parquet (输出行数: 966 秒)
     [√] 聚合完成 -> btc-updown-15m-1765449900_trade_features.parquet (输出行数: 782 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765292400_trade_features.parquet (输出行数: 911 秒)
     [√] 聚合完成 -> btc-updown-15m-1765518300_trade_features.parquet (输出行数: 905 秒)
     [√] 聚合完成 -> btc-updown-15m-1765278000_trade_features.parquet (输出行数: 1371 秒)
     [√] 聚合完成 -> btc-updown-15m-1765482300_trade_features.parquet (输出行数: 943 秒)
     [√] 聚合完成 -> btc-updown-15m-1765469700_trade_features.parquet (输出行数: 881 秒)
     [√] 聚合完成 -> btc-updown-15m-1765556100_trade_features.parquet (输出行数: 1168 秒)
     [√] 聚合完成 -> btc-updown-15m-1765253700_trade_features.parquet (输出行数: 973 秒)
     [√] 聚合完成 -> btc-updown-15m-1765410300_trade_features.parquet (输出行数: 1464 秒)
     [√] 聚合完成 -> btc-updown-15m-1765762200_trade_features.parquet (输出行数: 788 秒)
     [√] 聚合完成 -> btc-updown-15m-1765426500_trade_features.parquet (输出行数: 1377 秒)
     [√] 聚合完成 -> btc-updown-15m-1765296900_trade_features.parquet (输出行数: 1580 秒)
     [√] 聚合完成 -> btc-updown-15m-1765348200_trade_features.parquet (输出行数: 961 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765395000_trade_features.parquet (输出行数: 1455 秒)
     [√] 聚合完成 -> btc-updown-15m-1765363500_trade_features.parquet (输出行数: 1120 秒)
     [√] 聚合完成 -> btc-updown-15m-1765520100_trade_features.parquet (输出行数: 1044 秒)
     [√] 聚合完成 -> btc-updown-15m-1765544400_trade_features.parquet (输出行数: 1096 秒)
     [√] 聚合完成 -> btc-updown-15m-1765240200_trade_features.parquet (输出行数: 680 秒)
     [√] 聚合完成 -> btc-updown-15m-1765423800_trade_features.parquet (输出行数: 1265 秒)
     [√] 聚合完成 -> btc-updown-15m-1765573200_trade_features.parquet (输出行数: 907 秒)
     [√] 聚合完成 -> btc-updown-15m-1765631700_trade_features.parquet (输出行数: 987 秒)
     [√] 聚合完成 -> btc-updown-15m-1765337400_trade_features.parquet (输出行数: 947 秒)
     [√] 聚合完成 -> btc-updown-15m-1765654200_trade_features.parquet (输出行数: 561 秒)
     [√] 聚合完成 -> btc-updown-15m-1765575000_trade_features.parquet (输出行数: 804 秒)
     [√] 聚合完成 -> btc-updown-15m-1765542600_trade_features.parquet (输出行数: 1166 秒)
     [√] 聚合完成 -> btc-updown-15m-1765611900_trade_features.parquet (输出行数: 797 秒)
     [√] 聚合完成 -> btc-updown-15m-1765527300_trade_features.parquet (输出行数: 202 秒)
     [√] 聚合完成 -> btc-updown-15m-1765476900_trade_features.parquet (输出行数: 212 秒)
     [√] 聚合完成 -> btc-updown-15m-1765393200_trade_features.parquet (输出行数: 1505 秒)
     [√] 聚合完成 -> btc-updown-15m-1765739700_trade_features.parquet (输出行数: 1003 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765190700_trade_features.parquet (输出行数: 1062 秒)
     [√] 聚合完成 -> btc-updown-15m-1765683900_trade_features.parquet (输出行数: 1047 秒)
     [√] 聚合完成 -> btc-updown-15m-1765719900_trade_features.parquet (输出行数: 910 秒)
     [√] 聚合完成 -> btc-updown-15m-1765380600_trade_features.parquet (输出行数: 1402 秒)
     [√] 聚合完成 -> btc-updown-15m-1765485000_trade_features.parquet (输出行数: 854 秒)
     [√] 聚合完成 -> btc-updown-15m-1765687500_trade_features.parquet (输出行数: 942 秒)
     [√] 聚合完成 -> btc-updown-15m-1765773900_trade_features.parquet (输出行数: 1292 秒)
     [√] 聚合完成 -> btc-updown-15m-1765502100_trade_features.parquet (输出行数: 292 秒)
     [√] 聚合完成 -> btc-updown-15m-1765333800_trade_features.parquet (输出行数: 807 秒)
     [√] 聚合完成 -> btc-updown-15m-1765666800_trade_features.parquet (输出行数: 954 秒)
     [√] 聚合完成 -> btc-updown-15m-1765540800_trade_features.parquet (输出行数: 675 秒)
     [√] 聚合完成 -> btc-updown-15m-1765557000_trade_features.parquet (输出行数: 597 秒)
     [√] 聚合完成 -> btc-updown-15m-1765411200_trade_features.parquet (输出行数: 1291 秒)
     [√] 聚合完成 -> btc-updown-15m-1765427400_trade_features.parquet (输出行数: 1177 秒)
     [√] 聚合完成 -> btc-updown-15m-1765201500_trade_features.parquet (输出行数: 1185 秒)
     [√] 聚合完成 -> btc-updown-15m-1765519200_trade_features.parquet (输出行数: 753 秒)
     [√] 聚合完成 -> btc-updown-15m-1765638000_trade_features.parquet (输出行数: 895 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765483200_trade_features.parquet (输出行数: 772 秒)
     [√] 聚合完成 -> btc-updown-15m-1765309500_trade_features.parquet (输出行数: 1140 秒)
     [√] 聚合完成 -> btc-updown-15m-1765723500_trade_features.parquet (输出行数: 1312 秒)
     [√] 聚合完成 -> btc-updown-15m-1765746000_trade_features.parquet (输出行数: 1213 秒)
     [√] 聚合完成 -> btc-updown-15m-1765521000_trade_features.parquet (输出行数: 920 秒)
     [√] 聚合完成 -> btc-updown-15m-1765600200_trade_features.parquet (输出行数: 768 秒)
     [√] 聚合完成 -> btc-updown-15m-1765572300_trade_features.parquet (输出行数: 1154 秒)
     [√] 聚合完成 -> btc-updown-15m-1765422900_trade_features.parquet (输出行数: 1196 秒)
     [√] 聚合完成 -> btc-updown-15m-1765297800_trade_features.parquet (输出行数: 747 秒)
     [√] 聚合完成 -> btc-updown-15m-1765708200_trade_features.parquet (输出行数: 934 秒)
     [√] 聚合完成 -> btc-updown-15m-1765394100_trade_features.parquet (输出行数: 1087 秒)
     [√] 聚合完成 -> btc-updown-15m-1765379700_trade_features.parquet (输出行数: 1164 秒)
     [√] 聚合完成 -> btc-updown-15m-1765191600_trade_features.parquet (输出行数: 1404 秒)
     [√] 聚合完成 -> btc-updown-15m-1765418400_trade_features.parquet (输出行数: 849 秒)
     [√] 聚合完成 -> btc-updown-15m-1765392300_trade_features.parquet (输出行数: 1359 秒)
     [√] 聚合完成 -> btc-updown-15m-1765359900_trade_features.parquet (输出行数: 719 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765271700_trade_features.parquet (输出行数: 888 秒)
     [√] 聚合完成 -> btc-updown-15m-1765336500_trade_features.parquet (输出行数: 772 秒)
     [√] 聚合完成 -> btc-updown-15m-1765574100_trade_features.parquet (输出行数: 756 秒)
     [√] 聚合完成 -> btc-updown-15m-1765251900_trade_features.parquet (输出行数: 1096 秒)
     [√] 聚合完成 -> btc-updown-15m-1765742400_trade_features.parquet (输出行数: 1357 秒)
     [√] 聚合完成 -> btc-updown-15m-1765605600_trade_features.parquet (输出行数: 876 秒)
     [√] 聚合完成 -> btc-updown-15m-1765727100_trade_features.parquet (输出行数: 1053 秒)
     [√] 聚合完成 -> btc-updown-15m-1765244700_trade_features.parquet (输出行数: 1500 秒)
     [√] 聚合完成 -> btc-updown-15m-1765577700_trade_features.parquet (输出行数: 1032 秒)
     [√] 聚合完成 -> btc-updown-15m-1765279800_trade_features.parquet (输出行数: 1269 秒)
     [√] 聚合完成 -> btc-updown-15m-1765638900_trade_features.parquet (输出行数: 1124 秒)
     [√] 聚合完成 -> btc-updown-15m-1765448100_trade_features.parquet (输出行数: 867 秒)
     [√] 聚合完成 -> btc-updown-15m-1765485900_trade_features.parquet (输出行数: 1024 秒)
     [√] 聚合完成 -> btc-updown-15m-1765397700_trade_features.parquet (输出行数: 989 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765493100_trade_features.parquet (输出行数: 17 秒)
     [√] 聚合完成 -> btc-updown-15m-1765195200_trade_features.parquet (输出行数: 909 秒)
     [√] 聚合完成 -> btc-updown-15m-1765765800_trade_features.parquet (输出行数: 1068 秒)
     [√] 聚合完成 -> btc-updown-15m-1765773000_trade_features.parquet (输出行数: 787 秒)
     [√] 聚合完成 -> btc-updown-15m-1765275300_trade_features.parquet (输出行数: 1215 秒)
     [√] 聚合完成 -> btc-updown-15m-1765570500_trade_features.parquet (输出行数: 1144 秒)
     [√] 聚合完成 -> btc-updown-15m-1765229400_trade_features.parquet (输出行数: 1056 秒)
     [√] 聚合完成 -> btc-updown-15m-1765682100_trade_features.parquet (输出行数: 1302 秒)
     [√] 聚合完成 -> btc-updown-15m-1765384200_trade_features.parquet (输出行数: 885 秒)
     [√] 聚合完成 -> btc-updown-15m-1765481400_trade_features.parquet (输出行数: 821 秒)
     [√] 聚合完成 -> btc-updown-15m-1765669500_trade_features.parquet (输出行数: 987 秒)
     [√] 聚合完成 -> btc-updown-15m-1765718100_trade_features.parquet (输出行数: 1315 秒)
     [√] 聚合完成 -> btc-updown-15m-1765359000_trade_features.parquet (输出行数: 866 秒)
     [√] 聚合完成 -> btc-updown-15m-1765589400_trade_features.parquet (输出行数: 413 秒)
     [√] 聚合完成 -> btc-updown-15m-1765203300_trade_features.parquet (输出行数: 844 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765507500_trade_features.parquet (输出行数: 834 秒)
     [√] 聚合完成 -> btc-updown-15m-1765610100_trade_features.parquet (输出行数: 874 秒)
     [√] 聚合完成 -> btc-updown-15m-1765251000_trade_features.parquet (输出行数: 604 秒)
     [√] 聚合完成 -> btc-updown-15m-1765553400_trade_features.parquet (输出行数: 1147 秒)
     [√] 聚合完成 -> btc-updown-15m-1765306800_trade_features.parquet (输出行数: 1411 秒)
     [√] 聚合完成 -> btc-updown-15m-1765521900_trade_features.parquet (输出行数: 760 秒)
     [√] 聚合完成 -> btc-updown-15m-1765699200_trade_features.parquet (输出行数: 460 秒)
     [√] 聚合完成 -> btc-updown-15m-1765746900_trade_features.parquet (输出行数: 911 秒)
     [√] 聚合完成 -> btc-updown-15m-1765766700_trade_features.parquet (输出行数: 861 秒)
     [√] 聚合完成 -> btc-updown-15m-1765205100_trade_features.parquet (输出行数: 1129 秒)
     [√] 聚合完成 -> btc-updown-15m-1765326600_trade_features.parquet (输出行数: 1339 秒)
     [√] 聚合完成 -> btc-updown-15m-1765422000_trade_features.parquet (输出行数: 884 秒)
     [√] 聚合完成 -> btc-updown-15m-1765290600_trade_features.parquet (输出行数: 1542 秒)
     [√] 聚合完成 -> btc-updown-15m-1765186200_trade_features.parquet (输出行数: 1333 秒)
     [√] 聚合完成 -> btc-updown-15m-1765554300_trade_features.parquet (输出行数: 1125 秒)
     [√] 聚合完成 -> btc-updown-15m-1765412100_trade_features.parquet (输出行数: 854 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765316700_trade_features.parquet (输出行数: 1387 秒)
     [√] 聚合完成 -> btc-updown-15m-1765398600_trade_features.parquet (输出行数: 1564 秒)
     [√] 聚合完成 -> btc-updown-15m-1765266300_trade_features.parquet (输出行数: 1140 秒)
     [√] 聚合完成 -> btc-updown-15m-1765424700_trade_features.parquet (输出行数: 1365 秒)
     [√] 聚合完成 -> btc-updown-15m-1765705500_trade_features.parquet (输出行数: 1175 秒)
     [√] 聚合完成 -> btc-updown-15m-1765627200_trade_features.parquet (输出行数: 569 秒)
     [√] 聚合完成 -> btc-updown-15m-1765620000_trade_features.parquet (输出行数: 831 秒)
     [√] 聚合完成 -> btc-updown-15m-1765450800_trade_features.parquet (输出行数: 1223 秒)
     [√] 聚合完成 -> btc-updown-15m-1765470600_trade_features.parquet (输出行数: 557 秒)
     [√] 聚合完成 -> btc-updown-15m-1765751400_trade_features.parquet (输出行数: 938 秒)
     [√] 聚合完成 -> btc-updown-15m-1765728000_trade_features.parquet (输出行数: 1156 秒)
     [√] 聚合完成 -> btc-updown-15m-1765219500_trade_features.parquet (输出行数: 789 秒)
     [√] 聚合完成 -> btc-updown-15m-1765578600_trade_features.parquet (输出行数: 951 秒)
     [√] 聚合完成 -> btc-updown-15m-1765431000_trade_features.parquet (输出行数: 1183 秒)
     [√] 聚合完成 -> btc-updown-15m-1765335600_trade_features.parquet (输出行数: 984 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765656000_trade_features.parquet (输出行数: 967 秒)
     [√] 聚合完成 -> btc-updown-15m-1765633500_trade_features.parquet (输出行数: 881 秒)
     [√] 聚合完成 -> btc-updown-15m-1765755900_trade_features.parquet (输出行数: 999 秒)
     [√] 聚合完成 -> btc-updown-15m-1765407600_trade_features.parquet (输出行数: 878 秒)
     [√] 聚合完成 -> btc-updown-15m-1765315800_trade_features.parquet (输出行数: 869 秒)
     [√] 聚合完成 -> btc-updown-15m-1765618200_trade_features.parquet (输出行数: 309 秒)
     [√] 聚合完成 -> btc-updown-15m-1765539000_trade_features.parquet (输出行数: 1145 秒)
     [√] 聚合完成 -> btc-updown-15m-1765192500_trade_features.parquet (输出行数: 1082 秒)
     [√] 聚合完成 -> btc-updown-15m-1765178100_trade_features.parquet (输出行数: 788 秒)
     [√] 聚合完成 -> btc-updown-15m-1765508400_trade_features.parquet (输出行数: 1042 秒)
     [√] 聚合完成 -> btc-updown-15m-1765691100_trade_features.parquet (输出行数: 837 秒)
     [√] 聚合完成 -> btc-updown-15m-1765242000_trade_features.parquet (输出行数: 1293 秒)
     [√] 聚合完成 -> btc-updown-15m-1765400400_trade_features.parquet (输出行数: 1221 秒)
     [√] 聚合完成 -> btc-updown-15m-1765361700_trade_features.parquet (输出行数: 773 秒)
     [√] 聚合完成 -> btc-updown-15m-1765341900_trade_features.parquet (输出行数: 1098 秒)
     [√] 聚合完成 -> btc-updown-15m-1765567800_trade_features.parquet (输出行数: 1222 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765620900_trade_features.parquet (输出行数: 933 秒)
     [√] 聚合完成 -> btc-updown-15m-1765770300_trade_features.parquet (输出行数: 1283 秒)
     [√] 聚合完成 -> btc-updown-15m-1765637100_trade_features.parquet (输出行数: 1024 秒)
     [√] 聚合完成 -> btc-updown-15m-1765261800_trade_features.parquet (输出行数: 1306 秒)
     [√] 聚合完成 -> btc-updown-15m-1765652400_trade_features.parquet (输出行数: 855 秒)
     [√] 聚合完成 -> btc-updown-15m-1765330200_trade_features.parquet (输出行数: 1136 秒)
     [√] 聚合完成 -> btc-updown-15m-1765402200_trade_features.parquet (输出行数: 1293 秒)
     [√] 聚合完成 -> btc-updown-15m-1765728900_trade_features.parquet (输出行数: 801 秒)
     [√] 聚合完成 -> btc-updown-15m-1765196100_trade_features.parquet (输出行数: 1260 秒)
     [√] 聚合完成 -> btc-updown-15m-1765369800_trade_features.parquet (输出行数: 1164 秒)
     [√] 聚合完成 -> btc-updown-15m-1765649700_trade_features.parquet (输出行数: 1046 秒)
     [√] 聚合完成 -> btc-updown-15m-1765583100_trade_features.parquet (输出行数: 661 秒)
     [√] 聚合完成 -> btc-updown-15m-1765209600_trade_features.parquet (输出行数: 1518 秒)
     [√] 聚合完成 -> btc-updown-15m-1765688400_trade_features.parquet (输出行数: 652 秒)
     [√] 聚合完成 -> btc-updown-15m-1765223100_trade_features.parquet (输出行数: 1332 秒)
     [√] 聚合完成 -> btc-updown-15m-1765606500_trade_features.parquet (输出行数: 657 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765365300_trade_features.parquet (输出行数: 1199 秒)
     [√] 聚合完成 -> btc-updown-15m-1765247400_trade_features.parquet (输出行数: 1266 秒)
     [√] 聚合完成 -> btc-updown-15m-1765675800_trade_features.parquet (输出行数: 692 秒)
     [√] 聚合完成 -> btc-updown-15m-1765511100_trade_features.parquet (输出行数: 1094 秒)
     [√] 聚合完成 -> btc-updown-15m-1765294200_trade_features.parquet (输出行数: 1041 秒)
     [√] 聚合完成 -> btc-updown-15m-1765182600_trade_features.parquet (输出行数: 1192 秒)
     [√] 聚合完成 -> btc-updown-15m-1765417500_trade_features.parquet (输出行数: 864 秒)
     [√] 聚合完成 -> btc-updown-15m-1765499400_trade_features.parquet (输出行数: 612 秒)
     [√] 聚合完成 -> btc-updown-15m-1765550700_trade_features.parquet (输出行数: 1506 秒)
     [√] 聚合完成 -> btc-updown-15m-1765242900_trade_features.parquet (输出行数: 1160 秒)
     [√] 聚合完成 -> btc-updown-15m-1765753200_trade_features.parquet (输出行数: 887 秒)
     [√] 聚合完成 -> btc-updown-15m-1765603800_trade_features.parquet (输出行数: 669 秒)
     [√] 聚合完成 -> btc-updown-15m-1765623600_trade_features.parquet (输出行数: 866 秒)
     [√] 聚合完成 -> btc-updown-15m-1765341000_trade_features.parquet (输出行数: 713 秒)
     [√] 聚合完成 -> btc-updown-15m-1765262700_trade_features.parquet (输出行数: 686 秒)
     [√] 聚合完成 -> btc-updown-15m-1765264500_trade_features.parquet (输出行数: 553 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765656900_trade_features.parquet (输出行数: 925 秒)
     [√] 聚合完成 -> btc-updown-15m-1765431900_trade_features.parquet (输出行数: 898 秒)
     [√] 聚合完成 -> btc-updown-15m-1765707300_trade_features.parquet (输出行数: 709 秒)
     [√] 聚合完成 -> btc-updown-15m-1765216800_trade_features.parquet (输出行数: 1303 秒)
     [√] 聚合完成 -> btc-updown-15m-1765625400_trade_features.parquet (输出行数: 890 秒)
     [√] 聚合完成 -> btc-updown-15m-1765474200_trade_features.parquet (输出行数: 808 秒)
     [√] 聚合完成 -> btc-updown-15m-1765755000_trade_features.parquet (输出行数: 1439 秒)
     [√] 聚合完成 -> btc-updown-15m-1765236600_trade_features.parquet (输出行数: 1142 秒)
     [√] 聚合完成 -> btc-updown-15m-1765676700_trade_features.parquet (输出行数: 964 秒)
     [√] 聚合完成 -> btc-updown-15m-1765184400_trade_features.parquet (输出行数: 820 秒)
     [√] 聚合完成 -> btc-updown-15m-1765681200_trade_features.parquet (输出行数: 1105 秒)
     [√] 聚合完成 -> btc-updown-15m-1765539900_trade_features.parquet (输出行数: 1094 秒)
     [√] 聚合完成 -> btc-updown-15m-1765596600_trade_features.parquet (输出行数: 767 秒)
     [√] 聚合完成 -> btc-updown-15m-1765368900_trade_features.parquet (输出行数: 1307 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765197000_trade_features.parquet (输出行数: 1141 秒)
     [√] 聚合完成 -> btc-updown-15m-1765180800_trade_features.parquet (输出行数: 82 秒)
     [√] 聚合完成 -> btc-updown-15m-1765239300_trade_features.parquet (输出行数: 1306 秒)
     [√] 聚合完成 -> btc-updown-15m-1765491300_trade_features.parquet (输出行数: 463 秒)
     [√] 聚合完成 -> btc-updown-15m-1765729800_trade_features.parquet (输出行数: 669 秒)
     [√] 聚合完成 -> btc-updown-15m-1765260900_trade_features.parquet (输出行数: 1048 秒)
     [√] 聚合完成 -> btc-updown-15m-1765277100_trade_features.parquet (输出行数: 999 秒)
     [√] 聚合完成 -> btc-updown-15m-1765435500_trade_features.parquet (输出行数: 1212 秒)
     [√] 聚合完成 -> btc-updown-15m-1765599300_trade_features.parquet (输出行数: 855 秒)
     [√] 聚合完成 -> btc-updown-15m-1765771200_trade_features.parquet (输出行数: 871 秒)
     [√] 聚合完成 -> btc-updown-15m-1765621800_trade_features.parquet (输出行数: 745 秒)
     [√] 聚合完成 -> btc-updown-15m-1765725300_trade_features.parquet (输出行数: 1335 秒)
     [√] 聚合完成 -> btc-updown-15m-1765413900_trade_features.parquet (输出行数: 1340 秒)
     [√] 聚合完成 -> btc-updown-15m-1765246500_trade_features.parquet (输出行数: 974 秒)
     [√] 聚合完成 -> btc-updown-15m-1765674900_trade_features.parquet (输出行数: 819 秒)
     [√] 聚合完成 -> btc-updown-15m-1765607400_trade_features.parquet (输出行数: 587 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765740600_trade_features.parquet (输出行数: 1143 秒)
     [√] 聚合完成 -> btc-updown-15m-1765234800_trade_features.parquet (输出行数: 1168 秒)
     [√] 聚合完成 -> btc-updown-15m-1765456200_trade_features.parquet (输出行数: 1357 秒)
     [√] 聚合完成 -> btc-updown-15m-1765433700_trade_features.parquet (输出行数: 636 秒)
     [√] 聚合完成 -> btc-updown-15m-1765208700_trade_features.parquet (输出行数: 972 秒)
     [√] 聚合完成 -> btc-updown-15m-1765594800_trade_features.parquet (输出行数: 771 秒)
     [√] 聚合完成 -> btc-updown-15m-1765602900_trade_features.parquet (输出行数: 772 秒)
     [√] 聚合完成 -> btc-updown-15m-1765752300_trade_features.parquet (输出行数: 1003 秒)
     [√] 聚合完成 -> btc-updown-15m-1765551600_trade_features.parquet (输出行数: 899 秒)
     [√] 聚合完成 -> btc-updown-15m-1765498500_trade_features.parquet (输出行数: 367 秒)
     [√] 聚合完成 -> btc-updown-15m-1765670400_trade_features.parquet (输出行数: 948 秒)
     [√] 聚合完成 -> btc-updown-15m-1765312200_trade_features.parquet (输出行数: 1528 秒)
     [√] 聚合完成 -> btc-updown-15m-1765243800_trade_features.parquet (输出行数: 1159 秒)
     [√] 聚合完成 -> btc-updown-15m-1765263600_trade_features.parquet (输出行数: 1253 秒)
     [√] 聚合完成 -> btc-updown-15m-1765420200_trade_features.parquet (输出行数: 1389 秒)
     [√] 聚合完成 -> btc-updown-15m-1765566000_trade_features.parquet (输出行数: 776 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765340100_trade_features.parquet (输出行数: 1158 秒)
     [√] 聚合完成 -> btc-updown-15m-1765622700_trade_features.parquet (输出行数: 989 秒)
     [√] 聚合完成 -> btc-updown-15m-1765528200_trade_features.parquet (输出行数: 554 秒)
     [√] 聚合完成 -> btc-updown-15m-1765386000_trade_features.parquet (输出行数: 1447 秒)
     [√] 聚合完成 -> btc-updown-15m-1765179900_trade_features.parquet (输出行数: 837 秒)
     [√] 聚合完成 -> btc-updown-15m-1765680300_trade_features.parquet (输出行数: 888 秒)
     [√] 聚合完成 -> btc-updown-15m-1765347300_trade_features.parquet (输出行数: 800 秒)
     [√] 聚合完成 -> btc-updown-15m-1765505700_trade_features.parquet (输出行数: 1277 秒)
     [√] 聚合完成 -> btc-updown-15m-1765624500_trade_features.parquet (输出行数: 608 秒)
     [√] 聚合完成 -> btc-updown-15m-1765265400_trade_features.parquet (输出行数: 883 秒)
     [√] 聚合完成 -> btc-updown-15m-1765657800_trade_features.parquet (输出行数: 1020 秒)
     [√] 聚合完成 -> btc-updown-15m-1765314000_trade_features.parquet (输出行数: 1354 秒)
     [√] 聚合完成 -> btc-updown-15m-1765677600_trade_features.parquet (输出行数: 922 秒)
     [√] 聚合完成 -> btc-updown-15m-1765754100_trade_features.parquet (输出行数: 1369 秒)
     [√] 聚合完成 -> btc-updown-15m-1765555200_trade_features.parquet (输出行数: 1558 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765405800_trade_features.parquet (输出行数: 13 秒)
     [√] 聚合完成 -> btc-updown-15m-1765674000_trade_features.parquet (输出行数: 974 秒)
     [√] 聚合完成 -> btc-updown-15m-1765317600_trade_features.parquet (输出行数: 1450 秒)
     [√] 聚合完成 -> btc-updown-15m-1765413000_trade_features.parquet (输出行数: 847 秒)
     [√] 聚合完成 -> btc-updown-15m-1765757700_trade_features.parquet (输出行数: 778 秒)
     [√] 聚合完成 -> btc-updown-15m-1765345500_trade_features.parquet (输出行数: 1075 秒)
     [√] 聚合完成 -> btc-updown-15m-1765626300_trade_features.parquet (输出行数: 1011 秒)
     [√] 聚合完成 -> btc-updown-15m-1765267200_trade_features.parquet (输出行数: 509 秒)
     [√] 聚合完成 -> btc-updown-15m-1765562400_trade_features.parquet (输出行数: 168 秒)
     [√] 聚合完成 -> btc-updown-15m-1765425600_trade_features.parquet (输出行数: 1231 秒)
     [√] 聚合完成 -> btc-updown-15m-1765685700_trade_features.parquet (输出行数: 1191 秒)
     [√] 聚合完成 -> btc-updown-15m-1765368000_trade_features.parquet (输出行数: 1219 秒)
     [√] 聚合完成 -> btc-updown-15m-1765197900_trade_features.parquet (输出行数: 1412 秒)
     [√] 聚合完成 -> btc-updown-15m-1765382400_trade_features.parquet (输出行数: 1279 秒)
     [√] 聚合完成 -> btc-updown-15m-1765260000_trade_features.parquet (输出行数: 741 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765343700_trade_features.parquet (输出行数: 1126 秒)
     [√] 聚合完成 -> btc-updown-15m-1765750500_trade_features.parquet (输出行数: 1113 秒)
     [√] 聚合完成 -> btc-updown-15m-1765310400_trade_features.parquet (输出行数: 1310 秒)
     [√] 聚合完成 -> btc-updown-15m-1765258200_trade_features.parquet (输出行数: 626 秒)
     [√] 聚合完成 -> btc-updown-15m-1765386900_trade_features.parquet (输出行数: 755 秒)
     [√] 聚合完成 -> btc-updown-15m-1765179000_trade_features.parquet (输出行数: 1293 秒)
     [√] 聚合完成 -> btc-updown-15m-1765193400_trade_features.parquet (输出行数: 1012 秒)
     [√] 聚合完成 -> btc-updown-15m-1765538100_trade_features.parquet (输出行数: 921 秒)
     [√] 聚合完成 -> btc-updown-15m-1765454400_trade_features.parquet (输出行数: 1169 秒)
     [√] 聚合完成 -> btc-updown-15m-1765334700_trade_features.parquet (输出行数: 930 秒)
     [√] 聚合完成 -> btc-updown-15m-1765430100_trade_features.parquet (输出行数: 713 秒)
     [√] 聚合完成 -> btc-updown-15m-1765273500_trade_features.parquet (输出行数: 1144 秒)
     [√] 聚合完成 -> btc-updown-15m-1765406700_trade_features.parquet (输出行数: 1141 秒)
     [√] 聚合完成 -> btc-updown-15m-1765488600_trade_features.parquet (输出行数: 1365 秒)
     [√] 聚合完成 -> btc-updown-15m-1765314900_trade_features.parquet (输出行数: 1103 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765744200_trade_features.parquet (输出行数: 1333 秒)
     [√] 聚合完成 -> btc-updown-15m-1765602000_trade_features.parquet (输出行数: 864 秒)
     [√] 聚合完成 -> btc-updown-15m-1765721700_trade_features.parquet (输出行数: 1195 秒)
     [√] 聚合完成 -> btc-updown-15m-1765566900_trade_features.parquet (输出行数: 880 秒)
     [√] 聚合完成 -> btc-updown-15m-1765437300_trade_features.parquet (输出行数: 928 秒)
     [√] 聚合完成 -> btc-updown-15m-1765452600_trade_features.parquet (输出行数: 1344 秒)
     [√] 聚合完成 -> btc-updown-15m-1765712700_trade_features.parquet (输出行数: 902 秒)
     [√] 聚合完成 -> btc-updown-15m-1765441800_trade_features.parquet (输出行数: 916 秒)
     [√] 聚合完成 -> btc-updown-15m-1765353600_trade_features.parquet (输出行数: 518 秒)
     [√] 聚合完成 -> btc-updown-15m-1765510200_trade_features.parquet (输出行数: 996 秒)
     [√] 聚合完成 -> btc-updown-15m-1765461600_trade_features.parquet (输出行数: 1238 秒)
     [√] 聚合完成 -> btc-updown-15m-1765526400_trade_features.parquet (输出行数: 172 秒)
     [√] 聚合完成 -> btc-updown-15m-1765222200_trade_features.parquet (输出行数: 1243 秒)
     [√] 聚合完成 -> btc-updown-15m-1765662300_trade_features.parquet (输出行数: 886 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765695600_trade_features.parquet (输出行数: 1031 秒)
     [√] 聚合完成 -> btc-updown-15m-1765549800_trade_features.parquet (输出行数: 1065 秒)
     [√] 聚合完成 -> btc-updown-15m-1765569600_trade_features.parquet (输出行数: 1119 秒)
     [√] 聚合完成 -> btc-updown-15m-1765582200_trade_features.parquet (输出行数: 854 秒)
     [√] 聚合完成 -> btc-updown-15m-1765281600_trade_features.parquet (输出行数: 1357 秒)
     [√] 聚合完成 -> btc-updown-15m-1765584000_trade_features.parquet (输出行数: 675 秒)
     [√] 聚合完成 -> btc-updown-15m-1765403100_trade_features.parquet (输出行数: 416 秒)
     [√] 聚合完成 -> btc-updown-15m-1765307700_trade_features.parquet (输出行数: 1356 秒)
     [√] 聚合完成 -> btc-updown-15m-1765664100_trade_features.parquet (输出行数: 892 秒)
     [√] 聚合完成 -> btc-updown-15m-1765545300_trade_features.parquet (输出行数: 1154 秒)
     [√] 聚合完成 -> btc-updown-15m-1765224000_trade_features.parquet (输出行数: 730 秒)
     [√] 聚合完成 -> btc-updown-15m-1765636200_trade_features.parquet (输出行数: 575 秒)
     [√] 聚合完成 -> btc-updown-15m-1765355400_trade_features.parquet (输出行数: 1180 秒)
     [√] 聚合完成 -> btc-updown-15m-1765331100_trade_features.parquet (输出行数: 891 秒)
     [√] 聚合完成 -> btc-updown-15m-1765714500_trade_features.parquet (输出行数: 1263 秒)
     [√] 聚合完成 -> btc-updown-15m-1765597500_trade_features.parquet (输出行数: 533 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765293300_trade_features.parquet (输出行数: 1106 秒)
     [√] 聚合完成 -> btc-updown-15m-1765237500_trade_features.parquet (输出行数: 1290 秒)
     [√] 聚合完成 -> btc-updown-15m-1765370700_trade_features.parquet (输出行数: 1240 秒)
     [√] 聚合完成 -> btc-updown-15m-1765475100_trade_features.parquet (输出行数: 802 秒)
     [√] 聚合完成 -> btc-updown-15m-1765731600_trade_features.parquet (输出行数: 1122 秒)
     [√] 聚合完成 -> btc-updown-15m-1765711800_trade_features.parquet (输出行数: 1107 秒)
     [√] 聚合完成 -> btc-updown-15m-1765576800_trade_features.parquet (输出行数: 703 秒)
     [√] 聚合完成 -> btc-updown-15m-1765442700_trade_features.parquet (输出行数: 962 秒)
     [√] 聚合完成 -> btc-updown-15m-1765350900_trade_features.parquet (输出行数: 955 秒)
     [√] 聚合完成 -> btc-updown-15m-1765444500_trade_features.parquet (输出行数: 1069 秒)
     [√] 聚合完成 -> btc-updown-15m-1765647000_trade_features.parquet (输出行数: 910 秒)
     [√] 聚合完成 -> btc-updown-15m-1765416600_trade_features.parquet (输出行数: 1284 秒)
     [√] 聚合完成 -> btc-updown-15m-1765473300_trade_features.parquet (输出行数: 521 秒)
     [√] 聚合完成 -> btc-updown-15m-1765169100_trade_features.parquet (输出行数: 1081 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765396800_trade_features.parquet (输出行数: 1086 秒)
     [√] 聚合完成 -> btc-updown-15m-1765248300_trade_features.parquet (输出行数: 1164 秒)
     [√] 聚合完成 -> btc-updown-15m-1765609200_trade_features.parquet (输出行数: 818 秒)
     [√] 聚合完成 -> btc-updown-15m-1765183500_trade_features.parquet (输出行数: 1285 秒)
     [√] 聚合完成 -> btc-updown-15m-1765295100_trade_features.parquet (输出行数: 893 秒)
     [√] 聚合完成 -> btc-updown-15m-1765584900_trade_features.parquet (输出行数: 933 秒)
     [√] 聚合完成 -> btc-updown-15m-1765592100_trade_features.parquet (输出行数: 526 秒)
     [√] 聚合完成 -> btc-updown-15m-1765218600_trade_features.parquet (输出行数: 1172 秒)
     [√] 聚合完成 -> btc-updown-15m-1765658700_trade_features.parquet (输出行数: 798 秒)
     [√] 聚合完成 -> btc-updown-15m-1765579500_trade_features.parquet (输出行数: 917 秒)
     [√] 聚合完成 -> btc-updown-15m-1765256400_trade_features.parquet (输出行数: 1035 秒)
     [√] 聚合完成 -> btc-updown-15m-1765735200_trade_features.parquet (输出行数: 1044 秒)
     [√] 聚合完成 -> btc-updown-15m-1765374300_trade_features.parquet (输出行数: 1262 秒)
     [√] 聚合完成 -> btc-updown-15m-1765224900_trade_features.parquet (输出行数: 1128 秒)
     [√] 聚合完成 -> btc-updown-15m-1765232100_trade_features.parquet (输出行数: 1322 秒)
     [√] 聚合完成 -> btc-updown-15m-1765471500_trade_features.parquet (输出行数: 236 秒)
     [√] 聚合完成 -> btc-updown-15m-1765446300_trade_features.parquet (输出行数: 916 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765704600_trade_features.parquet (输出行数: 229 秒)
     [√] 聚合完成 -> btc-updown-15m-1765643400_trade_features.parquet (输出行数: 990 秒)
     [√] 聚合完成 -> btc-updown-15m-1765321200_trade_features.parquet (输出行数: 911 秒)
     [√] 聚合完成 -> btc-updown-15m-1765270800_trade_features.parquet (输出行数: 926 秒)
     [√] 聚合完成 -> btc-updown-15m-1765761300_trade_features.parquet (输出行数: 1105 秒)
     [√] 聚合完成 -> btc-updown-15m-1765399500_trade_features.parquet (输出行数: 782 秒)
     [√] 聚合完成 -> btc-updown-15m-1765187100_trade_features.parquet (输出行数: 904 秒)
     [√] 聚合完成 -> btc-updown-15m-1765378800_trade_features.parquet (输出行数: 1056 秒)
     [√] 聚合完成 -> btc-updown-15m-1765291500_trade_features.parquet (输出行数: 1230 秒)
     [√] 聚合完成 -> btc-updown-15m-1765634400_trade_features.parquet (输出行数: 1026 秒)
     [√] 聚合完成 -> btc-updown-15m-1765515600_trade_features.parquet (输出行数: 1091 秒)
     [√] 聚合完成 -> btc-updown-15m-1765207800_trade_features.parquet (输出行数: 1281 秒)
     [√] 聚合完成 -> btc-updown-15m-1765357200_trade_features.parquet (输出行数: 1257 秒)
     [√] 聚合完成 -> btc-updown-15m-1765716300_trade_features.parquet (输出行数: 1146 秒)
     [√] 聚合完成 -> btc-updown-15m-1765647900_trade_features.parquet (输出行数: 939 秒)
     [√] 聚合完成 -> btc-updown-15m-1765667700_trade_features.parquet (输出行数: 1090 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765304100_trade_features.parquet (输出行数: 1324 秒)
     [√] 聚合完成 -> btc-updown-15m-1765227600_trade_features.parquet (输出行数: 1227 秒)
     [√] 聚合完成 -> btc-updown-15m-1765465200_trade_features.parquet (输出行数: 855 秒)
     [√] 聚合完成 -> btc-updown-15m-1765690200_trade_features.parquet (输出行数: 905 秒)
     [√] 聚合完成 -> btc-updown-15m-1765587600_trade_features.parquet (输出行数: 777 秒)
     [√] 聚合完成 -> btc-updown-15m-1765328400_trade_features.parquet (输出行数: 1114 秒)
     [√] 聚合完成 -> btc-updown-15m-1765768500_trade_features.parquet (输出行数: 1252 秒)
     [√] 聚合完成 -> btc-updown-15m-1765580400_trade_features.parquet (输出行数: 1023 秒)
     [√] 聚合完成 -> btc-updown-15m-1765619100_trade_features.parquet (输出行数: 881 秒)
     [√] 聚合完成 -> btc-updown-15m-1765220400_trade_features.parquet (输出行数: 1139 秒)
     [√] 聚合完成 -> btc-updown-15m-1765612800_trade_features.parquet (输出行数: 364 秒)
     [√] 聚合完成 -> btc-updown-15m-1765660500_trade_features.parquet (输出行数: 1048 秒)
     [√] 聚合完成 -> btc-updown-15m-1765541700_trade_features.parquet (输出行数: 1099 秒)
     [√] 聚合完成 -> btc-updown-15m-1765632600_trade_features.parquet (输出行数: 1140 秒)
     [√] 聚合完成 -> btc-updown-15m-1765350000_trade_features.parquet (输出行数: 864 秒)
     [√] 聚合完成 -> btc-updown-15m-1765225800_trade_features.parquet (输出行数: 1110 秒)
     [√] 聚合完成 -> btc-updown-15m-1765375200_trade_features.parquet (输出行数: 1078 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765233000_trade_features.parquet (输出行数: 966 秒)
     [√] 聚合完成 -> btc-updown-15m-1765665900_trade_features.parquet (输出行数: 1106 秒)
     [√] 聚合完成 -> btc-updown-15m-1765673100_trade_features.parquet (输出行数: 475 秒)
     [√] 聚合完成 -> btc-updown-15m-1765734300_trade_features.parquet (输出行数: 1206 秒)
     [√] 聚合完成 -> btc-updown-15m-1765447200_trade_features.parquet (输出行数: 1180 秒)
     [√] 聚合完成 -> btc-updown-15m-1765659600_trade_features.parquet (输出行数: 874 秒)
     [√] 聚合完成 -> btc-updown-15m-1765585800_trade_features.parquet (输出行数: 720 秒)
     [√] 聚合完成 -> btc-updown-15m-1765593000_trade_features.parquet (输出行数: 458 秒)
     [√] 聚合完成 -> btc-updown-15m-1765738800_trade_features.parquet (输出行数: 573 秒)
     [√] 聚合完成 -> btc-updown-15m-1765548000_trade_features.parquet (输出行数: 999 秒)
     [√] 聚合完成 -> btc-updown-15m-1765202400_trade_features.parquet (输出行数: 1412 秒)
     [√] 聚合完成 -> btc-updown-15m-1765630800_trade_features.parquet (输出行数: 1051 秒)
     [√] 聚合完成 -> btc-updown-15m-1765344600_trade_features.parquet (输出行数: 1157 秒)
     [√] 聚合完成 -> btc-updown-15m-1765440000_trade_features.parquet (输出行数: 567 秒)
     [√] 聚合完成 -> btc-updown-15m-1765320300_trade_features.parquet (输出行数: 1295 秒)
     [√] 聚合完成 -> btc-updown-15m-1765642500_trade_features.parquet (输出行数: 667 秒)
     [√] 聚合完成 -> btc-updown-15m-1765586700_trade_features.parquet (输出行数: 842 秒)
     [√] 聚合完成 -> btc-updown-15m-1765717200_trade_features.parquet (输出行数: 727 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765274400_trade_features.parquet (输出行数: 1234 秒)
     [√] 聚合完成 -> btc-updown-15m-1765514700_trade_features.parquet (输出行数: 748 秒)
     [√] 聚合完成 -> btc-updown-15m-1765453500_trade_features.parquet (输出行数: 1336 秒)
     [√] 聚合完成 -> btc-updown-15m-1765288800_trade_features.parquet (输出行数: 1214 秒)
     [√] 聚合完成 -> btc-updown-15m-1765356300_trade_features.parquet (输出行数: 1058 秒)
     [√] 聚合完成 -> btc-updown-15m-1765206900_trade_features.parquet (输出行数: 1302 秒)
     [√] 聚合完成 -> btc-updown-15m-1765226700_trade_features.parquet (输出行数: 1078 秒)
     [√] 聚合完成 -> btc-updown-15m-1765745100_trade_features.parquet (输出行数: 1087 秒)
     [√] 聚合完成 -> btc-updown-15m-1765464300_trade_features.parquet (输出行数: 531 秒)
     [√] 聚合完成 -> btc-updown-15m-1765305000_trade_features.parquet (输出行数: 1050 秒)
     [√] 聚合完成 -> btc-updown-15m-1765252800_trade_features.parquet (输出行数: 988 秒)
     [√] 聚合完成 -> btc-updown-15m-1765489500_trade_features.parquet (输出行数: 944 秒)
     [√] 聚合完成 -> btc-updown-15m-1765661400_trade_features.parquet (输出行数: 1059 秒)
     [√] 聚合完成 -> btc-updown-15m-1765303200_trade_features.parquet (输出行数: 1411 秒)
     [√] 聚合完成 -> btc-updown-15m-1765743300_trade_features.parquet (输出行数: 1101 秒)
     [√] 聚合完成 -> btc-updown-15m-1765710000_trade_features.parquet (输出行数: 1066 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765272600_trade_features.parquet (输出行数: 874 秒)
     [√] 聚合完成 -> btc-updown-15m-1765769400_trade_features.parquet (输出行数: 900 秒)
     [√] 聚合完成 -> btc-updown-15m-1765259100_trade_features.parquet (输出行数: 868 秒)
     [√] 聚合完成 -> btc-updown-15m-1765468800_trade_features.parquet (输出行数: 358 秒)
     [√] 聚合完成 -> btc-updown-15m-1765548900_trade_features.parquet (输出行数: 1198 秒)
     [√] 聚合完成 -> btc-updown-15m-1765419300_trade_features.parquet (输出行数: 1393 秒)
     [√] 聚合完成 -> btc-updown-15m-1765694700_trade_features.parquet (输出行数: 1084 秒)
     [√] 聚合完成 -> btc-updown-15m-1765568700_trade_features.parquet (输出行数: 1202 秒)
     [√] 聚合完成 -> btc-updown-15m-1765440900_trade_features.parquet (输出行数: 928 秒)
     [√] 聚合完成 -> btc-updown-15m-1765457100_trade_features.parquet (输出行数: 864 秒)
     [√] 聚合完成 -> btc-updown-15m-1765352700_trade_features.parquet (输出行数: 877 秒)
     [√] 聚合完成 -> btc-updown-15m-1765713600_trade_features.parquet (输出行数: 1365 秒)
     [√] 聚合完成 -> btc-updown-15m-1765663200_trade_features.parquet (输出行数: 1020 秒)
     [√] 聚合完成 -> btc-updown-15m-1765741500_trade_features.parquet (输出行数: 1310 秒)
     [√] 聚合完成 -> btc-updown-15m-1765460700_trade_features.parquet (输出行数: 1285 秒)
     [√] 聚合完成 -> btc-updown-15m-1765233900_trade_features.parquet (输出行数: 1223 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765414800_trade_features.parquet (输出行数: 990 秒)
     [√] 聚合完成 -> btc-updown-15m-1765665000_trade_features.parquet (输出行数: 685 秒)
     [√] 聚合完成 -> btc-updown-15m-1765715400_trade_features.parquet (输出行数: 894 秒)
     [√] 聚合完成 -> btc-updown-15m-1765434600_trade_features.parquet (输出行数: 553 秒)
     [√] 聚合完成 -> btc-updown-15m-1765276200_trade_features.parquet (输出行数: 1193 秒)
     [√] 聚合完成 -> btc-updown-15m-1765354500_trade_features.parquet (输出行数: 749 秒)
     [√] 聚合完成 -> btc-updown-15m-1765280700_trade_features.parquet (输出行数: 1012 秒)
     [√] 聚合完成 -> btc-updown-15m-1765593900_trade_features.parquet (输出行数: 685 秒)
     [√] 聚合完成 -> btc-updown-15m-1765486800_trade_features.parquet (输出行数: 961 秒)
     [√] 聚合完成 -> btc-updown-15m-1765730700_trade_features.parquet (输出行数: 1470 秒)
     [√] 聚合完成 -> btc-updown-15m-1765371600_trade_features.parquet (输出行数: 1270 秒)
     [√] 聚合完成 -> btc-updown-15m-1765199700_trade_features.parquet (输出行数: 1045 秒)
     [√] 聚合完成 -> btc-updown-15m-1765443600_trade_features.parquet (输出行数: 1185 秒)
     [√] 聚合完成 -> btc-updown-15m-1765351800_trade_features.parquet (输出行数: 880 秒)
     [√] 聚合完成 -> btc-updown-15m-1765710900_trade_features.parquet (输出行数: 1027 秒)
     [√] 聚合完成 -> btc-updown-15m-1765529100_trade_features.parquet (输出行数: 657 秒)
     [√] 聚合完成 -> btc-updown-15m-1765608300_trade_features.parquet (输出行数: 808 秒)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 聚合完成 -> btc-updown-15m-1765249200_trade_features.parquet (输出行数: 1186 秒)
     [√] 聚合完成 -> btc-updown-15m-1765646100_trade_features.parquet (输出行数: 873 秒)
     [√] 聚合完成 -> btc-updown-15m-1765325700_trade_features.parquet (输出行数: 780 秒)
     [√] 聚合完成 -> btc-updown-15m-1765421100_trade_features.parquet (输出行数: 1291 秒)
     [√] 聚合完成 -> btc-updown-15m-1765445400_trade_features.parquet (输出行数: 1115 秒)
     [√] 聚合完成 -> btc-updown-15m-1765206000_trade_features.parquet (输出行数: 1140 秒)
     [√] 聚合完成 -> btc-updown-15m-1765522800_trade_features.parquet (输出行数: 419 秒)
     [√] 聚合完成 -> btc-updown-15m-1765305900_trade_features.parquet (输出行数: 1541 秒)
     [√] 聚合完成 -> btc-updown-15m-1765313100_trade_features.parquet (输出行数: 1433 秒)

🎉 恭喜！所有交易特征聚合完毕！

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/3235670114.py:24: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

In [4]:
import pandas as pd
from pathlib import Path
import glob

# ==========================================
# 1. 路径配置 (读取上一步聚合好的目录)
# ==========================================
BASE_DIR = Path('/Volumes/KIOXIA/Project/lob')
INPUT_DIR = BASE_DIR / 'final_aggregated_trades'
WEEKS_TO_PROCESS = ['week1', 'week2']

all_dfs = []

print("🚀 开始合并所有聚合后的交易特征表...\n")

# ==========================================
# 2. 遍历读取并合并
# ==========================================
for week in WEEKS_TO_PROCESS:
    week_dir = INPUT_DIR / week
    
    # 查找该周下面所有的 parquet 文件
    parquet_files = glob.glob(str(week_dir / '*_trade_features.parquet'))
    
    if not parquet_files:
        print(f"⚠️ 警告：在 {week} 未找到任何特征文件！请检查上一步是否成功。")
        continue
        
    print(f"   [{week}] 找到 {len(parquet_files)} 个合约文件，正在拼接...")
    
    for f in parquet_files:
        df = pd.read_parquet(f)
        all_dfs.append(df)

# ==========================================
# 3. 生成大总表并打印核对信息
# ==========================================
if all_dfs:
    # 纵向合并所有表格
    df_grand_total = pd.concat(all_dfs, ignore_index=True)
    
    # 按照 时间 和 合约名称 重新排序，让数据规规矩矩
    print("   [!] 正在按照时间和合约名称进行全盘排序...")
    df_grand_total.sort_values(by=['timestamp', 'slug'], inplace=True)
    df_grand_total.reset_index(drop=True, inplace=True)
    
    # 保存这份无敌大总表
    output_path = INPUT_DIR / "grand_total_trades_master.parquet"
    df_grand_total.to_parquet(output_path)
    
    print("\n🎉 大总表合并大功告成！")
    print("=" * 50)
    print(f"📊 最终总表行数 (Rows): {df_grand_total.shape[0]} 行")
    print(f"📊 最终总表列数 (Cols): {df_grand_total.shape[1]} 列")
    print("=" * 50)
    print(f"💾 文件已保存至: {output_path}\n")
    
    print("👀 前 5 行数据预览:")
    print(df_grand_total.head())
else:
    print("❌ 未找到任何数据进行合并，请检查路径或上一步的输出。")

🚀 开始合并所有聚合后的交易特征表...

   [week1] 找到 627 个合约文件，正在拼接...
   [week2] 找到 628 个合约文件，正在拼接...
   [!] 正在按照时间和合约名称进行全盘排序...

🎉 大总表合并大功告成！
==================================================
📊 最终总表行数 (Rows): 1179430 行
📊 最终总表列数 (Cols): 12 列
==================================================
💾 文件已保存至: /Volumes/KIOXIA/Project/lob/final_aggregated_trades/grand_total_trades_master.parquet

👀 前 5 行数据预览:
                        slug  \
0  btc-updown-15m-1764565200
1  btc-updown-15m-1764565200
2  btc-updown-15m-1764565200
3  btc-updown-15m-1764565200
4  btc-updown-15m-1764565200

                                              market  \
0  0xdc2dc0399bf6584e9b502ca51d61a8a9570b731e4e5b...
1  0xdc2dc0399bf6584e9b502ca51d61a8a9570b731e4e5b...
2  0xdc2dc0399bf6584e9b502ca51d61a8a9570b731e4e5b...
3  0xdc2dc0399bf6584e9b502ca51d61a8a9570b731e4e5b...
4  0xdc2dc0399bf6584e9b502ca51d61a8a9570b731e4e5b...

                                            asset_id  \
0  4070657408180023518277177261998523093049036367...
1  4070657408180023518277177261998523093049036367...
2  7624450354679081382276088807478298687015500496...
3  4070657408180023518277177261998523093049036367...
4  7624450354679081382276088807478298687015500496...

                  timestamp  buy_trade_size  buy_trade_count  \
0 2025-12-01 05:00:23+00:00        2.272726              1.0
1 2025-12-01 05:00:24+00:00      111.720000              1.0
2 2025-12-01 05:00:25+00:00       19.000000              2.0
3 2025-12-01 05:00:26+00:00       10.000000              2.0
4 2025-12-01 05:00:26+00:00        9.000000              1.0

   taker_buy_trade_nominal_value  buy_trade_vwap  sell_trade_size  \
0                       0.999999        0.440000              0.0
1                      50.274000        0.450000              0.0
2                      10.730000        0.564737              0.0
3                       4.300000        0.430000              0.0
4                       5.220000        0.580000              0.0

   sell_trade_count  taker_sell_trade_nominal_value  sell_trade_vwap
0               0.0                             0.0              NaN
1               0.0                             0.0              NaN
2               0.0                             0.0              NaN
3               0.0                             0.0              NaN
4               0.0                             0.0              NaN

In [8]:
import pandas as pd
from pathlib import Path
import glob

# ==========================================
# 1. 路径配置
# ==========================================
BASE_DIR = Path('/Volumes/KIOXIA/Project/lob')
INPUT_PATH = BASE_DIR / 'final_aggregated_trades' / 'grand_total_trades_master.parquet'
OUTPUT_PATH = BASE_DIR / 'final_aggregated_trades' / 'grand_total_trades_WIDE_master.parquet'

print("🚀 正在加载交易总表...")
df_trades = pd.read_parquet(INPUT_PATH)

# ==========================================
# 2. 从 CSV 中提取 asset_id -> Up/Down 的映射
# ==========================================
print("🔍 正在构建 Token 映射字典...")
mapping_dict = {}
# 找到所有的 trades_week.csv
csv_files = glob.glob(str(BASE_DIR / '*' / 'trades_week*.csv'))

for f in csv_files:
    df_meta = pd.read_csv(f, dtype={'token_id': str})
    # 把 token_id 和 token_name (Up/Down) 变成字典
    temp_dict = df_meta.drop_duplicates('token_id').set_index('token_id')['token_name'].to_dict()
    mapping_dict.update(temp_dict)

# ==========================================
# 3. 翻译 asset_id 并进行透视 (Pivot)
# ==========================================
print("🔄 正在将长表横向展开为宽表 (Pivot)...")

# 翻译: 匹配出 Up 和 Down
df_trades['token_type'] = df_trades['asset_id'].map(mapping_dict)

# 踢掉没有匹配上类型的数据（安全校验）
df_trades.dropna(subset=['token_type'], inplace=True)

# 找出需要拆分为 Up/Down 的数值列
val_cols = [c for c in df_trades.columns if c not in ['slug', 'market', 'asset_id', 'timestamp', 'token_type']]

# 进行数据透视，以 timestamp 和 slug 为基准，把 token_type(Up/Down) 变成列
df_wide = df_trades.pivot_table(
    index=['timestamp', 'slug'], 
    columns='token_type', 
    values=val_cols, 
    aggfunc='first' # 数据已经是1秒聚合的了，直接取 first 即可
)

# 重命名列名 (例如把 ('buy_trade_size', 'Up') 变成 'Up_buy_trade_size')
df_wide.columns = [f"{token}_{metric}" for metric, token in df_wide.columns]
df_wide.reset_index(inplace=True)

# ==========================================
# 4. 缺失值处理与保存
# ==========================================
# 某秒只有 Up 交易没 Down 交易时，Down 的 size 和 count 应该填 0，VWAP 保持 NaN
fill_zero_cols = [c for c in df_wide.columns if any(k in c for k in ['_size', '_count', '_nominal_value'])]
df_wide[fill_zero_cols] = df_wide[fill_zero_cols].fillna(0)

# 保存最终版宽表
df_wide.to_parquet(OUTPUT_PATH)

print(f"\n🎉 转换完成！表结构已完美兼容。")
print(f"📊 新表行数: {df_wide.shape[0]} 行")
print(f"📊 新表列数: {df_wide.shape[1]} 列")
print(f"💾 已保存至: {OUTPUT_PATH}\n")

print("👀 前 5 行数据预览:")
print(df_wide.head())

🚀 正在加载交易总表...
🔍 正在构建 Token 映射字典...
🔄 正在将长表横向展开为宽表 (Pivot)...

🎉 转换完成！表结构已完美兼容。
📊 新表行数: 779234 行
📊 新表列数: 18 列
💾 已保存至: /Volumes/KIOXIA/Project/lob/final_aggregated_trades/grand_total_trades_WIDE_master.parquet

👀 前 5 行数据预览:
                  timestamp                       slug  Down_buy_trade_count  \
0 2025-12-01 05:00:23+00:00  btc-updown-15m-1764565200                   0.0
1 2025-12-01 05:00:24+00:00  btc-updown-15m-1764565200                   0.0
2 2025-12-01 05:00:25+00:00  btc-updown-15m-1764565200                   2.0
3 2025-12-01 05:00:26+00:00  btc-updown-15m-1764565200                   1.0
4 2025-12-01 05:00:27+00:00  btc-updown-15m-1764565200                   1.0

   Up_buy_trade_count  Down_buy_trade_size  Up_buy_trade_size  \
0                 1.0                  0.0           2.272726
1                 1.0                  0.0         111.720000
2                 0.0                 19.0           0.000000
3                 2.0                  9.0          10.000000
4                 0.0                 10.0           0.000000

   Down_buy_trade_vwap  Up_buy_trade_vwap  Down_sell_trade_count  \
0                  NaN               0.44                    0.0
1                  NaN               0.45                    0.0
2             0.564737                NaN                    0.0
3             0.580000               0.43                    0.0
4             0.580000                NaN                    0.0

   Up_sell_trade_count  Down_sell_trade_size  Up_sell_trade_size  \
0                  0.0                   0.0                 0.0
1                  0.0                   0.0                 0.0
2                  0.0                   0.0                 0.0
3                  0.0                   0.0                 0.0
4                  0.0                   0.0                 0.0

   Down_sell_trade_vwap  Up_sell_trade_vwap  \
0                   NaN                 NaN
1                   NaN                 NaN
2                   NaN                 NaN
3                   NaN                 NaN
4                   NaN                 NaN

   Down_taker_buy_trade_nominal_value  Up_taker_buy_trade_nominal_value  \
0                                0.00                          0.999999
1                                0.00                         50.274000
2                               10.73                          0.000000
3                                5.22                          4.300000
4                                5.80                          0.000000

   Down_taker_sell_trade_nominal_value  Up_taker_sell_trade_nominal_value
0                                  0.0                                0.0
1                                  0.0                                0.0
2                                  0.0                                0.0
3                                  0.0                                0.0
4                                  0.0                                0.0

In [9]:
df_wide

,timestamp,slug,Down_buy_trade_count,Up_buy_trade_count,Down_buy_trade_size,Up_buy_trade_size,Down_buy_trade_vwap,Up_buy_trade_vwap,Down_sell_trade_count,Up_sell_trade_count,Down_sell_trade_size,Up_sell_trade_size,Down_sell_trade_vwap,Up_sell_trade_vwap,Down_taker_buy_trade_nominal_value,Up_taker_buy_trade_nominal_value,Down_taker_sell_trade_nominal_value,Up_taker_sell_trade_nominal_value
0,2025-12-01 05:00:23+00:00,btc-updown-15m-1764565200,0.0,1.0,0.0,2.272726,NaN,0.44,0.0,0.0,0.00,0.0,NaN,NaN,0.00,0.999999,0.0000,0.0
1,2025-12-01 05:00:24+00:00,btc-updown-15m-1764565200,0.0,1.0,0.0,111.720000,NaN,0.45,0.0,0.0,0.00,0.0,NaN,NaN,0.00,50.274000,0.0000,0.0
2,2025-12-01 05:00:25+00:00,btc-updown-15m-1764565200,2.0,0.0,19.0,0.000000,0.564737,NaN,0.0,0.0,0.00,0.0,NaN,NaN,10.73,0.000000,0.0000,0.0
3,2025-12-01 05:00:26+00:00,btc-updown-15m-1764565200,1.0,2.0,9.0,10.000000,0.580000,0.43,0.0,0.0,0.00,0.0,NaN,NaN,5.22,4.300000,0.0000,0.0
4,2025-12-01 05:00:27+00:00,btc-updown-15m-1764565200,1.0,0.0,10.0,0.000000,0.580000,NaN,0.0,0.0,0.00,0.0,NaN,NaN,5.80,0.000000,0.0000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
779229,2025-12-15 05:00:28+00:00,btc-updown-15m-1765773900,0.0,0.0,0.0,0.000000,NaN,NaN,1.0,0.0,249.98,0.0,0.99,NaN,0.00,0.000000,247.4802,0.0
779230,2025-12-15 05:00:29+00:00,btc-updown-15m-1765773900,0.0,0.0,0.0,0.000000,NaN,NaN,1.0,0.0,443.82,0.0,0.99,NaN,0.00,0.000000,439.3818,0.0
779231,2025-12-15 05:00:36+00:00,btc-updown-15m-1765773900,0.0,0.0,0.0,0.000000,NaN,NaN,1.0,0.0,1.63,0.0,0.99,NaN,0.00,0.000000,1.6137,0.0
779232,2025-12-15 05:00:49+00:00,btc-updown-15m-1765773900,0.0,0.0,0.0,0.000000,NaN,NaN,1.0,0.0,1.38,0.0,0.99,NaN,0.00,0.000000,1.3662,0.0
779233,2025-12-15 05:01:02+00:00,btc-updown-15m-1765773900,0.0,0.0,0.0,0.000000,NaN,NaN,1.0,0.0,119.76,0.0,0.99,NaN,0.00,0.000000,118.5624,0.0

In [6]:
data.shape

(1060114, 59)

In [12]:
import pandas as pd
import numpy as np
from pathlib import Path
import glob
import os

# ==========================================
# 1. 基础路径配置
# ==========================================
BASE_DIR = Path('/Volumes/KIOXIA/Project/lob')
INPUT_DIR = BASE_DIR / 'raw_transactions_only'
OUTPUT_DIR = BASE_DIR / 'advanced_hft_features'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

WEEKS_TO_PROCESS = ['week1', 'week2']

print("🔍 正在构建 Token 映射字典 (asset_id -> Up/Down)...")
mapping_dict = {}
csv_files = glob.glob(str(BASE_DIR / '*' / 'trades_week*.csv'))
for f in csv_files:
    df_meta = pd.read_csv(f, dtype={'token_id': str})
    temp_dict = df_meta.drop_duplicates('token_id').set_index('token_id')['token_name'].to_dict()
    mapping_dict.update(temp_dict)
print(f"   [√] 成功加载 {len(mapping_dict)} 个 Token 映射。")

# ==========================================
# 2. 核心处理函数：重采样 + 因子计算 + 宽表透视
# ==========================================
def process_advanced_features(df_raw, slug):
    if df_raw.empty: return pd.DataFrame()

    df_raw['token_type'] = df_raw['asset_id'].map(mapping_dict)
    df_raw.dropna(subset=['token_type'], inplace=True)
    if df_raw.empty: return pd.DataFrame()

    df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
    df_raw['notional'] = df_raw['price'] * df_raw['size']

    # 基础聚合
    agg_df = df_raw.groupby(['timestamp', 'token_type', 'side']).agg(
        trade_size=('size', 'sum'),
        trade_count=('transaction_hash', 'count'),
        notional=('notional', 'sum')
    ).reset_index()

    # 计算 VWAP (如果有量)
    agg_df['vwap'] = agg_df['notional'] / agg_df['trade_size']
    
    # 组合前缀，用于透视 (例如: Up_BUY)
    agg_df['pivot_key'] = agg_df['token_type'] + '_' + agg_df['side']
    
    val_cols = ['trade_size', 'trade_count', 'notional', 'vwap']
    
    # 透视为宽表
    df_wide = agg_df.pivot(index='timestamp', columns='pivot_key', values=val_cols)
    df_wide.columns = [f"{col[1]}_{col[0]}" for col in df_wide.columns]
    
    # 【非常重要】：对齐到连续的1秒时间网格
    # 因为如果不做这一步，连续10秒没交易，这10秒的行都会直接消失
    full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
    df_wide = df_wide.reindex(full_idx)
    df_wide.index.name = 'timestamp'
    df_wide.reset_index(inplace=True)
    
    # --------------------------------------------------
    # B. 缺失值精确处理 (听你的，去掉繁琐的，精确填0)
    # --------------------------------------------------
    expected_prefixes = ['Up_BUY', 'Up_SELL', 'Down_BUY', 'Down_SELL']
    
    # 1. 确保所有列存在
    for pfx in expected_prefixes:
        for metric in val_cols:
            col_name = f"{pfx}_{metric}"
            if col_name not in df_wide.columns:
                df_wide[col_name] = np.nan

    # 2. 属于“量”的列，没交易就填 0
    zero_fill_metrics = ['trade_size', 'trade_count', 'notional']
    for pfx in expected_prefixes:
        for metric in zero_fill_metrics:
            df_wide[f"{pfx}_{metric}"] = df_wide[f"{pfx}_{metric}"].fillna(0)

    # 3. 属于“价”的列 (VWAP)，没交易就向前填充 (ffill)
    vwap_cols = [f"{pfx}_vwap" for pfx in expected_prefixes]
    df_wide[vwap_cols] = df_wide[vwap_cols].ffill()
    # 如果开头还有 NaN (比如最开始的几秒没交易)，填0或填盘口中间价都可以，这里简单向后填充
    df_wide[vwap_cols] = df_wide[vwap_cols].bfill()

    # --------------------------------------------------
    # C. 计算最终因子：Net_OFI
    # --------------------------------------------------
    bullish_flow = df_wide['Up_BUY_trade_size'] + df_wide['Down_SELL_trade_size']
    bearish_flow = df_wide['Up_SELL_trade_size'] + df_wide['Down_BUY_trade_size']
    
    # 加上 1e-8 防止分母为 0。如果全没交易，OFI 会是 0（中立）
    df_wide['Net_OFI'] = (bullish_flow - bearish_flow) / (bullish_flow + bearish_flow + 1e-8)

    df_wide['slug'] = slug
    return df_wide

# ==========================================
# 3. 执行循环处理
# ==========================================
all_dfs = []
for week in WEEKS_TO_PROCESS:
    print(f"\n🚀 开始提取 {week.upper()} 的高级特征")
    WEEK_INPUT_DIR = INPUT_DIR / week
    WEEK_OUTPUT_DIR = OUTPUT_DIR / week
    WEEK_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    parquet_files = glob.glob(str(WEEK_INPUT_DIR / '*_raw_txs.parquet'))
    
    for file_path in parquet_files:
        slug = os.path.basename(file_path).replace('_raw_txs.parquet', '')
        df_raw = pd.read_parquet(file_path)
        
        df_features = process_advanced_features(df_raw, slug)
        
        if not df_features.empty:
            out_file = WEEK_OUTPUT_DIR / f"{slug}_hft_features.parquet"
            df_features.to_parquet(out_file)
            all_dfs.append(df_features)
            print(f"     [√] 处理完成 -> {slug} (行数: {len(df_features)})")

if all_dfs:
    print("\n🔗 正在拼接最终大总表...")
    df_grand_total = pd.concat(all_dfs, ignore_index=True)
    df_grand_total.sort_values(by=['timestamp', 'slug'], inplace=True)
    df_grand_total.reset_index(drop=True, inplace=True)
    
    grand_output = OUTPUT_DIR / "grand_total_HFT_master.parquet"
    df_grand_total.to_parquet(grand_output)
    print(f"🎉 高频因子大总表生成完毕！保存在: {grand_output}")

🔍 正在构建 Token 映射字典 (asset_id -> Up/Down)...
   [√] 成功加载 2622 个 Token 映射。

🚀 开始提取 WEEK1 的高级特征

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765153800 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1764838800 (行数: 867)
     [√] 处理完成 -> btc-updown-15m-1764656100 (行数: 856)
     [√] 处理完成 -> btc-updown-15m-1765081800 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1764792900 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1764834300 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765107900 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1764567900 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1764745200 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1764603000 (行数: 850)
     [√] 处理完成 -> btc-updown-15m-1765127700 (行数: 858)
     [√] 处理完成 -> btc-updown-15m-1765084500 (行数: 912)
     [√] 处理完成 -> btc-updown-15m-1764810000 (行数: 829)
     [√] 处理完成 -> btc-updown-15m-1764843300 (行数: 819)
     [√] 处理完成 -> btc-updown-15m-1764642600 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1764981900 (行数: 209)
     [√] 处理完成 -> btc-updown-15m-1765103400 (行数: 884)
     [√] 处理完成 -> btc-updown-15m-1764918000 (行数: 884)
     [√] 处理完成 -> btc-updown-15m-1764627300 (行数: 828)
     [√] 处理完成 -> btc-updown-15m-1764869400 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1764675000 (行数: 865)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 处理完成 -> btc-updown-15m-1764882000 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1765010700 (行数: 906)
     [√] 处理完成 -> btc-updown-15m-1764673200 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1765156500 (行数: 853)
     [√] 处理完成 -> btc-updown-15m-1764751500 (行数: 926)
     [√] 处理完成 -> btc-updown-15m-1764620100 (行数: 865)
     [√] 处理完成 -> btc-updown-15m-1764644400 (行数: 853)
     [√] 处理完成 -> btc-updown-15m-1765118700 (行数: 923)
     [√] 处理完成 -> btc-updown-15m-1764845100 (行数: 890)
     [√] 处理完成 -> btc-updown-15m-1764966600 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1764578700 (行数: 557)
     [√] 处理完成 -> btc-updown-15m-1765082700 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1764817200 (行数: 847)
     [√] 处理完成 -> btc-updown-15m-1764946800 (行数: 847)
     [√] 处理完成 -> btc-updown-15m-1765068300 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1764815400 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1765018800 (行数: 892)
     [√] 处理完成 -> btc-updown-15m-1764779400 (行数: 899)
     [√] 处理完成 -> btc-updown-15m-1764792000 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765038600 (行数: 941)
     [√] 处理完成 -> btc-updown-15m-1764973800 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1764784800 (行数: 821)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765107000 (行数: 833)
     [√] 处理完成 -> btc-updown-15m-1764623700 (行数: 862)
     [√] 处理完成 -> btc-updown-15m-1764567000 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1764646200 (行数: 823)
     [√] 处理完成 -> btc-updown-15m-1764671400 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1764603900 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1764753300 (行数: 906)
     [√] 处理完成 -> btc-updown-15m-1765076400 (行数: 894)
     [√] 处理完成 -> btc-updown-15m-1764755100 (行数: 867)
     [√] 处理完成 -> btc-updown-15m-1765014300 (行数: 867)
     [√] 处理完成 -> btc-updown-15m-1764949500 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1764789300 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764625500 (行数: 855)
     [√] 处理完成 -> btc-updown-15m-1764596700 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1764841500 (行数: 866)
     [√] 处理完成 -> btc-updown-15m-1764927900 (行数: 361)
     [√] 处理完成 -> btc-updown-15m-1764681300 (行数: 856)
     [√] 处理完成 -> btc-updown-15m-1765086300 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1764813600 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1765027800 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1764652500 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1765049400 (行数: 868)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764923400 (行数: 411)
     [√] 处理完成 -> btc-updown-15m-1764810900 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1764976500 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1764830700 (行数: 892)
     [√] 处理完成 -> btc-updown-15m-1764595800 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1764918900 (行数: 908)
     [√] 处理完成 -> btc-updown-15m-1764741600 (行数: 895)
     [√] 处理完成 -> btc-updown-15m-1764688500 (行数: 847)
     [√] 处理完成 -> btc-updown-15m-1764938700 (行数: 909)
     [√] 处理完成 -> btc-updown-15m-1764882900 (行数: 900)
     [√] 处理完成 -> btc-updown-15m-1765146600 (行数: 836)
     [√] 处理完成 -> btc-updown-15m-1764675900 (行数: 907)
     [√] 处理完成 -> btc-updown-15m-1764566100 (行数: 858)
     [√] 处理完成 -> btc-updown-15m-1765106100 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1765041300 (行数: 821)
     [√] 处理完成 -> btc-updown-15m-1764670500 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1764814500 (行数: 897)
     [√] 处理完成 -> btc-updown-15m-1765149300 (行数: 837)
     [√] 处理完成 -> btc-updown-15m-1765080000 (行数: 852)
     [√] 处理完成 -> btc-updown-15m-1764972900 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1764778500 (行数: 830)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764590400 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1764597600 (行数: 855)
     [√] 处理完成 -> btc-updown-15m-1764812700 (行数: 867)
     [√] 处理完成 -> btc-updown-15m-1765087200 (行数: 860)
     [√] 处理完成 -> btc-updown-15m-1765152000 (行数: 877)
     [√] 处理完成 -> btc-updown-15m-1765015200 (行数: 902)
     [√] 处理完成 -> btc-updown-15m-1764677700 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765144800 (行数: 850)
     [√] 处理完成 -> btc-updown-15m-1765164600 (行数: 834)
     [√] 处理完成 -> btc-updown-15m-1764657900 (行数: 916)
     [√] 处理完成 -> btc-updown-15m-1765022400 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1764786600 (行数: 832)
     [√] 处理完成 -> btc-updown-15m-1765048500 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1764915300 (行数: 903)
     [√] 处理完成 -> btc-updown-15m-1765125000 (行数: 242)
     [√] 处理完成 -> btc-updown-15m-1765026900 (行数: 859)
     [√] 处理完成 -> btc-updown-15m-1764714600 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764653400 (行数: 902)
     [√] 处理完成 -> btc-updown-15m-1764621900 (行数: 900)
     [√] 处理完成 -> btc-updown-15m-1764771300 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1764987300 (行数: 916)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764919800 (行数: 852)
     [√] 处理完成 -> btc-updown-15m-1764883800 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1764689400 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1764740700 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1764607500 (行数: 877)
     [√] 处理完成 -> btc-updown-15m-1764939600 (行数: 854)
     [√] 处理完成 -> btc-updown-15m-1765072800 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1764811800 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1765093500 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1765079100 (行数: 932)
     [√] 处理完成 -> btc-updown-15m-1764594900 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1764977400 (行数: 919)
     [√] 处理完成 -> btc-updown-15m-1764831600 (行数: 849)
     [√] 处理完成 -> btc-updown-15m-1764768600 (行数: 850)
     [√] 处理完成 -> btc-updown-15m-1764911700 (行数: 830)
     [√] 处理完成 -> btc-updown-15m-1764804600 (行数: 877)
     [√] 处理完成 -> btc-updown-15m-1764619200 (行数: 308)
     [√] 处理完成 -> btc-updown-15m-1764926100 (行数: 620)
     [√] 处理完成 -> btc-updown-15m-1764861300 (行数: 928)
     [√] 处理完成 -> btc-updown-15m-1764748800 (行数: 373)
     [√] 处理完成 -> btc-updown-15m-1764660600 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1765152900 (行数: 876)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 处理完成 -> btc-updown-15m-1764983700 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1764969300 (行数: 901)
     [√] 处理完成 -> btc-updown-15m-1764640800 (行数: 852)
     [√] 处理完成 -> btc-updown-15m-1764657000 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1764985500 (行数: 854)
     [√] 处理完成 -> btc-updown-15m-1764744300 (行数: 905)
     [√] 处理完成 -> btc-updown-15m-1764602100 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1765097100 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1765080900 (行数: 865)
     [√] 处理完成 -> btc-updown-15m-1764964800 (行数: 884)
     [√] 处理完成 -> btc-updown-15m-1764972000 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1764835200 (行数: 391)
     [√] 处理完成 -> btc-updown-15m-1764793800 (行数: 386)
     [√] 处理完成 -> btc-updown-15m-1765102500 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1764674100 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1764868500 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1765085400 (行数: 845)
     [√] 处理完成 -> btc-updown-15m-1764594000 (行数: 835)
     [√] 处理完成 -> btc-updown-15m-1764579600 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1765119600 (行数: 613)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764592200 (行数: 851)
     [√] 处理完成 -> btc-updown-15m-1765069200 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1764816300 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1764898200 (行数: 914)
     [√] 处理完成 -> btc-updown-15m-1765083600 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1765133100 (行数: 912)
     [√] 处理完成 -> btc-updown-15m-1765125900 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1764672300 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1765011600 (行数: 842)
     [√] 处理完成 -> btc-updown-15m-1765157400 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1765026000 (行数: 859)
     [√] 处理完成 -> btc-updown-15m-1764621000 (行数: 901)
     [√] 处理完成 -> btc-updown-15m-1765090800 (行数: 838)
     [√] 处理完成 -> btc-updown-15m-1764783900 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1764825300 (行数: 924)
     [√] 处理完成 -> btc-updown-15m-1764962100 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1764840600 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1764711900 (行数: 848)
     [√] 处理完成 -> btc-updown-15m-1764624600 (行数: 862)
     [√] 处理完成 -> btc-updown-15m-1764995400 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1765116900 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1764612000 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765136700 (行数: 879)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764604800 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1764754200 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1764948600 (行数: 842)
     [√] 处理完成 -> btc-updown-15m-1764731700 (行数: 950)
     [√] 处理完成 -> btc-updown-15m-1764993600 (行数: 855)
     [√] 处理完成 -> btc-updown-15m-1764647100 (行数: 917)
     [√] 处理完成 -> btc-updown-15m-1764829800 (行数: 914)
     [√] 处理完成 -> btc-updown-15m-1765039500 (行数: 849)
     [√] 处理完成 -> btc-updown-15m-1764871200 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1764936000 (行数: 933)
     [√] 处理完成 -> btc-updown-15m-1764609300 (行数: 823)
     [√] 处理完成 -> btc-updown-15m-1765135800 (行数: 933)
     [√] 处理完成 -> btc-updown-15m-1765147500 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1765001700 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1764569700 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1764854100 (行数: 903)
     [√] 处理完成 -> btc-updown-15m-1764582300 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1765109700 (行数: 903)
     [√] 处理完成 -> btc-updown-15m-1764695700 (行数: 824)
     [√] 处理完成 -> btc-updown-15m-1764888300 (行数: 235)
     [√] 处理完成 -> btc-updown-15m-1764801000 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1764852300 (行数: 878)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764584100 (行数: 846)
     [√] 处理完成 -> btc-updown-15m-1764990900 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1765112400 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1764909000 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1764636300 (行数: 918)
     [√] 处理完成 -> btc-updown-15m-1764572400 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1765161900 (行数: 909)
     [√] 处理完成 -> btc-updown-15m-1764878400 (行数: 858)
     [√] 处理完成 -> btc-updown-15m-1765062000 (行数: 852)
     [√] 处理完成 -> btc-updown-15m-1764958500 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1765005300 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1765142100 (行数: 907)
     [√] 处理完成 -> btc-updown-15m-1764634500 (行数: 900)
     [√] 处理完成 -> btc-updown-15m-1764798300 (行数: 145)
     [√] 处理完成 -> btc-updown-15m-1764587700 (行数: 895)
     [√] 处理完成 -> btc-updown-15m-1764850500 (行数: 838)
     [√] 处理完成 -> btc-updown-15m-1764936900 (行数: 838)
     [√] 处理完成 -> btc-updown-15m-1764690300 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1765159200 (行数: 931)
     [√] 处理完成 -> btc-updown-15m-1765009800 (行数: 711)
     [√] 处理完成 -> btc-updown-15m-1764783000 (行数: 853)
     [√] 处理完成 -> btc-updown-15m-1765029600 (行数: 864)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 处理完成 -> btc-updown-15m-1764580500 (行数: 866)
     [√] 处理完成 -> btc-updown-15m-1764857700 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1764576000 (行数: 403)
     [√] 处理完成 -> btc-updown-15m-1764711000 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1765051200 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1765116000 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1764632700 (行数: 820)
     [√] 处理完成 -> btc-updown-15m-1765067400 (行数: 877)
     [√] 处理完成 -> btc-updown-15m-1764612900 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1764896400 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1764951300 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1764801900 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1764844200 (行数: 900)
     [√] 处理完成 -> btc-updown-15m-1764821700 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1764967500 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764990000 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1764909900 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1765161000 (行数: 821)
     [√] 处理完成 -> btc-updown-15m-1764735300 (行数: 877)
     [√] 处理完成 -> btc-updown-15m-1765062900 (行数: 895)
     [√] 处理完成 -> btc-updown-15m-1764929700 (行数: 914)
     [√] 处理完成 -> btc-updown-15m-1764750600 (行数: 60)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764643500 (行数: 849)
     [√] 处理完成 -> btc-updown-15m-1764704700 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1765036800 (行数: 742)
     [√] 处理完成 -> btc-updown-15m-1764997200 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764631800 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1765058400 (行数: 852)
     [√] 处理完成 -> btc-updown-15m-1764932400 (行数: 907)
     [√] 处理完成 -> btc-updown-15m-1764739800 (行数: 884)
     [√] 处理完成 -> btc-updown-15m-1764851400 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1764691200 (行数: 922)
     [√] 处理完成 -> btc-updown-15m-1764937800 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1764803700 (行数: 858)
     [√] 处理完成 -> btc-updown-15m-1765096200 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1764959400 (行数: 866)
     [√] 处理完成 -> btc-updown-15m-1765143000 (行数: 841)
     [√] 处理完成 -> btc-updown-15m-1764799200 (行数: 830)
     [√] 处理完成 -> btc-updown-15m-1764828000 (行数: 846)
     [√] 处理完成 -> btc-updown-15m-1764717300 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764635400 (行数: 867)
     [√] 处理完成 -> btc-updown-15m-1764984600 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1764633600 (行数: 842)
     [√] 处理完成 -> btc-updown-15m-1765050300 (行数: 896)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764710100 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1764661500 (行数: 909)
     [√] 处理完成 -> btc-updown-15m-1765066500 (行数: 860)
     [√] 处理完成 -> btc-updown-15m-1764613800 (行数: 247)
     [√] 处理完成 -> btc-updown-15m-1765158300 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1764805500 (行数: 897)
     [√] 处理完成 -> btc-updown-15m-1764769500 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764581400 (行数: 889)
     [√] 处理完成 -> btc-updown-15m-1764963900 (行数: 862)
     [√] 处理完成 -> btc-updown-15m-1765028700 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1764782100 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1765160100 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1765063800 (行数: 842)
     [√] 处理完成 -> btc-updown-15m-1765132200 (行数: 832)
     [√] 处理完成 -> btc-updown-15m-1764892800 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1764899100 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1764659700 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1764585900 (行数: 902)
     [√] 处理完成 -> btc-updown-15m-1764593100 (行数: 923)
     [√] 处理完成 -> btc-updown-15m-1764855900 (行数: 839)
     [√] 处理完成 -> btc-updown-15m-1764738900 (行数: 895)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764875700 (行数: 918)
     [√] 处理完成 -> btc-updown-15m-1765134000 (行数: 811)
     [√] 处理完成 -> btc-updown-15m-1764630900 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1764996300 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1764705600 (行数: 895)
     [√] 处理完成 -> btc-updown-15m-1765167300 (行数: 936)
     [√] 处理完成 -> btc-updown-15m-1764994500 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1765117800 (行数: 846)
     [√] 处理完成 -> btc-updown-15m-1765165500 (行数: 906)
     [√] 处理完成 -> btc-updown-15m-1765137600 (行数: 844)
     [√] 处理完成 -> btc-updown-15m-1765008000 (行数: 392)
     [√] 处理完成 -> btc-updown-15m-1764963000 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1764870300 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1765130400 (行数: 833)
     [√] 处理完成 -> btc-updown-15m-1765143900 (行数: 899)
     [√] 处理完成 -> btc-updown-15m-1764828900 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1764978300 (行数: 658)
     [√] 处理完成 -> btc-updown-15m-1765163700 (行数: 910)
     [√] 处理完成 -> btc-updown-15m-1764992700 (行数: 903)
     [√] 处理完成 -> btc-updown-15m-1764855000 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1764583200 (行数: 894)
     [√] 处理完成 -> btc-updown-15m-1764807300 (行数: 884)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764738000 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1764889200 (行数: 924)
     [√] 处理完成 -> btc-updown-15m-1765092600 (行数: 877)
     [√] 处理完成 -> btc-updown-15m-1765078200 (行数: 838)
     [√] 处理完成 -> btc-updown-15m-1765134900 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1764606600 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1764630000 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1764713700 (行数: 826)
     [√] 处理完成 -> btc-updown-15m-1764715500 (行数: 818)
     [√] 处理完成 -> btc-updown-15m-1764637200 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1764908100 (行数: 847)
     [√] 处理完成 -> btc-updown-15m-1764991800 (行数: 843)
     [√] 处理完成 -> btc-updown-15m-1764766800 (行数: 918)
     [√] 处理完成 -> btc-updown-15m-1765055700 (行数: 851)
     [√] 处理完成 -> btc-updown-15m-1764665100 (行数: 739)
     [√] 处理完成 -> btc-updown-15m-1764800100 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1765094400 (行数: 400)
     [√] 处理完成 -> btc-updown-15m-1764787500 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1764853200 (行数: 908)
     [√] 处理完成 -> btc-updown-15m-1764585000 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1764941400 (行数: 825)
     [√] 处理完成 -> btc-updown-15m-1764781200 (行数: 842)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765114200 (行数: 901)
     [√] 处理完成 -> btc-updown-15m-1765053000 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1765045800 (行数: 831)
     [√] 处理完成 -> btc-updown-15m-1764776700 (行数: 911)
     [√] 处理完成 -> btc-updown-15m-1764574200 (行数: 847)
     [√] 处理完成 -> btc-updown-15m-1764894600 (行数: 856)
     [√] 处理完成 -> btc-updown-15m-1764725400 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1764756900 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765065600 (行数: 906)
     [√] 处理完成 -> btc-updown-15m-1765140300 (行数: 839)
     [√] 处理完成 -> btc-updown-15m-1764723600 (行数: 923)
     [√] 处理完成 -> btc-updown-15m-1765007100 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1764703800 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1764599400 (行数: 832)
     [√] 处理完成 -> btc-updown-15m-1764692100 (行数: 839)
     [√] 处理完成 -> btc-updown-15m-1764873900 (行数: 914)
     [√] 处理完成 -> btc-updown-15m-1764684900 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764679500 (行数: 897)
     [√] 处理完成 -> btc-updown-15m-1764881100 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1765070100 (行数: 887)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764982800 (行数: 889)
     [√] 处理完成 -> btc-updown-15m-1765046700 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1764775800 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1764706500 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1764788400 (行数: 912)
     [√] 处理完成 -> btc-updown-15m-1764641700 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1764910800 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1764989100 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1764680400 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1764930600 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1764687600 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1764945900 (行数: 716)
     [√] 处理完成 -> btc-updown-15m-1764953100 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1764823500 (行数: 910)
     [√] 处理完成 -> btc-updown-15m-1764965700 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1764846000 (行数: 910)
     [√] 处理完成 -> btc-updown-15m-1765077300 (行数: 900)
     [√] 处理完成 -> btc-updown-15m-1764752400 (行数: 858)
     [√] 处理完成 -> btc-updown-15m-1764737100 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1764808200 (行数: 883)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 处理完成 -> btc-updown-15m-1764720900 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765075500 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765089900 (行数: 146)
     [√] 处理完成 -> btc-updown-15m-1764645300 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1764791100 (行数: 856)
     [√] 处理完成 -> btc-updown-15m-1764865800 (行数: 862)
     [√] 处理完成 -> btc-updown-15m-1764684000 (行数: 860)
     [√] 处理完成 -> btc-updown-15m-1764934200 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1764873000 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764669600 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1764682200 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1764842400 (行数: 926)
     [√] 处理完成 -> btc-updown-15m-1764960300 (行数: 897)
     [√] 处理完成 -> btc-updown-15m-1764718200 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1764827100 (行数: 918)
     [√] 处理完成 -> btc-updown-15m-1764649800 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764626400 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1765053900 (行数: 930)
     [√] 处理完成 -> btc-updown-15m-1764733500 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1765073700 (行数: 914)
     [√] 处理完成 -> btc-updown-15m-1764610200 (行数: 874)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 处理完成 -> btc-updown-15m-1764756000 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1764866700 (行数: 924)
     [√] 处理完成 -> btc-updown-15m-1764945000 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1765168200 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1764846900 (行数: 838)
     [√] 处理完成 -> btc-updown-15m-1764570600 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1765110600 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1765060200 (行数: 903)
     [√] 处理完成 -> btc-updown-15m-1764720000 (行数: 897)
     [√] 处理完成 -> btc-updown-15m-1765145700 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1764676800 (行数: 842)
     [√] 处理完成 -> btc-updown-15m-1764727200 (行数: 825)
     [√] 处理完成 -> btc-updown-15m-1764818100 (行数: 884)
     [√] 处理完成 -> btc-updown-15m-1765003500 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1764943200 (行数: 899)
     [√] 处理完成 -> btc-updown-15m-1764864900 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1764872100 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1764693900 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1765042200 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1764858600 (行数: 881)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764702000 (行数: 571)
     [√] 处理完成 -> btc-updown-15m-1765021500 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1764588600 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1765044000 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765151100 (行数: 826)
     [√] 处理完成 -> btc-updown-15m-1765129500 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1764668700 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1764961200 (行数: 810)
     [√] 处理完成 -> btc-updown-15m-1764648900 (行数: 838)
     [√] 处理完成 -> btc-updown-15m-1764772200 (行数: 924)
     [√] 处理完成 -> btc-updown-15m-1764622800 (行数: 865)
     [√] 处理完成 -> btc-updown-15m-1765057500 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1765019700 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1764944100 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1764867600 (行数: 832)
     [√] 处理完成 -> btc-updown-15m-1764629100 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1764916200 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1764847800 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1764785700 (行数: 820)
     [√] 处理完成 -> btc-updown-15m-1764860400 (行数: 817)
     [√] 处理完成 -> btc-updown-15m-1764942300 (行数: 909)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765071900 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764819000 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1764726300 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1764968400 (行数: 846)
     [√] 处理完成 -> btc-updown-15m-1764774000 (行数: 851)
     [√] 处理完成 -> btc-updown-15m-1765052100 (行数: 835)
     [√] 处理完成 -> btc-updown-15m-1764777600 (行数: 858)
     [√] 处理完成 -> btc-updown-15m-1765044900 (行数: 918)
     [√] 处理完成 -> btc-updown-15m-1765064700 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1764757800 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1764724500 (行数: 847)
     [√] 处理完成 -> btc-updown-15m-1764862200 (行数: 817)
     [√] 处理完成 -> btc-updown-15m-1764940500 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1764648000 (行数: 907)
     [√] 处理完成 -> btc-updown-15m-1764780300 (行数: 828)
     [√] 处理完成 -> btc-updown-15m-1764912600 (行数: 904)
     [√] 处理完成 -> btc-updown-15m-1764914400 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1764971100 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1764947700 (行数: 895)
     [√] 处理完成 -> btc-updown-15m-1764693000 (行数: 853)
     [√] 处理完成 -> btc-updown-15m-1764685800 (行数: 877)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764864000 (行数: 853)
     [√] 处理完成 -> btc-updown-15m-1764722700 (行数: 828)
     [√] 处理完成 -> btc-updown-15m-1765088100 (行数: 734)
     [√] 处理完成 -> btc-updown-15m-1765141200 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1764986400 (行数: 894)
     [√] 处理完成 -> btc-updown-15m-1764770400 (行数: 833)
     [√] 处理完成 -> btc-updown-15m-1764598500 (行数: 930)
     [√] 处理完成 -> btc-updown-15m-1764702900 (行数: 842)
     [√] 处理完成 -> btc-updown-15m-1764877500 (行数: 925)
     [√] 处理完成 -> btc-updown-15m-1765071000 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1764819900 (行数: 932)
     [√] 处理完成 -> btc-updown-15m-1764707400 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1765023300 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1764839700 (行数: 907)
     [√] 处理完成 -> btc-updown-15m-1764774900 (行数: 862)
     [√] 处理完成 -> btc-updown-15m-1765047600 (行数: 858)
     [√] 处理完成 -> btc-updown-15m-1765040400 (行数: 929)
     [√] 处理完成 -> btc-updown-15m-1765025100 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1764721800 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1765126800 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1765148400 (行数: 892)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 处理完成 -> btc-updown-15m-1764686700 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1764591300 (行数: 899)
     [√] 处理完成 -> btc-updown-15m-1765098000 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1764732600 (行数: 851)
     [√] 处理完成 -> btc-updown-15m-1765016100 (行数: 851)
     [√] 处理完成 -> btc-updown-15m-1764611100 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1764760500 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1764712800 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1765059300 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1764904500 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1764719100 (行数: 866)
     [√] 处理完成 -> btc-updown-15m-1764826200 (行数: 846)
     [√] 处理完成 -> btc-updown-15m-1764957600 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1764933300 (行数: 848)
     [√] 处理完成 -> btc-updown-15m-1764683100 (行数: 919)
     [√] 处理完成 -> btc-updown-15m-1764935100 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1764950400 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1764790200 (行数: 861)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764902700 (行数: 231)
     [√] 处理完成 -> btc-updown-15m-1764565200 (行数: 908)
     [√] 处理完成 -> btc-updown-15m-1765054800 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1764767700 (行数: 855)
     [√] 处理完成 -> btc-updown-15m-1765105200 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1764747900 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765074600 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1764734400 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1764954900 (行数: 907)
     [√] 处理完成 -> btc-updown-15m-1764696600 (行数: 30)
     [√] 处理完成 -> btc-updown-15m-1764639900 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1764974700 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1764832500 (行数: 913)
     [√] 处理完成 -> btc-updown-15m-1765035000 (行数: 944)
     [√] 处理完成 -> btc-updown-15m-1765002600 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1764897300 (行数: 877)
     [√] 处理完成 -> btc-updown-15m-1764743400 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1765061100 (行数: 865)
     [√] 处理完成 -> btc-updown-15m-1765004400 (行数: 901)
     [√] 处理完成 -> btc-updown-15m-1764890100 (行数: 829)
     [√] 处理完成 -> btc-updown-15m-1765162800 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1764571500 (行数: 909)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765033200 (行数: 843)
     [√] 处理完成 -> btc-updown-15m-1764650700 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1765111500 (行数: 860)
     [√] 处理完成 -> btc-updown-15m-1765169100 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764998100 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1764921600 (行数: 389)
     [√] 处理完成 -> btc-updown-15m-1764758700 (行数: 929)
     [√] 处理完成 -> btc-updown-15m-1765139400 (行数: 895)
     [√] 处理完成 -> btc-updown-15m-1764678600 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1764658800 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1764709200 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1765031400 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1764573300 (行数: 903)
     [√] 处理完成 -> btc-updown-15m-1765113300 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1764747000 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1764879300 (行数: 895)
     [√] 处理完成 -> btc-updown-15m-1764601200 (行数: 849)
     [√] 处理完成 -> btc-updown-15m-1765006200 (行数: 835)
     [√] 处理完成 -> btc-updown-15m-1764893700 (行数: 849)
     [√] 处理完成 -> btc-updown-15m-1764895500 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1765098900 (行数: 758)
     [√] 处理完成 -> btc-updown-15m-1764848700 (行数: 894)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 处理完成 -> btc-updown-15m-1765115100 (行数: 859)
     [√] 处理完成 -> btc-updown-15m-1764575100 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1764654300 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1764874800 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1764736200 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1764809100 (行数: 927)
     [√] 处理完成 -> btc-updown-15m-1765012500 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1765154700 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1764667800 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1764764100 (行数: 894)
     [√] 处理完成 -> btc-updown-15m-1764822600 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1764608400 (行数: 939)
     [√] 处理完成 -> btc-updown-15m-1764802800 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764952200 (行数: 853)
     [√] 处理完成 -> btc-updown-15m-1764954000 (行数: 842)
     [√] 处理完成 -> btc-updown-15m-1764931500 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1764988200 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764906300 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1764639000 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1764824400 (行数: 854)
     [√] 处理完成 -> btc-updown-15m-1765101600 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1764762300 (行数: 864)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765035900 (行数: 975)
     [√] 处理完成 -> btc-updown-15m-1764880200 (行数: 834)
     [√] 处理完成 -> btc-updown-15m-1765030500 (行数: 902)
     [√] 处理完成 -> btc-updown-15m-1764746100 (行数: 890)
     [√] 处理完成 -> btc-updown-15m-1764600300 (行数: 915)
     [√] 处理完成 -> btc-updown-15m-1764928800 (行数: 835)
     [√] 处理完成 -> btc-updown-15m-1765138500 (行数: 894)
     [√] 处理完成 -> btc-updown-15m-1764837000 (行数: 196)
     [√] 处理完成 -> btc-updown-15m-1764708300 (行数: 909)
     [√] 处理完成 -> btc-updown-15m-1764820800 (行数: 829)
     [√] 处理完成 -> btc-updown-15m-1764970200 (行数: 845)
     [√] 处理完成 -> btc-updown-15m-1764913500 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1764863100 (行数: 923)
     [√] 处理完成 -> btc-updown-15m-1764924300 (行数: 195)
     [√] 处理完成 -> btc-updown-15m-1764806400 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1764662400 (行数: 373)
     [√] 处理完成 -> btc-updown-15m-1765017900 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1765099800 (行数: 919)
     [√] 处理完成 -> btc-updown-15m-1765037700 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1764655200 (行数: 905)
     [√] 处理完成 -> btc-updown-15m-1764849600 (行数: 906)
     [√] 处理完成 -> btc-updown-15m-1764999900 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1764586800 (行数: 837)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764891900 (行数: 906)
     [√] 处理完成 -> btc-updown-15m-1765013400 (行数: 899)
     [√] 处理完成 -> btc-updown-15m-1764666900 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1765155600 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1765131300 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1764765000 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765024200 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1764763200 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765100700 (行数: 808)
     [√] 处理完成 -> btc-updown-15m-1764876600 (行数: 822)
     [√] 处理完成 -> btc-updown-15m-1764856800 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1764638100 (行数: 850)
     [√] 处理完成 -> btc-updown-15m-1764907200 (行数: 906)
     [√] 处理完成 -> btc-updown-15m-1764568800 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1765108800 (行数: 895)
     [√] 处理完成 -> btc-updown-15m-1764905400 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1764694800 (行数: 922)
     [√] 处理完成 -> btc-updown-15m-1765128600 (行数: 894)
     [√] 处理完成 -> btc-updown-15m-1764956700 (行数: 865)
     [√] 处理完成 -> btc-updown-15m-1765017000 (行数: 867)
     [√] 处理完成 -> btc-updown-15m-1765000800 (行数: 867)
     [√] 处理完成 -> btc-updown-15m-1765150200 (行数: 902)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765166400 (行数: 856)
     [√] 处理完成 -> btc-updown-15m-1765020600 (行数: 845)
     [√] 处理完成 -> btc-updown-15m-1764761400 (行数: 907)
     [√] 处理完成 -> btc-updown-15m-1764589500 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1764859500 (行数: 835)
     [√] 处理完成 -> btc-updown-15m-1765043100 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1765104300 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1764903600 (行数: 897)
     [√] 处理完成 -> btc-updown-15m-1764837900 (行数: 904)
     [√] 处理完成 -> btc-updown-15m-1765034100 (行数: 828)
     [√] 处理完成 -> btc-updown-15m-1764605700 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1764742500 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1765091700 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1764955800 (行数: 829)
     [√] 处理完成 -> btc-updown-15m-1764975600 (行数: 860)
     [√] 处理完成 -> btc-updown-15m-1764833400 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1764999000 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1764628200 (行数: 900)
     [√] 处理完成 -> btc-updown-15m-1764917100 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1764920700 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1764759600 (行数: 849)
     [√] 处理完成 -> btc-updown-15m-1764666000 (行数: 829)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1764891000 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1764765900 (行数: 895)
     [√] 处理完成 -> btc-updown-15m-1765056600 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1764773100 (行数: 822)
     [√] 处理完成 -> btc-updown-15m-1764651600 (行数: 884)
     [√] 处理完成 -> btc-updown-15m-1764716400 (行数: 867)
     [√] 处理完成 -> btc-updown-15m-1765032300 (行数: 959)

🚀 开始提取 WEEK2 的高级特征
     [√] 处理完成 -> btc-updown-15m-1765512900 (行数: 344)
     [√] 处理完成 -> btc-updown-15m-1765763100 (行数: 895)
     [√] 处理完成 -> btc-updown-15m-1765323000 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1765641600 (行数: 822)
     [√] 处理完成 -> btc-updown-15m-1765706400 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1765173600 (行数: 852)
     [√] 处理完成 -> btc-updown-15m-1765532700 (行数: 859)
     [√] 处理完成 -> btc-updown-15m-1765495800 (行数: 731)
     [√] 处理完成 -> btc-updown-15m-1765749600 (行数: 839)
     [√] 处理完成 -> btc-updown-15m-1765185300 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765269900 (行数: 889)
     [√] 处理完成 -> btc-updown-15m-1765338300 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1765458000 (行数: 904)
     [√] 处理完成 -> btc-updown-15m-1765590300 (行数: 840)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765189800 (行数: 877)
     [√] 处理完成 -> btc-updown-15m-1765376100 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1765534500 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1765230300 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1765175400 (行数: 860)
     [√] 处理完成 -> btc-updown-15m-1765254600 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1765720800 (行数: 819)
     [√] 处理完成 -> btc-updown-15m-1765737000 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1765170900 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1765543500 (行数: 854)
     [√] 处理完成 -> btc-updown-15m-1765364400 (行数: 917)
     [√] 处理完成 -> btc-updown-15m-1765756800 (行数: 937)
     [√] 处理完成 -> btc-updown-15m-1765689300 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1765531800 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1765215000 (行数: 917)
     [√] 处理完成 -> btc-updown-15m-1765655100 (行数: 860)
     [√] 处理完成 -> btc-updown-15m-1765653300 (行数: 890)
     [√] 处理完成 -> btc-updown-15m-1765517400 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1765213200 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1765342800 (行数: 860)
     [√] 处理完成 -> btc-updown-15m-1765362600 (行数: 896)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765241100 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1765692000 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1765684800 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1765679400 (行数: 770)
     [√] 处理完成 -> btc-updown-15m-1765429200 (行数: 847)
     [√] 处理完成 -> btc-updown-15m-1765349100 (行数: 903)
     [√] 处理完成 -> btc-updown-15m-1765269000 (行数: 907)
     [√] 处理完成 -> btc-updown-15m-1765628100 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1765509300 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1765458900 (行数: 866)
     [√] 处理完成 -> btc-updown-15m-1765759500 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1765319400 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1765401300 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1765737900 (行数: 839)
     [√] 处理完成 -> btc-updown-15m-1765547100 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1765651500 (行数: 828)
     [√] 处理完成 -> btc-updown-15m-1765211400 (行数: 932)
     [√] 处理完成 -> btc-updown-15m-1765504800 (行数: 845)
     [√] 处理完成 -> btc-updown-15m-1765298700 (行数: 32)
     [√] 处理完成 -> btc-updown-15m-1765323900 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1765366200 (行数: 818)
     [√] 处理完成 -> btc-updown-15m-1765463400 (行数: 914)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765697400 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765645200 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1765467900 (行数: 858)
     [√] 处理完成 -> btc-updown-15m-1765536300 (行数: 867)
     [√] 处理完成 -> btc-updown-15m-1765177200 (行数: 859)
     [√] 处理完成 -> btc-updown-15m-1765181700 (行数: 444)
     [√] 处理完成 -> btc-updown-15m-1765692900 (行数: 825)
     [√] 处理完成 -> btc-updown-15m-1765408500 (行数: 853)
     [√] 处理完成 -> btc-updown-15m-1765595700 (行数: 822)
     [√] 处理完成 -> btc-updown-15m-1765439100 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1765170000 (行数: 810)
     [√] 处理完成 -> btc-updown-15m-1765733400 (行数: 912)
     [√] 处理完成 -> btc-updown-15m-1765372500 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1765235700 (行数: 856)
     [√] 处理完成 -> btc-updown-15m-1765215900 (行数: 808)
     [√] 处理完成 -> btc-updown-15m-1765432800 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1765377900 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1765188000 (行数: 931)
     [√] 处理完成 -> btc-updown-15m-1765210500 (行数: 852)
     [√] 处理完成 -> btc-updown-15m-1765436400 (行数: 897)
     [√] 处理完成 -> btc-updown-15m-1765629000 (行数: 920)
     [√] 处理完成 -> btc-updown-15m-1765282500 (行数: 618)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765459800 (行数: 846)
     [√] 处理完成 -> btc-updown-15m-1765268100 (行数: 345)
     [√] 处理完成 -> btc-updown-15m-1765492200 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1765318500 (行数: 836)
     [√] 处理完成 -> btc-updown-15m-1765696500 (行数: 846)
     [√] 处理完成 -> btc-updown-15m-1765455300 (行数: 844)
     [√] 处理完成 -> btc-updown-15m-1765217700 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765462500 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1765726200 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1765409400 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1765383300 (行数: 892)
     [√] 处理完成 -> btc-updown-15m-1765693800 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765204200 (行数: 937)
     [√] 处理完成 -> btc-updown-15m-1765644300 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1765327500 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1765176300 (行数: 893)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765311300 (行数: 855)
     [√] 处理完成 -> btc-updown-15m-1765537200 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765530000 (行数: 877)
     [√] 处理完成 -> btc-updown-15m-1765373400 (行数: 846)
     [√] 处理完成 -> btc-updown-15m-1765732500 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765506600 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765648800 (行数: 865)
     [√] 处理完成 -> btc-updown-15m-1765668600 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1765385100 (行数: 889)
     [√] 处理完成 -> btc-updown-15m-1765748700 (行数: 845)
     [√] 处理完成 -> btc-updown-15m-1765308600 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1765561500 (行数: 678)
     [√] 处理完成 -> btc-updown-15m-1765640700 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765322100 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1765200600 (行数: 899)
     [√] 处理完成 -> btc-updown-15m-1765513800 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1765346400 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765533600 (行数: 860)
     [√] 处理完成 -> btc-updown-15m-1765172700 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1765174500 (行数: 866)
     [√] 处理完成 -> btc-updown-15m-1765736100 (行数: 887)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765360800 (行数: 938)
     [√] 处理完成 -> btc-updown-15m-1765377000 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1765188900 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1765231200 (行数: 827)
     [√] 处理完成 -> btc-updown-15m-1765535400 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1765591200 (行数: 848)
     [√] 处理完成 -> btc-updown-15m-1765629900 (行数: 830)
     [√] 处理完成 -> btc-updown-15m-1765339200 (行数: 830)
     [√] 处理完成 -> btc-updown-15m-1765381500 (行数: 833)
     [√] 处理完成 -> btc-updown-15m-1765686600 (行数: 884)
     [√] 处理完成 -> btc-updown-15m-1765530900 (行数: 805)
     [√] 处理完成 -> btc-updown-15m-1765171800 (行数: 923)
     [√] 处理完成 -> btc-updown-15m-1765724400 (行数: 819)
     [√] 处理完成 -> btc-updown-15m-1765214100 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1765678500 (行数: 923)
     [√] 处理完成 -> btc-updown-15m-1765238400 (行数: 818)
     [√] 处理完成 -> btc-updown-15m-1765709100 (行数: 925)
     [√] 处理完成 -> btc-updown-15m-1765428300 (行数: 851)
     [√] 处理完成 -> btc-updown-15m-1765598400 (行数: 883)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765451700 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1765212300 (行数: 808)
     [√] 处理完成 -> btc-updown-15m-1765516500 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1765722600 (行数: 805)
     [√] 处理完成 -> btc-updown-15m-1765601100 (行数: 895)
     [√] 处理完成 -> btc-updown-15m-1765639800 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1765581300 (行数: 845)
     [√] 处理完成 -> btc-updown-15m-1765449000 (行数: 897)
     [√] 处理完成 -> btc-updown-15m-1765329300 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1765278900 (行数: 838)
     [√] 处理完成 -> btc-updown-15m-1765391400 (行数: 617)
     [√] 处理完成 -> btc-updown-15m-1765245600 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1765604700 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1765221300 (行数: 936)
     [√] 处理完成 -> btc-updown-15m-1765198800 (行数: 815)
     [√] 处理完成 -> btc-updown-15m-1765367100 (行数: 924)
     [√] 处理完成 -> btc-updown-15m-1765324800 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765332000 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1765650600 (行数: 912)
     [√] 处理完成 -> btc-updown-15m-1765571400 (行数: 822)
     [√] 处理完成 -> btc-updown-15m-1765764900 (行数: 897)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765635300 (行数: 860)
     [√] 处理完成 -> btc-updown-15m-1765503900 (行数: 228)
     [√] 处理完成 -> btc-updown-15m-1765772100 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1765546200 (行数: 899)
     [√] 处理完成 -> btc-updown-15m-1765194300 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1765758600 (行数: 837)
     [√] 处理完成 -> btc-updown-15m-1765760400 (行数: 909)
     [√] 处理完成 -> btc-updown-15m-1765588500 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1765575900 (行数: 907)
     [√] 处理完成 -> btc-updown-15m-1765250100 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1765476000 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1765611000 (行数: 899)
     [√] 处理完成 -> btc-updown-15m-1765480500 (行数: 521)
     [√] 处理完成 -> btc-updown-15m-1765683000 (行数: 904)
     [√] 处理完成 -> btc-updown-15m-1765228500 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765358100 (行数: 822)
     [√] 处理完成 -> btc-updown-15m-1765438200 (行数: 889)
     [√] 处理完成 -> btc-updown-15m-1765719000 (行数: 854)
     [√] 处理完成 -> btc-updown-15m-1765296000 (行数: 852)
     [√] 处理完成 -> btc-updown-15m-1765487700 (行数: 849)
     [√] 处理完成 -> btc-updown-15m-1765395900 (行数: 835)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765698300 (行数: 853)
     [√] 处理完成 -> btc-updown-15m-1765747800 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1765552500 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1765415700 (行数: 941)
     [√] 处理完成 -> btc-updown-15m-1765257300 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1765767600 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1765332900 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1765289700 (行数: 819)
     [√] 处理完成 -> btc-updown-15m-1765764000 (行数: 824)
     [√] 处理完成 -> btc-updown-15m-1765255500 (行数: 897)
     [√] 处理完成 -> btc-updown-15m-1765484100 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1765449900 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1765292400 (行数: 847)
     [√] 处理完成 -> btc-updown-15m-1765518300 (行数: 905)
     [√] 处理完成 -> btc-updown-15m-1765278000 (行数: 915)
     [√] 处理完成 -> btc-updown-15m-1765482300 (行数: 813)
     [√] 处理完成 -> btc-updown-15m-1765556100 (行数: 848)
     [√] 处理完成 -> btc-updown-15m-1765253700 (行数: 858)
     [√] 处理完成 -> btc-updown-15m-1765410300 (行数: 926)
     [√] 处理完成 -> btc-updown-15m-1765762200 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1765426500 (行数: 872)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765296900 (行数: 924)
     [√] 处理完成 -> btc-updown-15m-1765348200 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1765395000 (行数: 909)
     [√] 处理完成 -> btc-updown-15m-1765363500 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1765520100 (行数: 915)
     [√] 处理完成 -> btc-updown-15m-1765544400 (行数: 901)
     [√] 处理完成 -> btc-updown-15m-1765240200 (行数: 856)
     [√] 处理完成 -> btc-updown-15m-1765423800 (行数: 826)
     [√] 处理完成 -> btc-updown-15m-1765573200 (行数: 838)
     [√] 处理完成 -> btc-updown-15m-1765631700 (行数: 855)
     [√] 处理完成 -> btc-updown-15m-1765337400 (行数: 914)
     [√] 处理完成 -> btc-updown-15m-1765654200 (行数: 816)
     [√] 处理完成 -> btc-updown-15m-1765575000 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1765542600 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765611900 (行数: 854)
     [√] 处理完成 -> btc-updown-15m-1765476900 (行数: 134)
     [√] 处理完成 -> btc-updown-15m-1765393200 (行数: 902)
     [√] 处理完成 -> btc-updown-15m-1765739700 (行数: 877)
     [√] 处理完成 -> btc-updown-15m-1765190700 (行数: 841)
     [√] 处理完成 -> btc-updown-15m-1765683900 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1765719900 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1765380600 (行数: 927)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765485000 (行数: 846)
     [√] 处理完成 -> btc-updown-15m-1765687500 (行数: 918)
     [√] 处理完成 -> btc-updown-15m-1765773900 (行数: 930)
     [√] 处理完成 -> btc-updown-15m-1765502100 (行数: 248)
     [√] 处理完成 -> btc-updown-15m-1765333800 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765666800 (行数: 854)
     [√] 处理完成 -> btc-updown-15m-1765540800 (行数: 826)
     [√] 处理完成 -> btc-updown-15m-1765557000 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1765411200 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1765427400 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765201500 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1765519200 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1765638000 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1765483200 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1765309500 (行数: 865)
     [√] 处理完成 -> btc-updown-15m-1765723500 (行数: 914)
     [√] 处理完成 -> btc-updown-15m-1765746000 (行数: 892)
     [√] 处理完成 -> btc-updown-15m-1765521000 (行数: 848)
     [√] 处理完成 -> btc-updown-15m-1765600200 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1765572300 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1765422900 (行数: 901)
     [√] 处理完成 -> btc-updown-15m-1765297800 (行数: 810)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 处理完成 -> btc-updown-15m-1765708200 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1765394100 (行数: 832)
     [√] 处理完成 -> btc-updown-15m-1765379700 (行数: 816)
     [√] 处理完成 -> btc-updown-15m-1765191600 (行数: 912)
     [√] 处理完成 -> btc-updown-15m-1765418400 (行数: 856)
     [√] 处理完成 -> btc-updown-15m-1765392300 (行数: 884)
     [√] 处理完成 -> btc-updown-15m-1765359900 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1765271700 (行数: 820)
     [√] 处理完成 -> btc-updown-15m-1765336500 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1765574100 (行数: 853)
     [√] 处理完成 -> btc-updown-15m-1765251900 (行数: 931)
     [√] 处理完成 -> btc-updown-15m-1765742400 (行数: 838)
     [√] 处理完成 -> btc-updown-15m-1765605600 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1765727100 (行数: 884)
     [√] 处理完成 -> btc-updown-15m-1765244700 (行数: 926)
     [√] 处理完成 -> btc-updown-15m-1765577700 (行数: 926)
     [√] 处理完成 -> btc-updown-15m-1765279800 (行数: 902)
     [√] 处理完成 -> btc-updown-15m-1765638900 (行数: 908)
     [√] 处理完成 -> btc-updown-15m-1765448100 (行数: 819)
     [√] 处理完成 -> btc-updown-15m-1765485900 (行数: 817)
     [√] 处理完成 -> btc-updown-15m-1765397700 (行数: 860)
     [√] 处理完成 -> btc-updown-15m-1765493100 (行数: 35)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765195200 (行数: 818)
     [√] 处理完成 -> btc-updown-15m-1765765800 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1765773000 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1765275300 (行数: 923)
     [√] 处理完成 -> btc-updown-15m-1765570500 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1765229400 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1765682100 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765384200 (行数: 824)
     [√] 处理完成 -> btc-updown-15m-1765481400 (行数: 856)
     [√] 处理完成 -> btc-updown-15m-1765669500 (行数: 901)
     [√] 处理完成 -> btc-updown-15m-1765718100 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1765359000 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765203300 (行数: 827)
     [√] 处理完成 -> btc-updown-15m-1765507500 (行数: 839)
     [√] 处理完成 -> btc-updown-15m-1765610100 (行数: 855)
     [√] 处理完成 -> btc-updown-15m-1765251000 (行数: 866)
     [√] 处理完成 -> btc-updown-15m-1765553400 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1765306800 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765699200 (行数: 404)
     [√] 处理完成 -> btc-updown-15m-1765746900 (行数: 852)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765766700 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765205100 (行数: 819)
     [√] 处理完成 -> btc-updown-15m-1765326600 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1765422000 (行数: 854)
     [√] 处理完成 -> btc-updown-15m-1765290600 (行数: 901)
     [√] 处理完成 -> btc-updown-15m-1765186200 (行数: 897)
     [√] 处理完成 -> btc-updown-15m-1765554300 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1765412100 (行数: 833)
     [√] 处理完成 -> btc-updown-15m-1765316700 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1765398600 (行数: 912)
     [√] 处理完成 -> btc-updown-15m-1765266300 (行数: 914)
     [√] 处理完成 -> btc-updown-15m-1765424700 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765705500 (行数: 921)
     [√] 处理完成 -> btc-updown-15m-1765627200 (行数: 858)
     [√] 处理完成 -> btc-updown-15m-1765620000 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1765450800 (行数: 892)
     [√] 处理完成 -> btc-updown-15m-1765751400 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1765728000 (行数: 850)
     [√] 处理完成 -> btc-updown-15m-1765219500 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1765578600 (行数: 842)
     [√] 处理完成 -> btc-updown-15m-1765431000 (行数: 889)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765335600 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1765656000 (行数: 884)
     [√] 处理完成 -> btc-updown-15m-1765633500 (行数: 856)
     [√] 处理完成 -> btc-updown-15m-1765755900 (行数: 813)
     [√] 处理完成 -> btc-updown-15m-1765407600 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1765315800 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1765618200 (行数: 373)
     [√] 处理完成 -> btc-updown-15m-1765539000 (行数: 932)
     [√] 处理完成 -> btc-updown-15m-1765192500 (行数: 816)
     [√] 处理完成 -> btc-updown-15m-1765178100 (行数: 900)
     [√] 处理完成 -> btc-updown-15m-1765508400 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1765691100 (行数: 904)
     [√] 处理完成 -> btc-updown-15m-1765242000 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765400400 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1765361700 (行数: 818)
     [√] 处理完成 -> btc-updown-15m-1765341900 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765567800 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1765620900 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1765770300 (行数: 905)
     [√] 处理完成 -> btc-updown-15m-1765637100 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1765261800 (行数: 902)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 处理完成 -> btc-updown-15m-1765652400 (行数: 908)
     [√] 处理完成 -> btc-updown-15m-1765330200 (行数: 911)
     [√] 处理完成 -> btc-updown-15m-1765402200 (行数: 905)
     [√] 处理完成 -> btc-updown-15m-1765728900 (行数: 840)
     [√] 处理完成 -> btc-updown-15m-1765196100 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1765369800 (行数: 851)
     [√] 处理完成 -> btc-updown-15m-1765649700 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1765583100 (行数: 918)
     [√] 处理完成 -> btc-updown-15m-1765209600 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1765688400 (行数: 838)
     [√] 处理完成 -> btc-updown-15m-1765223100 (行数: 910)
     [√] 处理完成 -> btc-updown-15m-1765606500 (行数: 910)
     [√] 处理完成 -> btc-updown-15m-1765365300 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1765247400 (行数: 914)
     [√] 处理完成 -> btc-updown-15m-1765675800 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1765511100 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765294200 (行数: 877)
     [√] 处理完成 -> btc-updown-15m-1765182600 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1765417500 (行数: 862)
     [√] 处理完成 -> btc-updown-15m-1765499400 (行数: 488)
     [√] 处理完成 -> btc-updown-15m-1765550700 (行数: 883)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765242900 (行数: 917)
     [√] 处理完成 -> btc-updown-15m-1765753200 (行数: 897)
     [√] 处理完成 -> btc-updown-15m-1765603800 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1765623600 (行数: 794)
     [√] 处理完成 -> btc-updown-15m-1765341000 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765262700 (行数: 839)
     [√] 处理完成 -> btc-updown-15m-1765264500 (行数: 832)
     [√] 处理完成 -> btc-updown-15m-1765656900 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1765431900 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1765707300 (行数: 846)
     [√] 处理完成 -> btc-updown-15m-1765216800 (行数: 882)
     [√] 处理完成 -> btc-updown-15m-1765625400 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1765474200 (行数: 866)
     [√] 处理完成 -> btc-updown-15m-1765755000 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1765236600 (行数: 883)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765676700 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765184400 (行数: 816)
     [√] 处理完成 -> btc-updown-15m-1765681200 (行数: 901)
     [√] 处理完成 -> btc-updown-15m-1765539900 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1765596600 (行数: 904)
     [√] 处理完成 -> btc-updown-15m-1765368900 (行数: 874)
     [√] 处理完成 -> btc-updown-15m-1765197000 (行数: 844)
     [√] 处理完成 -> btc-updown-15m-1765180800 (行数: 51)
     [√] 处理完成 -> btc-updown-15m-1765239300 (行数: 898)
     [√] 处理完成 -> btc-updown-15m-1765729800 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1765260900 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1765277100 (行数: 859)
     [√] 处理完成 -> btc-updown-15m-1765435500 (行数: 902)
     [√] 处理完成 -> btc-updown-15m-1765599300 (行数: 889)
     [√] 处理完成 -> btc-updown-15m-1765771200 (行数: 852)
     [√] 处理完成 -> btc-updown-15m-1765621800 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1765725300 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1765413900 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1765246500 (行数: 853)
     [√] 处理完成 -> btc-updown-15m-1765674900 (行数: 851)
     [√] 处理完成 -> btc-updown-15m-1765607400 (行数: 850)
     [√] 处理完成 -> btc-updown-15m-1765740600 (行数: 882)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 处理完成 -> btc-updown-15m-1765234800 (行数: 817)
     [√] 处理完成 -> btc-updown-15m-1765456200 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1765433700 (行数: 928)
     [√] 处理完成 -> btc-updown-15m-1765208700 (行数: 858)
     [√] 处理完成 -> btc-updown-15m-1765594800 (行数: 953)
     [√] 处理完成 -> btc-updown-15m-1765602900 (行数: 832)
     [√] 处理完成 -> btc-updown-15m-1765752300 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1765551600 (行数: 808)
     [√] 处理完成 -> btc-updown-15m-1765498500 (行数: 284)
     [√] 处理完成 -> btc-updown-15m-1765670400 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1765312200 (行数: 910)
     [√] 处理完成 -> btc-updown-15m-1765243800 (行数: 828)
     [√] 处理完成 -> btc-updown-15m-1765263600 (行数: 944)
     [√] 处理完成 -> btc-updown-15m-1765420200 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765566000 (行数: 854)
     [√] 处理完成 -> btc-updown-15m-1765340100 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1765622700 (行数: 927)
     [√] 处理完成 -> btc-updown-15m-1765528200 (行数: 844)
     [√] 处理完成 -> btc-updown-15m-1765386000 (行数: 912)
     [√] 处理完成 -> btc-updown-15m-1765179900 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1765680300 (行数: 879)
     [√] 处理完成 -> btc-updown-15m-1765347300 (行数: 857)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765505700 (行数: 906)
     [√] 处理完成 -> btc-updown-15m-1765624500 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1765265400 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1765657800 (行数: 890)
     [√] 处理完成 -> btc-updown-15m-1765314000 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1765677600 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1765754100 (行数: 867)
     [√] 处理完成 -> btc-updown-15m-1765555200 (行数: 903)
     [√] 处理完成 -> btc-updown-15m-1765405800 (行数: 137)
     [√] 处理完成 -> btc-updown-15m-1765674000 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765317600 (行数: 862)
     [√] 处理完成 -> btc-updown-15m-1765413000 (行数: 908)
     [√] 处理完成 -> btc-updown-15m-1765757700 (行数: 866)
     [√] 处理完成 -> btc-updown-15m-1765345500 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1765626300 (行数: 894)
     [√] 处理完成 -> btc-updown-15m-1765267200 (行数: 364)
     [√] 处理完成 -> btc-updown-15m-1765562400 (行数: 100)
     [√] 处理完成 -> btc-updown-15m-1765425600 (行数: 920)
     [√] 处理完成 -> btc-updown-15m-1765685700 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1765368000 (行数: 841)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765197900 (行数: 935)
     [√] 处理完成 -> btc-updown-15m-1765382400 (行数: 862)
     [√] 处理完成 -> btc-updown-15m-1765260000 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1765343700 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765750500 (行数: 866)
     [√] 处理完成 -> btc-updown-15m-1765310400 (行数: 910)
     [√] 处理完成 -> btc-updown-15m-1765258200 (行数: 833)
     [√] 处理完成 -> btc-updown-15m-1765386900 (行数: 483)
     [√] 处理完成 -> btc-updown-15m-1765179000 (行数: 884)
     [√] 处理完成 -> btc-updown-15m-1765193400 (行数: 901)
     [√] 处理完成 -> btc-updown-15m-1765538100 (行数: 889)
     [√] 处理完成 -> btc-updown-15m-1765454400 (行数: 814)
     [√] 处理完成 -> btc-updown-15m-1765334700 (行数: 832)
     [√] 处理完成 -> btc-updown-15m-1765430100 (行数: 855)
     [√] 处理完成 -> btc-updown-15m-1765273500 (行数: 912)
     [√] 处理完成 -> btc-updown-15m-1765406700 (行数: 894)
     [√] 处理完成 -> btc-updown-15m-1765488600 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1765314900 (行数: 820)
     [√] 处理完成 -> btc-updown-15m-1765744200 (行数: 896)
     [√] 处理完成 -> btc-updown-15m-1765602000 (行数: 927)
     [√] 处理完成 -> btc-updown-15m-1765721700 (行数: 934)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765566900 (行数: 840)
     [√] 处理完成 -> btc-updown-15m-1765437300 (行数: 816)
     [√] 处理完成 -> btc-updown-15m-1765452600 (行数: 899)
     [√] 处理完成 -> btc-updown-15m-1765712700 (行数: 849)
     [√] 处理完成 -> btc-updown-15m-1765441800 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1765353600 (行数: 392)
     [√] 处理完成 -> btc-updown-15m-1765510200 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1765461600 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765222200 (行数: 831)
     [√] 处理完成 -> btc-updown-15m-1765662300 (行数: 866)
     [√] 处理完成 -> btc-updown-15m-1765695600 (行数: 951)
     [√] 处理完成 -> btc-updown-15m-1765549800 (行数: 926)
     [√] 处理完成 -> btc-updown-15m-1765569600 (行数: 860)
     [√] 处理完成 -> btc-updown-15m-1765582200 (行数: 860)
     [√] 处理完成 -> btc-updown-15m-1765281600 (行数: 923)
     [√] 处理完成 -> btc-updown-15m-1765584000 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1765403100 (行数: 292)
     [√] 处理完成 -> btc-updown-15m-1765307700 (行数: 830)
     [√] 处理完成 -> btc-updown-15m-1765664100 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1765545300 (行数: 843)
     [√] 处理完成 -> btc-updown-15m-1765224000 (行数: 812)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 处理完成 -> btc-updown-15m-1765636200 (行数: 834)
     [√] 处理完成 -> btc-updown-15m-1765355400 (行数: 913)
     [√] 处理完成 -> btc-updown-15m-1765331100 (行数: 870)
     [√] 处理完成 -> btc-updown-15m-1765714500 (行数: 887)
     [√] 处理完成 -> btc-updown-15m-1765597500 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1765293300 (行数: 877)
     [√] 处理完成 -> btc-updown-15m-1765237500 (行数: 915)
     [√] 处理完成 -> btc-updown-15m-1765370700 (行数: 892)
     [√] 处理完成 -> btc-updown-15m-1765475100 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1765731600 (行数: 833)
     [√] 处理完成 -> btc-updown-15m-1765711800 (行数: 863)
     [√] 处理完成 -> btc-updown-15m-1765576800 (行数: 836)
     [√] 处理完成 -> btc-updown-15m-1765442700 (行数: 858)
     [√] 处理完成 -> btc-updown-15m-1765350900 (行数: 917)
     [√] 处理完成 -> btc-updown-15m-1765444500 (行数: 911)
     [√] 处理完成 -> btc-updown-15m-1765647000 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1765416600 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765473300 (行数: 827)
     [√] 处理完成 -> btc-updown-15m-1765169100 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765396800 (行数: 644)
     [√] 处理完成 -> btc-updown-15m-1765248300 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1765609200 (行数: 908)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765183500 (行数: 919)
     [√] 处理完成 -> btc-updown-15m-1765295100 (行数: 868)
     [√] 处理完成 -> btc-updown-15m-1765584900 (行数: 894)
     [√] 处理完成 -> btc-updown-15m-1765592100 (行数: 928)
     [√] 处理完成 -> btc-updown-15m-1765218600 (行数: 902)
     [√] 处理完成 -> btc-updown-15m-1765658700 (行数: 837)
     [√] 处理完成 -> btc-updown-15m-1765579500 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765256400 (行数: 901)
     [√] 处理完成 -> btc-updown-15m-1765735200 (行数: 816)
     [√] 处理完成 -> btc-updown-15m-1765374300 (行数: 917)
     [√] 处理完成 -> btc-updown-15m-1765224900 (行数: 883)
     [√] 处理完成 -> btc-updown-15m-1765232100 (行数: 901)
     [√] 处理完成 -> btc-updown-15m-1765446300 (行数: 890)
     [√] 处理完成 -> btc-updown-15m-1765704600 (行数: 343)
     [√] 处理完成 -> btc-updown-15m-1765643400 (行数: 862)
     [√] 处理完成 -> btc-updown-15m-1765321200 (行数: 841)
     [√] 处理完成 -> btc-updown-15m-1765270800 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1765761300 (行数: 845)
     [√] 处理完成 -> btc-updown-15m-1765399500 (行数: 832)
     [√] 处理完成 -> btc-updown-15m-1765187100 (行数: 847)
     [√] 处理完成 -> btc-updown-15m-1765378800 (行数: 862)
     [√] 处理完成 -> btc-updown-15m-1765291500 (行数: 876)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765634400 (行数: 853)
     [√] 处理完成 -> btc-updown-15m-1765515600 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1765207800 (行数: 914)
     [√] 处理完成 -> btc-updown-15m-1765357200 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765716300 (行数: 900)
     [√] 处理完成 -> btc-updown-15m-1765647900 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1765667700 (行数: 858)
     [√] 处理完成 -> btc-updown-15m-1765304100 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1765227600 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1765690200 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1765587600 (行数: 850)
     [√] 处理完成 -> btc-updown-15m-1765328400 (行数: 893)
     [√] 处理完成 -> btc-updown-15m-1765768500 (行数: 894)
     [√] 处理完成 -> btc-updown-15m-1765580400 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1765619100 (行数: 845)
     [√] 处理完成 -> btc-updown-15m-1765220400 (行数: 856)
     [√] 处理完成 -> btc-updown-15m-1765612800 (行数: 371)
     [√] 处理完成 -> btc-updown-15m-1765660500 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1765541700 (行数: 905)
     [√] 处理完成 -> btc-updown-15m-1765632600 (行数: 928)
     [√] 处理完成 -> btc-updown-15m-1765350000 (行数: 846)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')

     [√] 处理完成 -> btc-updown-15m-1765225800 (行数: 876)
     [√] 处理完成 -> btc-updown-15m-1765375200 (行数: 816)
     [√] 处理完成 -> btc-updown-15m-1765233000 (行数: 834)
     [√] 处理完成 -> btc-updown-15m-1765665900 (行数: 905)
     [√] 处理完成 -> btc-updown-15m-1765673100 (行数: 643)
     [√] 处理完成 -> btc-updown-15m-1765734300 (行数: 864)
     [√] 处理完成 -> btc-updown-15m-1765447200 (行数: 905)
     [√] 处理完成 -> btc-updown-15m-1765659600 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765585800 (行数: 880)
     [√] 处理完成 -> btc-updown-15m-1765593000 (行数: 872)
     [√] 处理完成 -> btc-updown-15m-1765738800 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1765548000 (行数: 851)
     [√] 处理完成 -> btc-updown-15m-1765202400 (行数: 902)
     [√] 处理完成 -> btc-updown-15m-1765630800 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1765344600 (行数: 912)
     [√] 处理完成 -> btc-updown-15m-1765440000 (行数: 384)
     [√] 处理完成 -> btc-updown-15m-1765320300 (行数: 885)
     [√] 处理完成 -> btc-updown-15m-1765642500 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1765586700 (行数: 904)
     [√] 处理完成 -> btc-updown-15m-1765717200 (行数: 823)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765274400 (行数: 832)
     [√] 处理完成 -> btc-updown-15m-1765514700 (行数: 862)
     [√] 处理完成 -> btc-updown-15m-1765453500 (行数: 909)
     [√] 处理完成 -> btc-updown-15m-1765288800 (行数: 897)
     [√] 处理完成 -> btc-updown-15m-1765356300 (行数: 866)
     [√] 处理完成 -> btc-updown-15m-1765206900 (行数: 873)
     [√] 处理完成 -> btc-updown-15m-1765226700 (行数: 871)
     [√] 处理完成 -> btc-updown-15m-1765745100 (行数: 845)
     [√] 处理完成 -> btc-updown-15m-1765464300 (行数: 820)
     [√] 处理完成 -> btc-updown-15m-1765305000 (行数: 840)
     [√] 处理完成 -> btc-updown-15m-1765252800 (行数: 844)
     [√] 处理完成 -> btc-updown-15m-1765489500 (行数: 913)
     [√] 处理完成 -> btc-updown-15m-1765661400 (行数: 881)
     [√] 处理完成 -> btc-updown-15m-1765303200 (行数: 859)
     [√] 处理完成 -> btc-updown-15m-1765743300 (行数: 865)
     [√] 处理完成 -> btc-updown-15m-1765710000 (行数: 859)
     [√] 处理完成 -> btc-updown-15m-1765272600 (行数: 869)
     [√] 处理完成 -> btc-updown-15m-1765769400 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1765259100 (行数: 890)
     [√] 处理完成 -> btc-updown-15m-1765548900 (行数: 877)
     [√] 处理完成 -> btc-updown-15m-1765419300 (行数: 923)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765694700 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765568700 (行数: 914)
     [√] 处理完成 -> btc-updown-15m-1765440900 (行数: 745)
     [√] 处理完成 -> btc-updown-15m-1765457100 (行数: 862)
     [√] 处理完成 -> btc-updown-15m-1765352700 (行数: 841)
     [√] 处理完成 -> btc-updown-15m-1765713600 (行数: 894)
     [√] 处理完成 -> btc-updown-15m-1765663200 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765741500 (行数: 891)
     [√] 处理完成 -> btc-updown-15m-1765460700 (行数: 919)
     [√] 处理完成 -> btc-updown-15m-1765233900 (行数: 918)
     [√] 处理完成 -> btc-updown-15m-1765414800 (行数: 826)
     [√] 处理完成 -> btc-updown-15m-1765665000 (行数: 886)
     [√] 处理完成 -> btc-updown-15m-1765715400 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1765434600 (行数: 826)
     [√] 处理完成 -> btc-updown-15m-1765276200 (行数: 855)
     [√] 处理完成 -> btc-updown-15m-1765354500 (行数: 533)
     [√] 处理完成 -> btc-updown-15m-1765280700 (行数: 831)
     [√] 处理完成 -> btc-updown-15m-1765593900 (行数: 812)
     [√] 处理完成 -> btc-updown-15m-1765486800 (行数: 824)
     [√] 处理完成 -> btc-updown-15m-1765730700 (行数: 921)
     [√] 处理完成 -> btc-updown-15m-1765371600 (行数: 890)
     [√] 处理完成 -> btc-updown-15m-1765199700 (行数: 871)

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

     [√] 处理完成 -> btc-updown-15m-1765443600 (行数: 847)
     [√] 处理完成 -> btc-updown-15m-1765351800 (行数: 859)
     [√] 处理完成 -> btc-updown-15m-1765710900 (行数: 861)
     [√] 处理完成 -> btc-updown-15m-1765529100 (行数: 829)
     [√] 处理完成 -> btc-updown-15m-1765608300 (行数: 909)
     [√] 处理完成 -> btc-updown-15m-1765249200 (行数: 888)
     [√] 处理完成 -> btc-updown-15m-1765646100 (行数: 878)
     [√] 处理完成 -> btc-updown-15m-1765325700 (行数: 875)
     [√] 处理完成 -> btc-updown-15m-1765421100 (行数: 841)
     [√] 处理完成 -> btc-updown-15m-1765445400 (行数: 857)
     [√] 处理完成 -> btc-updown-15m-1765206000 (行数: 862)
     [√] 处理完成 -> btc-updown-15m-1765305900 (行数: 905)
     [√] 处理完成 -> btc-updown-15m-1765313100 (行数: 852)

🔗 正在拼接最终大总表...

/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:36: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_raw['timestamp'] = df_raw['timestamp'].dt.floor('S')
/var/folders/j4/kwkcy_yx4s5fg992bwd59h140000gn/T/ipykernel_45690/1266925292.py:60: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  full_idx = pd.date_range(start=df_wide.index.min(), end=df_wide.index.max(), freq='1S')

🎉 高频因子大总表生成完毕！保存在: /Volumes/KIOXIA/Project/lob/advanced_hft_features/grand_total_HFT_master.parquet

In [14]:
df_grand_total

,timestamp,Down_BUY_trade_size,Down_SELL_trade_size,Up_BUY_trade_size,Up_SELL_trade_size,Down_BUY_trade_count,Down_SELL_trade_count,Up_BUY_trade_count,Up_SELL_trade_count,Down_BUY_notional,Down_SELL_notional,Up_BUY_notional,Up_SELL_notional,Down_BUY_vwap,Down_SELL_vwap,Up_BUY_vwap,Up_SELL_vwap,Net_OFI,slug
0,2025-12-01 05:00:23+00:00,0.0,0.00,2.272726,0.0,0.0,0.0,1.0,0.0,0.00,0.0000,0.999999,0.0,0.564737,0.57,0.44,0.41,1.000000,btc-updown-15m-1764565200
1,2025-12-01 05:00:24+00:00,0.0,0.00,111.720000,0.0,0.0,0.0,1.0,0.0,0.00,0.0000,50.274000,0.0,0.564737,0.57,0.45,0.41,1.000000,btc-updown-15m-1764565200
2,2025-12-01 05:00:25+00:00,19.0,0.00,0.000000,0.0,2.0,0.0,0.0,0.0,10.73,0.0000,0.000000,0.0,0.564737,0.57,0.45,0.41,-1.000000,btc-updown-15m-1764565200
3,2025-12-01 05:00:26+00:00,9.0,0.00,10.000000,0.0,1.0,0.0,2.0,0.0,5.22,0.0000,4.300000,0.0,0.580000,0.57,0.43,0.41,0.052632,btc-updown-15m-1764565200
4,2025-12-01 05:00:27+00:00,10.0,0.00,0.000000,0.0,1.0,0.0,0.0,0.0,5.80,0.0000,0.000000,0.0,0.580000,0.57,0.43,0.41,-1.000000,btc-updown-15m-1764565200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1050777,2025-12-15 05:00:58+00:00,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.00,0.0000,0.000000,0.0,0.982442,0.99,0.01,0.05,0.000000,btc-updown-15m-1765773900
1050778,2025-12-15 05:00:59+00:00,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.00,0.0000,0.000000,0.0,0.982442,0.99,0.01,0.05,0.000000,btc-updown-15m-1765773900
1050779,2025-12-15 05:01:00+00:00,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.00,0.0000,0.000000,0.0,0.982442,0.99,0.01,0.05,0.000000,btc-updown-15m-1765773900
1050780,2025-12-15 05:01:01+00:00,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.00,0.0000,0.000000,0.0,0.982442,0.99,0.01,0.05,0.000000,btc-updown-15m-1765773900
1050781,2025-12-15 05:01:02+00:00,0.0,119.76,0.000000,0.0,0.0,1.0,0.0,0.0,0.00,118.5624,0.000000,0.0,0.982442,0.99,0.01,0.05,1.000000,btc-updown-15m-1765773900